### ISSUE TITLE
shinken2.0 cannot start webui

### ISSUE THREAD

**Issue by itxx00** [naparuba/shinken#1088]
after installed shinken 2.0 and webui and restarted all the services,
the webui cannot startup, and no program listen on port 7767.

https://asciinema.org/a/7604

**Comment by Hlearner** [comment]
Pleaaaase i've installed shinken 2.4 with pip method, ans add the webui module declaration to the broker but still the webui can't start, the broker log has no message error and i don't know where is the problem, i've installed shinken many times but i always get the same problem
i am on vmware ubuntu 14.04 
could anyone help me pleaaaaaaaaaaaaase

**Comment by fninja** [comment]
same here.
i followed the steps as specified above.
broker log gives me this:
```
[1461592545] WARNING: [broker-master] The module type webui for WebUI was not found in modules!
[1461592545] INFO: [broker-master] I correctly loaded the modules: []
```
No webui listening on `:7767` :
```
$ sudo netstat -plnt | grep 776*
tcp        0      0 0.0.0.0:7768            0.0.0.0:*               LISTEN      51247/python2.7 
tcp        0      0 0.0.0.0:7769            0.0.0.0:*               LISTEN      51288/python2.7 
tcp        0      0 127.0.0.1:7770          0.0.0.0:*               LISTEN      51350/python2.7 
tcp        0      0 0.0.0.0:7771            0.0.0.0:*               LISTEN      51266/python2.7 
tcp        0      0 0.0.0.0:7772            0.0.0.0:*               LISTEN      51312/python2.7 
tcp        0      0 0.0.0.0:7773            0.0.0.0:*               LISTEN      51333/python2.7
```
