### ISSUE TITLE
A note for windows

### ISSUE THREAD

**Issue by naparuba** [naparuba/shinken#1105]
For 2.0 and windows, for pycurl, yu need python 2.7.6. We should update the doc

I'm launching all under windows to be sure we can still be windows compatible :)

**Comment by Seb-Solon** [comment]
Are we dropping windows support?

**Comment by naparuba** [comment]
we still make it working on windows.
But we don't have the power to maintain the full windows integration stack (msi and co) that's all.

so we should limit to install doc but it's just too heavy currently to propose a full nightly build and co for windows. So we must limit to acceptable efforts :)

**Comment by naparuba** [comment]
ps: I think one day someone will think it can be cool to have a full windows installation automated with a dedicated UI and agent, and it can sell it. And he/she will be right ^^

but it's a lot of work, and out of scope for the framework, because I think most of the work to make it works "great" in thewindows world will be check plugins, agent and other easy UIs.
