### ISSUE TITLE
default mail bin location and macros use.

### ISSUE THREAD

**Issue by claneys** [naparuba/shinken#1178]
Hi,

default mail binary location under rhel and debian aren't the same. 
What about register all those possible difference under etc/resource.d/path.cfg with a macro for each one that will be used in command ?

**Comment by claneys** [comment]
What about that ? 
Can it be merged in master branch ?

**Comment by Seb-Solon** [comment]
Make a pull request, I'll review it. I need to understand the whole case because I did not read this issue.

**Comment by claneys** [comment]
Done.

Issue come from a difference between debian-like and red-hat like distro that did not place 'mail' binary at the same place. So, notify commands were wrong.

Initial proposal was to add a macro that configure path to the mail binary and naparuba suggests that can be better to have a notification plugin to send mail. And here it is :)

**Comment by claneys** [comment]
It want to merge it in master.
I thinks it is the right place to host this plugin and add valuable notifications to shinken by default.

**Comment by claneys** [comment]
pull request here #1653.

I close this issue since it is not relevant and has nothing to do with the initial issue.
