### ISSUE TITLE
Installation error on FreeBSD

### ISSUE THREAD

**Issue by ghost** [naparuba/shinken#1180]
On CentOS release 6.5 "pip install shinken" went fine and all services are up and running. On FreeBSD 10.0-RELEASE-p1 I got the following error:

pip install shinken
...
  Running setup.py install for shinken
    Parser error no such option: --compile
    ('updating path in %s', 'build/shinken.cfg')
    error: can't copy 'bin/rc.d/shinken_arbiter': doesn't exist or not a regular file
    Complete output from command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/shinken/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2fMdb9-record/install-record.txt --single-version-externally-managed --compile:
    Parser error no such option: --compile
...
running install_data

error: can't copy 'bin/rc.d/shinken_arbiter': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
Command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/shinken/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2fMdb9-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/shinken
Storing debug log for failure in /root/.pip/pip.log

**Comment by Seb-Solon** [comment]
Should be fine with new setup.py

**Comment by OranJuiceJohnes** [comment]
pip on debian jessie standard install seems to have a similar problem. Just fresh and off the sehlf install.

aptitude install python-pip python-pycurl python-pycurl python-cherrypy nagios-plugins
adduser shinken
pip install shinken

...

Downloading/unpacking shinken
  Downloading Shinken-2.4.2.tar.gz (27.2MB): 27.2MB downloaded
  Running setup.py (path:/tmp/pip-build-UpmAms/shinken/setup.py) egg_info for package shinken
    Parser error no such option: --egg-base
    ('updating path in %s', 'build/shinken.cfg')

    warning: no files found matching '.bat' under directory 'windows'
    warning: no files found matching '.reg' under directory 'windows'
    warning: no files found matching 'test'
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.debug' found anywhere in distribution
    warning: no previously-included files matching '.pid' found anywhere in distribution
    warning: no previously-included files matching '.exe' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no files found matching 'var/void_for_git'
    Shinken setup done
Installing collected packages: shinken
  Running setup.py install for shinken
    Parser error no such option: --compile
    ('updating path in %s', 'build/shinken.cfg')

    warning: no files found matching '.bat' under directory 'windows'
    warning: no files found matching '.reg' under directory 'windows'
    warning: no files found matching 'test'
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.debug' found anywhere in distribution
    warning: no previously-included files matching '.pid' found anywhere in distribution
    warning: no previously-included files matching '.exe' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no files found matching 'var/void_for_git'
    Changing owner of /etc/shinken to shinken:shinken
    Changing owner of /var/run/shinken to shinken:shinken
    Changing owner of /var/log/shinken to shinken:shinken
    Changing owner of /var/lib/shinken/ to shinken:shinken
    Changing owner of /var/lib/shinken/libexec to shinken:shinken
    Changing owner of /usr/bin/shinken-poller to shinken:shinken
    Changing owner of /usr/bin/shinken-discovery to shinken:shinken
    Changing owner of /usr/bin/shinken-receiver to shinken:shinken
    Changing owner of /usr/bin/shinken-reactionner to shinken:shinken
    Changing owner of /usr/bin/shinken-broker to shinken:shinken
    Changing owner of /usr/bin/shinken-scheduler to shinken:shinken
    Changing owner of /usr/bin/shinken to shinken:shinken
    Changing owner of /usr/bin/shinken-arbiter to shinken:shinken
    Shinken setup done
Successfully installed shinken
Cleaning up...
