### ISSUE TITLE
pip install shinken --upgrade overwrites configuration files (amongst other things)

### ISSUE THREAD

**Issue by dmsimard** [naparuba/shinken#1278]
I ran a `pip install shinken --upgrade` to upgrade from 2.0.2 to 2.0.3.

It's a good thing that:
a) I had backups
b) My configuration was versioned

From what I remember, the installation process did the following:
* Deleted all the logs in /var/log/shinken (not that I mind that much, but it shouldn't do that)
* Overwrote all the configuration files in /etc/shinken by the ones provided in the package
    * The ini files in /etc/shinken/daemons (flushed all my SSL config)
    * Command files that had been modified in /etc/shinken/commands
    * Templates in /etc/shinken/templates (ex: generic-host, generic-service)
    * workhours timeperiods in /etc/shinken/timeperiods
    * contactgroups in /etc/shinken/contactgroups
    * daemon *-master configs in their respective folders

There are probably others but that's what mostly comes to mind right now.

This may or may not be possible to manage with pip but I thought I would report this anyway.

**Comment by dmsimard** [comment]
@naparuba How are things from 2.0.3 to 2.2 ?

**Comment by t0xicCode** [comment]
still overwrites for me (yay for versionned configuration).

**Comment by Seb-Solon** [comment]
For me it's completely normal. pip / setup.py is not a package manager. If you don't want etc file to be overriden you can try to use something like --etc-file=/dev/null (i'm not sure it works). 

In the next version of setup.py you will only need to do setup.py install-data to not have etc file copied.

**Comment by t0xicCode** [comment]
:+1: for the install-data option

**Comment by titilambert** [comment]
@dmsimard Hello !
The setup.py was completely rewritten. Now, it uses PBR and should handle all of this :)
Could you try with the 2.4BETA1 version:
```sudo python setup.py install```
Modify some config files
```sudo python setup.py install```
You config files should be not replaced :)

Thanks !

**Comment by titilambert** [comment]
@dmsimard ,
I close this bug, Feel free to reopen it if it's not working for you

**Comment by setaou** [comment]
The same thing (/var/log/shinken/* deleted and config files overwritten) occurred to me when upgrading from 2.4.1 to 2.4.3, so this bug is still present.

**Comment by NicolasLM** [comment]
+1 
`pip install --upgrade shinken` from 2.4.2 to 2.4.3 removed logs and configuration files.
