### ISSUE TITLE
Missing notifications on Escalation configs

### ISSUE THREAD

**Issue by pedrojimenez** [naparuba/shinken#1386]
We have a test lab with a Shinken 2.0.3 (via PIP) on a Ubuntu 12.04 Server.

We are configuring **escalations** in a very simple scenario.
* 1 Host (mongomaster) with no escalation. Using generic-host definition.
* 2 Hosts (dummy01, dummy02) with host and service escalation (http)

The info for all of this configs is splitted in this files via Gist:
* https://gist.github.com/pedrojimenez/a1113af89fff481cbebb
* https://gist.github.com/pedrojimenez/16c61b993367dc4430a3
* https://gist.github.com/pedrojimenez/b9810c3c9ff31cce18e1
* https://gist.github.com/pedrojimenez/3dfb0bcbbc16e48a405a

We always get a situation where notifications are not sent anymore. Sometimes it happens at second/third one, others at sixth/seventh as maximum. It makes no difference with Host or Service notifications, it just only don't send anymore about these hosts.

This is a real log capture of this afternoon (we got only 2 notifications). There is no more notifications until now (after more than an hour).
* https://gist.github.com/pedrojimenez/5adef67b36aec536fc16

We have also tested it without escalations and same kind of results.

**Comment by naparuba** [comment]
Still the case with master version?

**Comment by Seb-Solon** [comment]
I cannot reproduce this on upstream. Try to provide simpler configuration sample so that the bug is easy to reproduce. I had to adapt yours, maybe this is way it work on my side. 

Feel free to open another issue for 2.4.
