### ISSUE TITLE
Default TCP Scan method : nmap_discovery_runner.py

### ISSUE THREAD

**Issue by claneys** [naparuba/shinken#1429]
Hi,

The default method used by this discovery is a full TCP Connect scan, that will scan by fully open a TCP port. But nmap advice to use SYN scan as it is quicker and unobstrusive.

Does we have a reason to  choose TCP Connect scan ? I had to be the less intrusive possible at my clients and no crash a random system in a scan.

Thanks

**Comment by Seb-Solon** [comment]
Discovery support is more or less dropped. Can we close this? 

For now I only move milestone

**Comment by claneys** [comment]
So, let's make a Syn scan then :)
