### ISSUE TITLE
Error 404: Not Found into WebUi interface: wall section and details hosts sections

### ISSUE THREAD

**Issue by jimbowarrior** [naparuba/shinken#1432]
hello,
I get this error message into Wall and Host (webui) details Linux_ssh_memory etc...

Sorry, the requested URL 'http://10.100.0.18:7767/wall' caused an error:

Not found: '/wall'

I  uninstall shinken, reboot server, install by pip install shinken. Same error.
My server is a Linux Debian 7 up to date 32 bit.

Regards

**Comment by Dual-Boot** [comment]
You can have a look here : 
https://github.com/shinken-monitoring/mod-webui/issues/102

 Regards,

**Comment by jimbowarrior** [comment]
I already read it, ticket closed and no solutions....

**Comment by jimbowarrior** [comment]
I juste install shinken on my Ubuntu 14.10 64 bit, "Wall" is working find but still error message on host details regarding Linux_ssh, linux_ssh_memory and Linux_ssh_processes

**Comment by Frescha** [comment]
wrong repo
