### ISSUE TITLE
Host check returning 1 (WARNING) generates no notification

### ISSUE THREAD

**Issue by openglx** [naparuba/shinken#1437]
Hi all,

I've noticed and am able to reproduce in a simple lab (Shinken 2.0.3 from EPEL, Python 2.6.6, CentOS 6.6) that a host that is marked as 'DOWN' will not send any recovery message if the host check goes to 'WARNING' - but the host itself will be considered 'UP'.

In a nutshell, this happens:

* Shinken starts, host 'localhost' is pending [good]
* 'localhost' check_host_alive returns 0 (OK), host is UP: no message is sent [good]
* 'localhost' check_host_alive returns 2 (CRITICAL) in three consecutive checks (max_check_attempts) [good]
* a notification 'HOST DOWN' is generated [good]
* 'localhost' check_host_alive returns 1 (WARNING): host is now 'UP' (on WebUI and LiveStatus API), current attempts is marking 3/3 (HARD), no notification was generated [wrong! there was a state change!]
* 'localhost' check_host_alive returns 0 (OK): host continues 'UP', current attempts is now 1/3 (SOFT), and no notification was generated [partially wrong, shouldn't generate message from WARNING->OK but should have notified CRITICAL->OK]

Running the daemons with debug didn't get much insight, and looking into the code also wasn't something obvious.

Please let me know which files are interesting to be attached.

Best regards,
openglx

**Comment by openglx** [comment]
During my tests I've also encountered some issues with services notifications when it changes between non-OK states (e.g. WARNING->CRITICAL and vice-versa).

My configuration has notificationways set up, and flap detection is disabled.

I'm now working trying to pin-point any specific setting that might be triggering these odd non-notifications.

**Comment by Seb-Solon** [comment]
Please try to reproduce this upstream. Bug report on previous version may be outdated.

**Comment by david-guenault** [comment]
Please could you provide a full set of configuration in order to be able to reproduce ?

Thx for reporting

**Comment by naparuba** [comment]
Did you try with host aggressive check for the host? It change this behavior.

**Comment by flaf** [comment]
Hi,
For information, I have posted exactly the same issue here https://github.com/naparuba/shinken/issues/1341 and the problem was been solved.

**Comment by openglx** [comment]
@flaf thanks for your update, have seen any strange behaviour on service checks as notifications not to sent to all contacts when it transitions from warning to critical?

**Comment by openglx** [comment]
Retested with 2.2-RC1, which contains #1341 fix, and am happy with the result.
