### ISSUE TITLE
[2.2-RC1] contactgroup no longer accepting contactgroup_members ?

### ISSUE THREAD

**Issue by openglx** [naparuba/shinken#1440]
On Shinken 2.0.3 this was valid configuration:

```
define contactgroup{
    contactgroup_name     NOC
    alias                 Network Operations Centre
    contactgroup_members  Team1,Team2,Team3,NOCManagers
}
```

Unfortunately on Shinken 2.2-RC1 (CentOS 6.6, Python 2.6.6) this is failing:

```
[1420650932] INFO: [Shinken] Checking contacts...
[1420650932] INFO: [Shinken]    Checked 75 contacts
[1420650872] INFO: [Shinken] Checking contactgroups...
[1420650872] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member 
[1420650872] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member 
[1420650872] ERROR: [Shinken] [items] In NOC is incorrect ; from /etc/shinken/contactgroups/NOC.cfg:1
[1420650872] ERROR: [Shinken]   contactgroups conf incorrect!!
[1420650872] INFO: [Shinken]    Checked 49 contactgroups
```

Any suggestions for troubleshooting?

**Comment by gst** [comment]
can you give the definition of your Team1+Team2+Team3+NOCManagers contactgroups ?

**Comment by gst** [comment]
according to this : 

[1420650872] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member 
[1420650872] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member

one of your contactgroup has an unknown member..

**Comment by openglx** [comment]
Hi,

Team1, Team2, and Team3 are all defined simply as

```
define contactgroup{
    contactgroup_name   Team1
    alias               This is Team 1
}
```

The NOCManager had listed the individuals

```
define contactgroup{
    contactgroup_name   NOCManagers
    alias               NOC Managers
    members             person1,person2
}
```


For any of Team1/2/3 contacts what we do is to define on the contact individual to say which team it belongs to:

```
define contact{
    use             contact-human
    contact_name    openglx
    email           openglx@...
    pager           5551234 ; contact phone number
    is_admin        1
    contactgroups      Team1
    password        my_password
        alias                         openglx
}
```

Then, contact-human is a template:

```
define contact {
    name                            contact-human
    register                        0
    host_notifications_enabled      0
    service_notifications_enabled   0
    can_submit_commands             1
}
```

**Comment by gst** [comment]
What looks/is strange is that normally the log:

> [1420650872] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member 

should have the member name listed at the end.. here it so looks empty..

if possible : could you, at least temporarily for one shot, replace in the file itemgroup.py , the line (near or on the 133th line number) :

```logger.error("[itemgroup::%s] as %s, got unknown member %s", self.get_name(), self.__class__.my_type, m)```

by:

```logger.error("[itemgroup::%s] as %s, got unknown member %r", self.get_name(), self.__class__.my_type, m)```

(basically the last %s is replaced by a %r)

and then give the log output ?

**Comment by gst** [comment]
> What looks/is strange is that normally the log:
>> [1420650872] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member

> should have the member name listed at the end.. here it so looks empty..

and if it is (empty) then I guess we could have a bug in the parsing of contactgroups or contacts..

can you assert that the exact same configuration files are parsed ok under 2.0.3 ?

**Comment by openglx** [comment]
I've changed that %s for a %r and it continues to fail without showing a name:

```
[1420666282] INFO: [Shinken] Checking contacts...
[1420666282] INFO: [Shinken]    Checked 75 contacts
[1420666282] INFO: [Shinken] Checking contactgroups...
[1420666282] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member ''
[1420666282] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member ''
[1420666282] ERROR: [Shinken] [itemgroup::NOC] as contactgroup, got unknown member ''
[1420666282] ERROR: [Shinken] [items] In NOC is incorrect ; from /etc/shinken/contactgroups/NOC.cfg:1
[1420666282] ERROR: [Shinken]   contactgroups conf incorrect!!

```


And I'm using exactly same config that used in 2.0.3 in production without issues.

**Comment by gst** [comment]
ok so effectively the code parsing the contactgroup or contacts resulted in an contact(group) with an empty name, which is bad.

would you have a trailing comma (,) in one of your contactgroup or contacts ?? If so then maybe dropping it and it'll be ok..

**Comment by gst** [comment]
but I'll try more properly with your config also.. tomorrow ;)

**Comment by openglx** [comment]
Did a grep around the config files and found no empty commas. All contact have only one group set.

The moment I comment out the ``` contactgroup_members ``` entry on my NOC.cfg it parses the config successfully.

This issue is looking incredibly similar to other I've added, #1439. Could it be that the parser isn't happy about Python 2.6 any more?

**Comment by gst** [comment]
damn, missed your python2.6 ;; yeah it's not impossible to be related to that.. see my comment in there.

**Comment by Seb-Solon** [comment]
Same here. Can you try upstream? I can't reproduce this.

**Comment by openglx** [comment]
Retested against 65ea078a7b8ae61fbbfca7951ba996963a5f3be8 - fixed.

I suppose this wasn't a bug ever existent on upstream but of some local change I did whilst investigating #1439. Sorry about the noise.
