### ISSUE TITLE
Problem in shinken 2.0.3 arbiter's api output for /get-all-states

### ISSUE THREAD

**Issue by nlm** [naparuba/shinken#1445]
The Shinken Arbiter's API output is incomplete and not in the desired format in version 2.0.3
The output shows only broker informations.

The bug can be resolved by this modification (thanks @david-guenault):
'in arbiterdaemon.py line 146 : remplace "lst" by "res"'

**Comment by david-guenault** [comment]
Note naparuba is currently working on a 2.0.4 version and the patch will be integrated

**Comment by nlm** [comment]
Ok, perfect ! It was essentially to keep a trace of the problem, and refer to it in another issue. You can close it if you already pushed the change
