### ISSUE TITLE
Problems in Arbiter API responses for /get-all-states

### ISSUE THREAD

**Issue by nlm** [naparuba/shinken#1446]
Hi, i'm using shinken v2.0.3.
I was looking at arbiter api's "get-all-states" json output and saw possible inconsistencies:

- arbiter is declaring itself "'reachable': False"
- arbiter's "realm" is empty (and maybe should)
- "realm" attribute is missing in other daemons

This was seen in shinken 2.0.3 patched to solve bug #1445

**Comment by david-guenault** [comment]
never tested this may be not related to the #1445 
need to dig into. 

could you provide a configuration to reproduce  ?

**Comment by nlm** [comment]
I don't think it's related to #1445, but the patch described is required to have this output.

No particular configuration here:
- 3 independant realms / 2 hosts per realm (1 active/1 spare)
- 1 arbiter on 1 host
- all other daemons on every host

**Comment by david-guenault** [comment]
ok i build the lab to reproduce

**Comment by david-guenault** [comment]
arbiter master is always not reachable. This is normal as the arbiter master should never be called by any other daemons. 

realm empty and realm not present, i'm not sure about this (need to read the code)

**Comment by david-guenault** [comment]
I will propose the following patch to add support of realm_name in api. May be it will be accepted or not. The problem is the api get daemons properties and try to dump the result to json. Sometime it is not serializable. This is the case for all daemons except arbiter (Realm object is not json serializable)

@@ -136,6 +136,9 @@ class IForArbiter(Interface):
                     for prop in _d:
                         if hasattr(d, prop):
                             v = getattr(d, prop)
+                            if prop == "realm":
+                                if hasattr(v,"realm_name"):
+                                    e[prop] = v.realm_name
                             # give a try to a json able object
                             try:
                                 json.dumps(v)

**Comment by nlm** [comment]
:+1:

**Comment by gst** [comment]
better : 

```
for _d in ds:
    for prop in _d:
        if hasattr(d, prop):
            v = getattr(d, prop)
            if prop == "realm" and hasattr(v, "realm_name"):
                e[prop] = v.realm_name
            # give a try to a json able object
            try:
                json.dumps(v)
                e[prop] = v
            except Exception, exp:
                logger.debug('%s', exp)
lst.append(e)
```

**Comment by david-guenault** [comment]
Thx gst for pointing the real problem in duplicate ;-)

```
diff --git a/shinken/daemons/arbiterdaemon.py b/shinken/daemons/arbiterdaemon.py
index f49f9dc..cc4ee8c 100644
--- a/shinken/daemons/arbiterdaemon.py
+++ b/shinken/daemons/arbiterdaemon.py
@@ -132,17 +132,21 @@ class IForArbiter(Interface):
                 cls = d.__class__
                 e = {}
                 ds = [cls.properties, cls.running_properties]
+
                 for _d in ds:
                     for prop in _d:
                         if hasattr(d, prop):
                             v = getattr(d, prop)
+                            if prop == "realm":
+                                if hasattr(v,"realm_name"):
+                                    e[prop] = v.realm_name
                             # give a try to a json able object
                             try:
                                 json.dumps(v)
                                 e[prop] = v
                             except Exception, exp:
                                 logger.debug('%s', exp)
-                    lst.append(e)
+                lst.append(e)
         return res
     get_all_states.doc = doc
```

**Comment by nlm** [comment]
I think this part of the code uses obscure variable names (e, v, d, _ds, d) and having more descriptive ones would really help debugging

**Comment by david-guenault** [comment]
First we fix then if we got spare time we can refactor but for now we must
fix before anything else

2015-01-12 10:44 GMT+01:00 Nicolas Limage <notifications@github.com>:
