### ISSUE TITLE
check_shinken : requires the Python Pyro module.Please install it

### ISSUE THREAD

**Issue by n-rodriguez** [naparuba/shinken#1464]
Hi!

I've updated Shinken to version 2.2 but still got this error when I try to check Shinken services with ```check_shinken.py``` :

```
CRITICAL : check_shinken requires the Python Pyro module.Please install it. (No module named pyro_wrapper)
```

I had to copy ```check_shinken.py``` by hand from https://github.com/shinken-monitoring/check_shinken.

Thank you.

**Comment by david-guenault** [comment]
I have made a rewrite of this plugin compatible with shinken api 2.2 (not 2.0.3). There are still some little bugs (but not on the plugin side) but you can give it a try. 

https://github.com/david-guenault/shinken-packs/tree/master/pack-arbiter2

The plugin is in the libexec folder.

**Comment by n-rodriguez** [comment]
Thanks for your answer. Actually this one works too https://github.com/shinken-monitoring/check_shinken but I thought it would be bundled with Shinken.
I've already had this issue 6 months ago (https://github.com/naparuba/shinken/issues/1235) with Shinken 2.0 and still got it with Shinken 2.2.
Anyway, it's working now :)

Thank you!

**Comment by Seb-Solon** [comment]
I removed it from master.
