### ISSUE TITLE
Feature: dynamically change daemons/loggers loglevel

### ISSUE THREAD

**Issue by gst** [naparuba/shinken#1466]
I've always found that being able to dynamically update the loggers loglevel would be a very good thing to have. 
It's very useful if you want to activate more debug/log output on some daemon(s) to verify some bad behavior or things like that, without having to restart completely the daemon(s) which could/would also completely reset their state and make it actually more difficult (if not impossible) to get what you wanted.

My idea :  Have a new function at the daemons interface level (Interface) with : 

```
def change_loggers_level( loggers_2_level ):
    ''' loggers_2_level is a dict-like with as keys a logger name (eventually None or '' for the "root" logger) and as value the new loglevel to be set '''
    for name, level in loggers_2_level.items():
        logging.getLogger(name).setLevel( level )
```

and voilà for the work at the daemons top level. 

After there is also the special case with subprocesses of the daemons, like Workers for pollers and so on.. 
But this can be still quite easily achieved by forwarding to them the new levels from the parent daemon process. Using their communication queue with a new message type for instance..

TBC..

**Comment by Seb-Solon** [comment]
Duplicated from #711  :)

**Comment by gst** [comment]
erf, my bad ;)
