### ISSUE TITLE
[Regression] Broken inheritance on services

### ISSUE THREAD

**Issue by t0xicCode** [naparuba/shinken#1472]
I have a bunch of service templates defined like so:

```
define service{
        name                            generic-service         ; The 'name' of this service template
        active_checks_enabled           1                       ; Active service checks are enabled
        passive_checks_enabled          1                               ; Passive service checks are enabled/accepted
        parallelize_check               1                       ; Active service checks should be parallelized (disabling this can lead to major performance problems)
        obsess_over_service             1                       ; We should obsess over this service (if necessary)
        check_freshness                 1                       ; Default is to NOT check service 'freshness'
        freshness_threshold             3600
        notifications_enabled           1                       ; Service notifications are enabled
        notification_interval           1440
        notification_period             workhours
        event_handler_enabled           0                       ; Service event handler is enabled
        flap_detection_enabled          1                       ; Flap detection is enabled
        failure_prediction_enabled      1                       ; Failure prediction is enabled
        process_perf_data               1                       ; Process performance data
        retain_status_information       1                       ; Retain status information across program restarts
        retain_nonstatus_information    1                       ; Retain non-status information across program restarts
        is_volatile                     0                       ; The service is not volatile
        check_period                    24x7                    ; The service can be checked at any time of the day
        max_check_attempts              3                       ; Re-check the service up to 3 times in order to determine its final (hard) state
        check_interval                  10                      ; Check the service every 10 minutes under normal conditions
        retry_interval                  2                       ; Re-check the service every two minutes until a hard state can be determined
        notification_options            w,u,c,r                 ; Send notifications about warning, unknown, critical, and recovery events
        contact_groups                  admins,users
        stalking_options                o,w,u,c
        register                        0                       ; DONT REGISTER THIS DEFINITION - ITS NOT A REAL SERVICE, JUST A TEMPLATE!
        }

define service{
        name                            critical-service
        use                             generic-service

        contact_groups                  critical

        max_check_attempts              3
        normal_check_interval           5
        retry_check_interval            2
        notification_interval           15

        # This is a template
        register                        0
}

define service{
        name                    ssh-critical-service
        use                     critical-service

        service_description     SSH
        check_command           check_ssh

        register                0
}

define service{
        use                     ssh-critical-service
        host_name               <hostname>
}
```

This worked fine under 2.0.3. However, trying to use the same configuration with 2.2 give me the following error:

```
[<timestamp>] ERROR: [Shinken] [service::<hostname>/SSH] a service has been defined without service_description in unknown
[<timestamp>] ERROR: [Shinken] [items] In SSH is incorrect ; from /etc/shinken/hosts/<hostname>.cfg:16
```

**Comment by Seb-Solon** [comment]
Ok I got the case. Actually the error is given way too early, before inheritance is applied. Service description / hostname is the unique key for a service. We made a bad asset on this one I think.

Ping @geektophe, maybe we should allow this behavior. It does not impact indexing template / host.

**Comment by t0xicCode** [comment]
After reading through the code and peppering it with debug statements, I've figured out that this happens because the `add_item` method in the `Services` class expects all services to have a **host_name** and a **service_description**. Unfortunately, in my case, only one of these is defined before inheritance is applied.

If you choose to allow this previously accepted behaviour, I see two ways of fixing this across the board:
 - apply inheritance on item creation, so inheritance is now done early in the process, to ensure that inherited properties are defined and set to the correct value. 
   
   There are two ways of accomplishing this:
    - The first is to examine items before they are created, and ensure that if they define a **uses**, the template has already been loaded or load it before resuming the original item creation. This would require the least amount of re-factoring (it can probably be implemented in the `create_objects_for_type` method).
    - The second involves a bigger re-factoring of the config system. It would involve creating a [DAG](http://en.wikipedia.org/wiki/Directed_acyclic_graph), specifying the relationship between various items (services could depend on their host, etc). This would require a more substantial amount of re-factoring, and potentially some normalization to the configuration (currently hosts and hostgroups can depend on each other, but there would need to be a single uni-directional relationship in a DAG), but the configuration would be more robust.
 - delay the addition to the item store until after inheritance has been applied.
   
   This may complicate the process, as there would be a need for a way to keep the item objects until they can be added to the store, which is what the store is supposed to be doing.

If, on the other hand, you choose to only allow the only the new behaviour, the documentation should be updated to reflect the fact that some of the required directives can be defined in an inherited template (such as, in this case, **check_command** or **check_interval**), while others (such as, in this case, **host_name** and **service_description**) must be defined in the child-most definition.

On a somewhat related node

**Comment by Seb-Solon** [comment]
The add item thing is done for indexing. This indexing is important for inheritance actually. I was design first for service / host explosion phase but I think it's also used for inheritance. 

I have to find time to fix the problem properly. For now you can just remove the test I think ;)

**Comment by k0ste** [comment]
Please fix inherit **service_description** to childs. Remove pain...

**Comment by Seb-Solon** [comment]
I've fixed it but I dont think I'll push it upstream right now as it's a big fix and we are going to release 2.4. Code has to be tested a bit more

**Comment by gst** [comment]
I am actually doing code review here.

but @t0xicCode : you deserve a big +1 for this investigation and the report you made.

**Comment by gst** [comment]
@Seb-Solon : 
little thing:
it's better to have the commit for the test case first, and then the fix after. So that you can checkout at the first commit, see that it fails, then checkout at the next commit (the one which fix) and see that it effectively fix the test case.

**Comment by Seb-Solon** [comment]
I prefer to always have a stable branch actually.

I usually checkout the new test file before to see it is broken :)

**Comment by Seb-Solon** [comment]
Commits merged.

**Comment by geektophe** [comment]
Hi guys, it seems the this did not fix the issue, as show in https://github.com/naparuba/shinken/issues/1695.

It should be fixed in https://githutb.com/naparuba/shinken/pull/1710 (the whole story is in the PR). Let's follow up in https://github.com/naparuba/shinken/issues/1695.
