### ISSUE TITLE
Service_excludes does not remove properly the service

### ISSUE THREAD

**Issue by Seb-Solon** [naparuba/shinken#1481]
The service is simply removed from services but we should ensure it is removed in other object.

For example if a service dependency is defined into a pack on the service we want to exclude the linkify function in service dependency will fail. 

Ping @gst  the issue will occur also with service_includes #1477

**Comment by gst** [comment]
if yes then damn..
but how did you spotted this possible issue ?

**Comment by Seb-Solon** [comment]
I used the mysql pack from shinken monitoring that has service dependencies on mysql connection service. I wanted to exclude a couple of not very useful for now and I got arbiter conf error.

I can give you log and everything tomorrow if you want.

**Comment by gst** [comment]
> I can give you log and everything tomorrow if you want.

will be helpful :)

**Comment by Seb-Solon** [comment]
Well, cannot reproduce upstream for now.

I'm pasting the configuration I got (more or less) 

```
define host{
name generic-mysql
register 0
}

define host{
name mysql
use generic-mysql
register 0
}

define service{
name mysql-service
use generic-service
register 0
aggregation mysql
}

define service{
service_description Mysql-connection
use mysql-service
register 0
host_name mysql
check_command _echo
}

define service{
service_description Mysql-bufferpool-hitrate
use mysql-service
register 0
host_name mysql
check_command _echo
service_dependencies ,Mysql-connection
aggregation mysql/cachehit
}

define service{
service_description Mysql-tablecache-hitrate
use mysql-service
register 0
host_name mysql
check_command _echo
service_dependencies ,Mysql-connection
aggregation mysql/cachehit
}

define host{
use mysql
host_name myalmostmysql
service_excludes Mysql-bufferpool-hitrate
}

```

**Comment by gst** [comment]
I could trigger some error with the test_servicedependency_complexes.py by adding some service_excludes and/or service_includes directives to some of the hosts.

I've done what I think would make it here.. I'll push to https://github.com/naparuba/shinken/pull/1480 as it's all linked.

**Comment by gst** [comment]
https://github.com/gst/shinken/commit/85d9c670162715b96a4b4d075b6746703e09398b
https://github.com/gst/shinken/commit/05285c80758f4b06425e981ecafe7e99543e2dbe

I'll have to double-check..
