### ISSUE TITLE
configuration error in scheduler-master.cfg

### ISSUE THREAD

**Issue by andyxning** [naparuba/shinken#1512]
the module name of retention-redis should be __RedisRetention__ if you install it with __shinken install__.

**Comment by Seb-Solon** [comment]
It is not up to dae on shinken.io. See https://github.com/shinken-monitoring/mod-retention-redis/blob/master/etc/modules/retention-redis.cfg

**Comment by andyxning** [comment]
@Seb-Solon ， however the one downloaded from shinken.io throgh `shinken install retention-redis` will still use **RedisRetention**, may be you should re upload the newer one to shinken.io.

**Comment by Seb-Solon** [comment]
Sorry, I cant because I'm not the first who updated this and I'm still not able to publish on all pack/module in shinken.io. @naparuba  could help on that.
