### ISSUE TITLE
log formmater  in log

### ISSUE THREAD

**Issue by andyxning** [naparuba/shinken#1513]
I think we should add each __human_timestamp_log__ to every daemon not just arbiterdaemon and schedulerdaemon. we should also make __naglog_result__ in log.py to accept a human readably time in its log not just a timestamp. It is very difficult to debug with timestamp. 

Time in below log item is very unreadable:
> [1423729784] ERROR: [Shinken] Ask actions to 0, got 5, [u'center0'], ['None']

I think we should only support time formatter like below:
> [%(asctime)s] %(levelname)s: %(message)s', '%a %b %d %H:%M:%S %Y'

not this one:
> [%(created)i] %(levelname)s: %(message)s

**Comment by gst** [comment]
+1

**Comment by andyxning** [comment]
I have make a PR about make the human readable timestamp log formatter the default and the only one. At the same time, i also change some test in order to make it work correctly. You can check it out in #1514

**Comment by Seb-Solon** [comment]
Sorry guys, it's about Nagios compatibility. 

This format is made for log parsing. Tools need a timestamp to get event and so does modules. We wanted to remove human timestamp because it was a pain.

I think it written somewhere is docs that the logging format is designed for further processing.

You can still use the human format btw

**Comment by andyxning** [comment]
if we can have the timestamp to follow the iso-8601 formatter, we can still
parse the timestamp easilly. Nothing more effort will be added, i think.



++++++
Ning Xie


2015-02-13 11:59 GMT+08:00 Sébastien Coavoux <notifications@github.com>:

**Comment by naparuba** [comment]
We should keep nagios format for nagios logs, lot of tools are using it for reporting and such thing. We can't break this compatibility.

It's up to the modules to get logs and reformat it if need :)

**Comment by Frescha** [comment]
> Am 13.02.2015 um 15:33 schrieb Gabès Jean <notifications@github.com>:
> 
> We should keep nagios format for nagios logs, lot of tools are using it for reporting and such thing. We can't break this compatibility.
> 
> It's up to the modules to get logs and reformat it if need :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/naparuba/shinken/issues/1513#issuecomment-74261867>.
> 
+1

**Comment by andyxning** [comment]
@naparuba , can you tell me one of the tools that using the timestamp log formmater, so i can check it out.
