### ISSUE TITLE
Initializing Pyro connection . Shinken 1.4

### ISSUE THREAD

**Issue by beetS76** [naparuba/shinken#1519]
Hello , 

I have an error when i try to start shinken on my server : 

[1424351872] Critical : I got an unrecoverable error. I have to exit
[1424351872] Critical : You can log a bug ticket at https://github.com/naparuba/shinken/issues/new to get help
[1424351872] Critical : Back trace of it: Traceback (most recent call last):
  File "/usr/local/shinken/shinken/daemons/brokerdaemon.py", line 661, in main
    self.do_daemon_init_and_start()
  File "/usr/local/shinken/shinken/daemon.py", line 479, in do_daemon_init_and_start
    self.setup_pyro_daemon()
  File "/usr/local/shinken/shinken/daemon.py", line 549, in setup_pyro_daemon
    self.pyro_daemon = pyro.ShinkenPyroDaemon(self.host, self.port, ssl_conf.use_ssl)
  File "/usr/local/shinken/shinken/pyro_wrapper.py", line 222, in __init__
    raise PortNotFree(msg)
PortNotFree: Error: Sorry, the port 7772 is not free: [Errno 48] Address already in use

I'm a begginer and do know how to resolvt it.

Have anyone an idea?

**Comment by Seb-Solon** [comment]
The error is kinda clear . You have something listening on the 7772 port. Maybe an old shinken daemon.

**Comment by beetS76** [comment]
Thats what im looking for bu when i do # netstat | grep 7772

Every PORT are marked as closed....

**Comment by Seb-Solon** [comment]
Hum, are you sure your netstat is listing lstening port by default?

The -l option gives you this, I personnaly always add a -pantu option (tcp / udp / all state / no resolution)

**Comment by beetS76** [comment]
ps  -ef | grep shinken doesn't return anything ....
netstat -l | grep 7772 return the same port as netstat | grep 7772 and no one is listening...

**Comment by Seb-Solon** [comment]
Do you have sufficient rights to do a full netstat ? To open a port? 

I'm pretty sure your issue is system related and not Shinken related. By the way, I suggest you not to use the 1.4 version of shinken.

**Comment by beetS76** [comment]
Which version do you suggest me ? i'm  logged as root ....

**Comment by Seb-Solon** [comment]
Well 2.2 should be fine. Shinken modules are mostly compatible . 

You are root but i guess shinken is not. I hope you wont have this when switching to the other version.

**Comment by beetS76** [comment]
I have no more PORT error but when i try to start shinken the 3 first line are :
 root@TFRNOR-AP100111:/root # /usr/local/etc/rc.d/shinken start
/usr/local/etc/rc.d/shinken: WARNING: cannot read shebang line from cd
./launch_all.sh: Command not found.
.................

and the last one one are : 

[1424359637] Info :    Trying to initialize additional groups for the daemon
[1424359637] Warning : Cannot call the additional groups setting with initgroups (Operation not permitted)
valid pidfile exists and not forced to replace.  Exiting.
/usr/local/etc/rc.d/shinken: WARNING: failed to start shinken
root@TFRNOR-AP100111:/root # valid pidfile exists and not forced to replace.  Exiting.
valid: Command not found.
root@TFRNOR-AP100111:/root # /usr/local/etc/rc.d/shinken: WARNING: failed to start shinken
/usr/local/etc/rc.d/shinken:: Too many arguments.
root@TFRNOR-AP100111:/root # root@TFRNOR-AP100111:/root # /usr/local/etc/rc.d/shinken start
root@TFRNOR-AP100111:/root: Command not found.
root@TFRNOR-AP100111:/root # /usr/local/etc/rc.d/shinken: WARNING: cannot read shebang line from cd
/usr/local/etc/rc.d/shinken:: Too many arguments.
root@TFRNOR-AP100111:/root # ./launch_all.sh: Command not found.

**Comment by Seb-Solon** [comment]
What distro are you using? Looks like the shebang is not fine, if you look at the script you may correct. 

There is also something else : the pidfile of shinken was not delete at shutdown (because it was not shutdown properly). You shuold remove it (/var/run/shinken/*). 

launch_all is for dev, how did you install it?

**Comment by beetS76** [comment]
I'm using FreeBSD 9.1-RELEASE (GENERIC)

Folder Shinken in /var/run doesn't exists...

Sorry but its not me that  have install shinken , i'm just trying to resolv this problem but i think i will contact technician who install it....

Thank you for your answer.
