### ISSUE TITLE
Feature request : ACL on displayed elements for an user

### ISSUE THREAD

**Issue by claneys** [naparuba/shinken#1521]
Hi,

It will be nice, if an user can view only elements that its contactgroup is assigned to.

What do you think ? I don't know what's the better solution, keep based on contact group or add an admin panel to the admin user that will configure acl for each user. First solution may be easier, already test to filter minemap view based on that that works well.

**Comment by naparuba** [comment]
You means on webui? This should be in the webui repo instead :)

**Comment by claneys** [comment]
Oh yeah, my mistake sorry ^^

**Comment by naparuba** [comment]
^^
