### ISSUE TITLE
Graphite module name conflicts with Graphite library and doesn't import

### ISSUE THREAD

**Issue by ktims** [naparuba/shinken#1523]
I have installed Shinken using pip, and have been trying to get the Graphite broker to work (installed with 'shinken install graphite'). Faced with errors in brokerd.log:
```
[1424718186] WARNING: [broker-master] Cannot load graphite as a package (No module named module), trying as module..
```
I did some digging. It appears that `modulesmanager.py` appends the configured module path to `sys.path`. However since I (necessarily) have Graphite installed as well, the 'graphite' package from actual Graphite appears first in the path. While `modulesmanager` does find the graphite module in the module path, Python attempts to import `.module` from the Graphite 'graphite' package instead of the Shinken one.

I'm not sure if the solution for the project is to rename the graphite broker back to 'graphite_perfdata' as it apparently used to be, or to fix the module loader to ensure sys.path only includes the configured module path for its loading.

**Comment by Seb-Solon** [comment]
Duplicated from shinken-monitoring/mod-graphite#7. Use the upstream version of shinken or rename the module type.
