### ISSUE TITLE
check_nrpe use python script with http request

### ISSUE THREAD

**Issue by RoCat** [naparuba/shinken#1528]
Hi,

I try to do the following:
MONITORING SERVER:
    nrpe_check!myCommand

MONITORED SERVER:
    myCommand: python /path/script.py

the python script: 
imports...
r = requests.get('http://<an url>')
print('test')

if i run the python script locally, even with nrpe user, it works and display 'test'
if i run the same remotelly using /usr/lib64/nagios/plugins/check_nrpe -H myHost -c myCommand
i have a NRPE: Unable to read output
and in logs in debug mode i have : 
Host is asking for command 'check_alerts' to be run...
Running command: python /opt/shinken/plugins/check_alerts.py
Command completed with return code 1 and output: <-- the output is empty

Is it a problem with check_nrpe that forbide me to send http requests ?

changed a bit to investigate:
i replaced the requests.get by a subprocess.call and a curl request.
Now the command works but the  behavior isn't the same locally and remotelly. I have code 0 as a return locally, and i have 7 remotelly. Like if the curl request is executed on the monitoring server and not on the monitored one...

**Comment by naparuba** [comment]
Hi,

what is the link with shinken? seems to be related to nrpe. Please open a ticket on the nrpe project instead :)
