### ISSUE TITLE
Problems with Macro Resolver since 2.2

### ISSUE THREAD

**Issue by 5c077yP** [naparuba/shinken#1534]
Hey I recently upgraded to shinken 2.2 and now some service macros are not resolved anymore. What I can see so far, it seems service macros are not inherited anymore.

The smallest config snippet would look like this:

```
# TEST HOST
define host {
  use                            my-host,generic-host ; usual generic-host
  host_name                      localhost
  address                        127.0.0.1
}

# ~~ pack definition

# HOST TEMPLATE
define host {
  name                            my-host
  register                        0
}

# SERVICE
define service {
  use                            my-service,generic-service ; usual generic-service
  service_description            CHECK-123
  host_name                      my-host
  check_command                  echo!$_SERVICEecho_command$
  # the check_command should be resolver to echo!OK | 'ok'=1" but it is not resolved at 
  register                       0
}

# SERVICE TEMPLATES
define service {
  name                            my-service
  _echo_command                   OK | 'ok'=1
  register                        0
}

```

This is just an example config that should show my use-case. It can see from the changelog that the macroresolver was fix from 2.0 => 2.2. I will try to look into the code and if I find something I will let you know, but maybe you already have an idea an can fix that simply before 2.4 final. 

Thanks in advance

**Comment by 5c077yP** [comment]
btw. this is the rest of my config (modules not included) if anyone wants to try

```
define host {
    name                            generic-host
    check_command                   echo
    check_period                    24x7
    contact_groups                  +admin
    register                        0
}

define service {
    name                            generic-service
    check_interval                  10
    retry_interval                  10
    check_period                    24x7
    contact_groups                  +admin
    register                        0
}

define command {
  command_name    echo
  command_line    /bin/echo '$ARG1$'
}

define timeperiod {
  timeperiod_name    24x7
  saturday           00:00-24:00
}

define contactgroup {
  contactgroup_name    admin
}

define contact {
  contact_name    me
  contactgroups   admin
}
```

**Comment by 5c077yP** [comment]
Hey, what i found out so far is:

- from 2.0 -> 2.2 `Items` was refactored to separate _items_ and _templates_  (into different dicts) from the beginning
- the `apply_inheritance` in `Items` as well as `Services` is __only__ called for the the _items_ but not _templates_ dict
- the `explode` step in arbeiterdaemon generates the items in my use-case (in 2.2)
- if I move `explode` before `apply_inheritance` (in arbeiterdaemon) it works, but i think this is __not__ the right way
- if you check the `linkify_templates` you can see that it is called against _templates_ and _items_ so i did with the `apply_inheritance` in `Services` and now it works
- i think this should also be done in the `Items` class

so this worked for me (in `./shinken/objects/service.py`)

```python
    # Apply inheritance for all properties
    def apply_inheritance(self, hosts):
        # We check for all Host properties if the host has it
        # if not, it check all host templates for a value
        for prop in Service.properties:
            self.apply_partial_inheritance(prop)

        # Then implicit inheritance
        # self.apply_implicit_inheritance(hosts)
        import itertools # TODO: move this to other imports on top
        for i in itertools.chain(self.items.itervalues(),
                             self.templates.itervalues()):
            i.get_customs_properties_by_inheritance()
```

I would like to send you a patch, but i cannot get the tests running so far. i called ./test/setup_test.sh and than in the test dir ./quick_tests.sh but they fail from the beginning without any changes made.

**Comment by Seb-Solon** [comment]
You need to install unitest2 etc.. 

We will be clearing some ticket today with @titilambert maybe this one is concerned as you made a big part :)

If you need some help to do it yourself you can come on IRC freenode #shinken, I'll be glad to help you :)

**Comment by Seb-Solon** [comment]
Done
