### ISSUE TITLE
bug in rc.d scripts for individual daemons

### ISSUE THREAD

**Issue by ryepup** [naparuba/shinken#1543]
I'm looking to run just the poller daemon on one of my machines, installing shinken via pip. The daemons don't come back up after reboot as I'd expect.

I have a symlink in `/etc/rc2.d/S20shinken-poller` pointing at `/etc/init.d/shinken-poller`.

When I restart the box, I get no poller, and no new log entries.

When I run it manually, I get an error:

```console
$ /etc/rc2.d/S20shinken-poller start
etc/rc2.d/S20shinken-poller: 56: /etc/rc2.d/S20shinken-poller: /etc/rc2.d/shinken: not found
```

The problem is the `shinken-poller` init script expects to be run in the same directory as the `shinken` init script. It works fine if I run the `shinken-poller` script directly:

```console
$ /etc/init.d/shinken-poller start
Starting poller: 
   ...done.
```

The expected behavior is that `/etc/rc2.d/S20shinken-poller start` is equivalent to `/etc/init.d/shinken-poller start`

**Comment by ryepup** [comment]
pull request coming shortly, this is an easy fix

**Comment by Seb-Solon** [comment]
Thanks!
