### ISSUE TITLE
The installation directory /var/lib/shinken/share is missing!

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1550]
Follow up of #1549 

```
# shinken install http
Grabbing : http
The installation directory /var/lib/shinken/share is missing!
```

I guess I'll go an submit this one to https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=shinken;dist=unstable

**Comment by Seb-Solon** [comment]
Fixed on debian side. We have to wait for the uploader to do the job. 

For now I suggest, if you really want update with a package, to use the 2.2 package we have done in deb.kaji-project.org/debian7 (this is a repo). Otherwise just create all missing dirs (share, doc, inventory)

**Comment by arthurlogilab** [comment]
Any plans for jessie packages ?

**Comment by Seb-Solon** [comment]
I dont get the question. I fixed the bug on the debian site : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781241 . I'll reply to the email so that everyone can see we are waiting for a new upload
