### ISSUE TITLE
setup.py is not installing on the good directories by default

### ISSUE THREAD

**Issue by naparuba** [naparuba/shinken#1555]
Hi,

the setup.py is installing under theses directories (python setup.p intall) by default:
  * debian (7) : /usr/local/etc /usr/local/var/lib   ...
  * centos (6): /usr/etc/* /usr/var/lib    ...

We should keep the old behavior that install by defualt on / if not in a virtual env or no --prefix/--root configured (for packaging)

I didn't find how to setup the config.install_dir on pbr (do not find it on pbr doc).

**Comment by titilambert** [comment]
Hello !
To install on debian:
```python setup.py install --prefix=   --install-layout=deb```
To install on centos:
```python setup.py install --prefix=```

**Comment by titilambert** [comment]
Or not ...
