### ISSUE TITLE
Stats sent to Statsd error : bad lines

### ISSUE THREAD

**Issue by mohierf** [naparuba/shinken#1560]
I configured my Shinken 2.2 to enable statistics and to send them to a running Statsd node with a Graphite backend but I do not see any metrics in my Whisper database.

Here are my Statsd logs ... where you can see that there is a space before the counter value ... syntax not accepted by Statsd ! 

``
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.poller-master.core.worker-fork.queue-size: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.poller-master.core.worker-fork.queue-size: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  1026,ms in msg "knm.shinken22.poller-master.core.wait-ratio: 1026|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  1026,ms in msg "knm.shinken22.poller-master.core.timeout: 1026|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.ping.args: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.ping.aqulock: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.ping.calling: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.ping.json: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.ping.global: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.get_checks.args: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.get_checks.aqulock: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.get_checks.calling: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.get_checks.json: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  0,ms in msg "knm.shinken22.scheduler-master.http.get_checks.global: 0|ms"
5 Apr 17:11:57 - DEBUG: Bad line:  2,ms in msg "knm.shinken22.poller-master.core.get-new-actions: 2|ms"
``

**Comment by naparuba** [comment]
You means should be :
knm.shinken22.scheduler-master.http.get_checks.global:0|ms

instead?

**Comment by mohierf** [comment]
Yes !

I fixed my problem with : 
``
            packet = '%s.%s.%s:%d|ms' % (self.statsd_prefix, self.name, k, v*1000)
``
instead of
``
            packet = '%s.%s.%s: %d|ms' % (self.statsd_prefix, self.name, k, v*1000)

``

No space character before %d ...

**Comment by naparuba** [comment]
arg, "works on my statsd" during my tests. I fix it thanks, will be ok for
2.4 :)


Jean
