### ISSUE TITLE
2.4RC1 : host.check_period should not be mandatory per nagios spec, but it is actually in Shinken

### ISSUE THREAD

**Issue by SLoeuillet** [naparuba/shinken#1568]
I had the following hineritance scheme :

template <= template <= real hosts

None of them defined "check_period"

In the end, I had this :

[1428503194] INFO: [Shinken] Checking hosts...
[1428503194] INFO: [Shinken] APP2568:GMLC01-adm@SrvLogiciel: check_period is not correct
[1428503194] ERROR: [Shinken] [items] In APP2568:GMLC01-adm@SrvLogiciel is incorrect ; from /etc/shinken/hosts/GMLC.hosts.cfg:1
[1428503194] INFO: [Shinken] APP2568:GMLC02-adm@SrvLogiciel: check_period is not correct
[1428503194] ERROR: [Shinken] [items] In APP2568:GMLC02-adm@SrvLogiciel is incorrect ; from /etc/shinken/hosts/GMLC.hosts.cfg:13
[1428503194] ERROR: [Shinken] 	hosts conf incorrect!!
[1428503194] INFO: [Shinken] 	Checked 3 hosts

So, at first, it sends an INFO saying "check_period" value is incorrect (in fact, it is missing)
Then, it sends an ERROR saying the host definition is incorrect but not why.

Missing check_period should then be an ERROR or get a default value somewhere else.
This configuration was working fine on an existing Nagios

**Comment by gst** [comment]
> Missing check_period should then be an ERROR or get a default value somewhere else.

I've also been beaten by that quite often.. IMO there should be a default for that parameter that should be correctly inherited for defined hosts or services that do not have that parameter explicitly configured.

can you provide an eventual fix ?

**Comment by naparuba** [comment]
indeed check_period is not mandatory. If unset means: 24x7. I give a test and a fix

**Comment by naparuba** [comment]
Cannot reproduce even with such an host:

define host{
       host_name        NOCHECKPERIOD

}



Please post a full test case for this.

**Comment by SLoeuillet** [comment]
I could reproduce it today with 2.4rc2

I'll provide a full test case tomorrow.

The problem could be in the double inheritence. Host -> host -> host...

**Comment by SLoeuillet** [comment]
Here it is :
http://pastebin.com/eNVXrzqD

**Comment by naparuba** [comment]
I can reproduce.

Note: don't paste un public ips and hostnames. :)

**Comment by Seb-Solon** [comment]
http://nagios.sourceforge.net/docs/nagioscore/3/en/objectdefinitions.html

host.check_period is mendatory regarding nagios doc

**Comment by naparuba** [comment]
Was mandatory in nagios, but we did choose to not manke it mandatory in shinken, as for exemple in service no check_period means "always valid".
