### ISSUE TITLE
2.4RC1 : shinken uses http_proxy ENV variable to talk to its daemons, even local ones

### ISSUE THREAD

**Issue by SLoeuillet** [naparuba/shinken#1569]
After first installing shinken, I had a big issue : no daemon could connect to the others.

I add all sorts of timeouts in the logs, saying it timed out after 3 secondes recieving 0 bytes.

After a long long time, I did figure that :+1: 
shinken uses pycurl, which uses curl, which uses whatever proxy is configured in the ENV of the user launching shinken.

I had this in my ENV :
http_proxy=http://10.153.151.4:8080
https_proxy=http://10.153.151.4:8080

No proxy configured inside /etc/shinken/
/etc/shinken/shinken.cfg:141:#http_proxy=
/etc/shinken/shinken_cli.ini:16:proxy =

In the end, I did modify /etc/init.d/shinken like this :
export TZ=:/etc/localtime
+export http_proxy=
+export https_proxy=

**Comment by naparuba** [comment]
thanks :)

I'll add it :)

**Comment by naparuba** [comment]
fixed by https://github.com/naparuba/shinken/commit/7965727c6ef2fc2b470b223e98298d4f7f97e75d

Thanks :)

![thanks 2](https://cloud.githubusercontent.com/assets/445325/7177517/956eee52-e427-11e4-9185-6043899ec5ac.gif)
