### ISSUE TITLE
unused CommandCall variable in linkify_one_command_with_commands()

### ISSUE THREAD

**Issue by gst** [naparuba/shinken#1571]
In the following code (part of Item class : https://github.com/naparuba/shinken/blob/master/shinken/objects/item.py#L638 )

```
# Link one command property to a class (for globals like oc*p_command)
def linkify_one_command_with_commands(self, commands, prop):
    if hasattr(self, prop):
        command = getattr(self, prop).strip()
        if command != '':
            if hasattr(self, 'poller_tag'):
### HERE :
                cmdCall = CommandCall(commands, command,
                                      poller_tag=self.poller_tag) 
            elif hasattr(self, 'reactionner_tag'):
### AND HERE :
                cmdCall = CommandCall(commands, command,
                                      reactionner_tag=self.reactionner_tag)   
            else:
                cmdCall = CommandCall(commands, command)
                setattr(self, prop, cmdCall)
        else:
            setattr(self, prop, None)
```

**HERE** + **AND HERE** : the `cmdCall` is unused after..
I guess it was an error because it's useless. 

The `setattr(self, prop, cmdCall)` should more than probably be 1 indentation level less..  shoud'nt it ?

wdyt ?

**Comment by naparuba** [comment]
definitvly yes

I add a test for such global ocmmand case with tag.

**Comment by naparuba** [comment]
![good job](https://cloud.githubusercontent.com/assets/445325/7177831/274a4072-e42a-11e4-9c67-6de2a4731606.gif)

**Comment by naparuba** [comment]
Fixed with https://github.com/naparuba/shinken/commit/3d69eb5286f4d8cdbadc1843a5ea36e212c6bd1f

was in fact working but it was more by chance. Now it's more explicit ^^
