### ISSUE TITLE
Problem with multiple active brokers for one scheduler

### ISSUE THREAD

**Issue by andyxning** [naparuba/shinken#1572]
I have a problem about why we limit the active broker number of each scheduler with **one**. That is to say that we can not have two active brokers at the same time.

What is the main reason for this.

**Comment by naparuba** [comment]
It's because of a bad configuration of your realms (multi broker links). I close the ticket :)

Feel fre to reopen if your configuration is valid and still not working :)

**Comment by andyxning** [comment]
What i mean is that why we should only configure one broker with each scheduler/poller/broker/receiver. I  don't mean one specific configuration. I mean the generic one. as the [doc said](http://shinken.readthedocs.org/en/latest/07_advanced/scaling-shinken.html?highlight=broker#scaling-the-broker).

**Comment by naparuba** [comment]
Because you must choose between broker scalability (divide load betweend
brokers) and same brokers wuth with different modules or levels (realms).
You cannot have both. That's all. That's why it's limited by default to one
(so you can scale brokers) and if you want more it's the "same" data that
brokers will have. But o you can choose when you are creating your
architecture ^^

**Comment by andyxning** [comment]
However, as the code will show that:

1   for scheduler, we can only have [some initial broks put to the broker
which connect to this scheduler first](
https://github.com/naparuba/shinken/blob/master/shinken/scheduler.py#L292)

2 for receiver/reactionner/poller, they will finally both put the broks to
one broker and after that all these three satellite will clear the broks.
[here is the code](
https://github.com/naparuba/shinken/blob/c6c354fb589959afb9e1da3ed28bbe2f9396a84a/shinken/satellite.py#L552
)

to conclusion, i think we should recommend that **we can not get more than
one active Broker for deployment** not for scheduler only.



++++++
Ning Xie


2015-04-16 19:24 GMT+08:00 Gabès Jean <notifications@github.com>:
