### ISSUE TITLE
2.4RC2 : only part of my hosts are visible in mklivestatus output

### ISSUE THREAD

**Issue by SLoeuillet** [naparuba/shinken#1578]
In my arbiter log, I see 636 hosts registered :
[1429620153] INFO: [Shinken] Checking hosts...
[1429620153] INFO: [Shinken] 	Checked 636 hosts

[1429620153] INFO: [Shinken] Number of hosts in the realm All: 636 (distributed in 462 linked packs)
[1429620153] INFO: [Shinken] Total number of hosts : 636

In thruk (and in raw mklivestatus output from a unix socket), I only have 414 hosts.

echo "GET hosts" | unixcat /var/run/shinken/live  > ~/hosts
wc -l ~/hosts
415 /root/hosts

Is there a limit on the number of hosts exposed via mklivestatus ??

**Comment by SLoeuillet** [comment]
Additional information : between 2 shinken restarts, I always have 414 hosts listed but ... not the same subset/servers...

Full /etc/shinken available on request.

System used : ubuntu 14.04.2 fully updated

**Comment by SLoeuillet** [comment]
2847 services visible in livestatus but 3588 in arbiter log

**Comment by Seb-Solon** [comment]
I suggest you to reduce your conf to find what it is missing so that you can provide us a minimal config to reproduce.

**Comment by naparuba** [comment]
it's related to livestatus I think. Please open to the livestatus repo
instead of the framework one :)

(https://github.com/shinken-monitoring/mod-livestatus)

Thanks.

**Comment by SLoeuillet** [comment]
Ok, found that actually, it's not a livestatus problem but a problem in CORE, related to shinken hosts not responding.

I had 4 hosts configured : prasvadm19, prasvadm20, prcsvadm19, prcsvadm20
All hosts are up. **But shinken was only running on prasvadm19**.

prasvadm19 : arbiter master, broker master, scheduler/poller/reciever/reactionner active
prcsvadm19 : arbiter spare, broker spare, scheduler/poller/reciever/reactionner active
prasvadm20 : scheduler/poller/reciever spare
prcsvadm20 : scheduler/poller/reciever spare

With the very same hosts/hostgroups/services/servicegroups, I have :
 28 hosts / 125 services when I remove the dead shinken hosts from the configuration
 24 hosts / 112 services when I let the 4 shinken hosts configuration in /etc/shinken/arbiter|broker|scheduler|reciever|poller|reactioner)

Now trying to narrow down which piece of not responding shinken host could lead to missing hosts/services from the livestatus view

**Comment by david-guenault** [comment]
do you use poller tags ? if so then any host tagged on dead pollers will
not appear at all (i think)



2015-04-23 10:35 GMT+02:00 Stéphane Loeuillet <notifications@github.com>:

**Comment by SLoeuillet** [comment]
Neither poller_tag nor realm_tag

All my hosts are in realm "All"

**Comment by naparuba** [comment]
just a question: how many active schedulers are running, and how many are
defined?

**Comment by naparuba** [comment]
(I postpone as seems to be a bad architecture configuration/design).

**Comment by SLoeuillet** [comment]
4 schelulers were defined. 2 active/2 spare.
Only one running. (Active)
 Le 23 avr. 2015 11:20 AM, "Gabès Jean" <notifications@github.com> a écrit :

(I postpone as seems to be a bad architecture configuration/design).

—
Reply to this email directly or view it on GitHub
<https://github.com/naparuba/shinken/issues/1578#issuecomment-95506347>.

**Comment by SLoeuillet** [comment]
Test case :

https://www.loeuillet.net/code/shinken/issue/1578/etc_shinken_20150423-standalone_and_working.tar.bz2
636 / 3588

https://www.loeuillet.net/code/shinken/issue/1578/etc_shinken_20150423-cluster_missing_hosts_and_services.tar.bz2
414 / 2838

**Comment by SLoeuillet** [comment]
Setting 3 schedulers as spares (spare=1) make my hosts/services come back.
Does it mean i'm limited to 1 active scheduler ? or one per realm ?

**Comment by naparuba** [comment]
you define 2 active but only one daemon was running in the 4. By design it
will fail yes.

**Comment by naparuba** [comment]
Definitivly bad architecture design problem, not a bug.

**Comment by SLoeuillet** [comment]
Ok, so if one of the active scheduler is DEAD, it would not redispatch its
resources to other active scheduler which are alive, right ?

Could I have 1 active/1 spare for a realm and 1 active/1 spare for another
realm ?

2015-04-24 8:38 GMT+02:00 Gabès Jean <notifications@github.com>:

**Comment by naparuba** [comment]
This is not a place for support, such questions should be in the forum, this place is for bug. But as it's quick: it's like raid, no spare, no fail allowed :)
