### ISSUE TITLE
Feature request : enable/disable macros by module

### ISSUE THREAD

**Issue by SLoeuillet** [naparuba/shinken#1580]
In main /etc/shinken/shinken.cfg file, I've got this :
# Disabling env macros is good for performances. If you really need it, enable it.
enable_environment_macros=0

I need them for reactioner (for notification script) but don't want to kill performance on poller which calls every checks and so forks a lot of shells

Could this macro be moved to every module/daemon so that it could be enabled for one and not for another ?

**Comment by naparuba** [comment]
Already avaialbe on commands :)

**Comment by SLoeuillet** [comment]
Ok, so I let this enable_environment_macros=0 in the main shinken.cfg file but I can set it to 1 inside a "define command" block or inside a "define service" block ?

I don't see a reference to this in the docs, but only in the source :
http://shinken.readthedocs.org/en/latest/_modules/shinken/commandcall.html

I did search for that in google : site:shinken.readthedocs.org enable_environment_macros

**Comment by naparuba** [comment]
doc not up to date, patch accepted :)

**Comment by SLoeuillet** [comment]
Ok.
I'll first try to find this bug root cause (https://github.com/shinken-monitoring/mod-livestatus/issues/57) then I'll make you patches
