### ISSUE TITLE
[Shinken 2.2] servicegroup parsing issue

### ISSUE THREAD

**Issue by dlgood23** [naparuba/shinken#1582]
In Shinken 2.2, if I have a service defined with a servicegroup beginning with a '+', it should add that group to whatever was inherited from its template.  Instead, I end up with only the servicegroup in the definition with it's name beginning with a literal '+'.  For example:

define service {
        use                     check-http-ecv
        service_description     Prism ECV Port 80
        host_name               prism.example.com
        servicegroups           +prism-ecv
}

And here's the check-http-ecv template:

define service {
        use                     standard-service
        name                    check-http-ecv
        check_command           check-http-args!
        servicegroups           ecv-all
        register                0
}

Once loaded, the 'Prism ECV Port 80' service ends up being a member only of the servicegroup '+prism-ecv'

**Comment by Seb-Solon** [comment]
If you guyz agree with that then servicegroups should be a List properties instead of a String property.

Only list can have a + actually. 

I can fix that if you agree @naparuba @gst etc...

**Comment by dlgood23** [comment]
It does the right thing in Nagios -- we've being doing it this way for years.  Plus I think it was working that way in 2.0.

**Comment by gst** [comment]
If it was working in 2.0 then it s a regression  and I guess it could be because  that property wasn t changed to a "ListProperty" one.
So yes for me ;)

**Comment by naparuba** [comment]
go for fix, as it's a regression.

Please up when it's pushed so I can tag the RC4 so ^^

**Comment by Seb-Solon** [comment]
Fixed
