### ISSUE TITLE
[debian] #782587 shinken: scheduler fails to start on reboot

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1599]
shinken fails to restart on reboot. scheduler fails to start because of stale pid file. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782587

**Comment by arthurlogilab** [comment]
scheduler fails to stop when using "service shinken stop"

**Comment by naparuba** [comment]
Debian package related, not upstream sorry.
