### ISSUE TITLE
Downtime  Not appearing in webui, i can see in log

### ISSUE THREAD

**Issue by tarak666** [naparuba/shinken#1602]
Hi,
We have shinken2.2 installed using pip, everything working fine for me, but only downtime is not working.
When i add downtime it showing in log, but not showing on webui or commant box.

Shinken Version:- shinken 2.2
EXTERNAL COMMAND: [142912347187] SCHEDULE_SVC_DOWNTIME;localhost;Check Memory Usage;142345340;142345540;1;0;0;tarak;sdsad

Can any one help me to fix this issue

Thanks in advance.

**Comment by naparuba** [comment]
Is it still occuring? even by setting by webui?

**Comment by mohierf** [comment]
Which versions: Shinken and WebUI ?
