### ISSUE TITLE
self.tags error in regenerator is wrong

### ISSUE THREAD

**Issue by andyxning** [naparuba/shinken#1612]
it seems that the root reason is that the regenerator module has something wrong. Currently, i can tell that when we reload configuration, then the `self.tags` in `Regenerator` is wrong. It does not have anything to clean all previous tags count instead just adding.

            # Linkify tags
            for t in h.tags:
                if t not in self.tags:
                    self.tags[t] = 0
                self.tags[t] += 1
this will cause all the tags count number increase every time we reload the configuration.

This will also make WebUI to present some error info. 
and some related issues #1597

**Comment by andyxning** [comment]
I think i can give a method to fix this bug. see PR #1616

**Comment by naparuba** [comment]
was merged if I'm not wrong, I fix here.
