### ISSUE TITLE
How to develop a special email notification for a service?

### ISSUE THREAD

**Issue by Peter-YAN** [naparuba/shinken#1619]
Hi,
I want to use Shinken monitoring a service.
If the service is down, a custom email is send.
please note, i hope the email is not the general email which is defined in "contact:notificationways".
I hope the custom email is just response to the service.
The email should has a custom format, such as highlight text, use table form; attachment is also want to used in the email.

I found "zabbix" can define action for a service, 
The action can be used to run external script to meet the requirement.

Could you tell how to implement it in Shinken?

**Comment by Peter-YAN** [comment]
OH, yes, i could use event handler for the service. is it right?

**Comment by mohierf** [comment]
Event handler is to manage service status change. It is a script executed when a service goes from Ok to bad state ...

I understand that you want to be able to send and HTML email ? You should copy a mailer script in your Shinken libexec directory and declare this script as a notification command in your configuration ...

**Comment by Peter-YAN** [comment]
Hi mohierf, 
the notification command is general command, which can not bind to a specific service, it is bind to a contact.

I hope to develop a plugin to monitor my application, then send a HTML email when the condition is meet.

**Comment by Frescha** [comment]
http://nagios.fm4dd.com/howto/nagios-flexible-notifications.htm

**Comment by claneys** [comment]
There is an issue already open #1178 . 

I use it to customize notifications for each services with 3 services's macros. Does will it fit your needs ?

**Comment by olivierHa** [comment]
Peter-Yan, is it ok for you?

**Comment by naparuba** [comment]
no news, I close.
