### ISSUE TITLE
Any plan to Integration with Cloudstack

### ISSUE THREAD

**Issue by sjkeerthi** [naparuba/shinken#1621]
Integration with Shinken Monitoring Is there any plan to integrate it with  CloudStack via plugins will be a great addition and besides simple monitoring.

**Comment by hvad** [comment]
Hi,

Need to developpe plugin for cloudstak or use https://github.com/heince/nagios-cloudstack. But it's not shinken project to do this. 

Best regards

**Comment by naparuba** [comment]
yes, that's out of scope with the shinekn framework, that's mainly plugins or even a module. But not the core framework :)
