### ISSUE TITLE
Loosing pid files every time I reboot the server

### ISSUE THREAD

**Issue by issad** [naparuba/shinken#1622]
Hi,
The /var/run/shinken directory is almost empty (There remains only the arbiter.pid file) every time the server reboots without being created afterwards.

**Comment by naparuba** [comment]
sorry but I don't understand the problem. What is the point with being empty by a reboot?

**Comment by issad** [comment]
When I cant't start the shinken service after a reboot but when I installed the previous version of shinken(2.2), it was fixed.

**Comment by halysan** [comment]
Hi, 
I have the same problem, 
I have update 2.2 to 2.4.
Every boot, my /var/run/shinken have the rights root:root, so the files .pid are not created
I have to change the rights shinken:shinken every boot
Then the files .pid are created with: /etc/init.d/shinken start

But every boot always the same...

**Comment by hvad** [comment]
hi,

in your init script you need something like this :
pre-start script
mkdir -p -m0755 /var/run/shinken
chown shinken:shinken /var/run/shinken
end script

best regard

or use deb or rpm ;-)

2015-05-18 16:17 GMT+02:00 halysan <notifications@github.com>:

> Hi,
> I have the same problem,
> I have update 2.2 to 2.4.
> Every boot, my /var/run/shinken have the rights root:root, so the files
> .pid are not created
> I have to change the rights shinken:shinken every boot
> Then the files .pid are created with: /etc/init.d/shinken start
>
> But every boot always the same...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/naparuba/shinken/issues/1622#issuecomment-103074253>.
>



-- 
David Hannequin

**Comment by naparuba** [comment]
fixed by https://github.com/naparuba/shinken/commit/ac2b318624e3cd6c76e1f726d7109fb31453d626
