### ISSUE TITLE
Shinken Debian service startup

### ISSUE THREAD

**Issue by mohierf** [naparuba/shinken#1624]
After a fresh install with pip, Shinken does not start as a service on a Debian Jessie with default configuration ...

 Only the arbiter daemon is started because the other daemons are not allowed to write their PID file in the /var/run/shinken directory ...

 I need to *chmod 777 /var/run/shinken* to have all daemons started correctly !

 After reboot, same problem ... because the /var/run/shinken is reset as *755 root/root* ... as of it the default user shinken/shinken is not allowed to write in this directory !

 In the */etc/init.d/shinken* script: 
```
# If var or run dir is missing, create them and chown them
[ ! -d $VAR ] && mkdir -p $VAR && chown $SHINKENUSER:$SHINKENGROUP $VAR
[ ! -d $RUN ] && mkdir -p $RUN && chown $SHINKENUSER:$SHINKENGROUP $RUN
```
but ii seems that it not executed !

```
root@shinken24:~# /etc/init.d/shinken start
Starting scheduler:
FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/schedulerd.pid' (full output is in /tmp/bad_start_for_scheduler) failed!
Starting poller:
FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/pollerd.pid' (full output is in /tmp/bad_start_for_poller) failed!
Starting reactionner:
FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/reactionnerd.pid' (full output is in /tmp/bad_start_for_reactionner) failed!
Starting broker:
FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/brokerd.pid' (full output is in /tmp/bad_start_for_broker) failed!
Starting receiver:
FAILED: shinken.daemon.InvalidPidFile: [Errno 13] Permission denied: '/var/run/shinken/receiverd.pid' (full output is in /tmp/bad_start_for_receiver) failed!
Starting arbiter:
. ok
```

**Comment by mohierf** [comment]
Relation with #1622 ?

**Comment by halysan** [comment]
I have the same problem with Debian 7 Wheezy

**Comment by hvad** [comment]
Hi,

Add line on your start function (you can see init SysV script on github in
directory for_fedora/init.d :

start() {



directory=$(dirname $pidfile)



 [ ! -d $directory ] && mkdir -p $directory

 chown $user:$group $directory



2015-05-18 16:23 GMT+02:00 halysan <notifications@github.com>:

> I have the same problem with Debian 7 Wheezy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/naparuba/shinken/issues/1624#issuecomment-103077052>.
>



-- 
David Hannequin

**Comment by gregmurf** [comment]
Hi,
i'm beginner in linux and shinken.
I have the same problem. Where do i add this code ? On /etc/init.d/shinken ?
Thx

**Comment by maethor** [comment]
Hello,

On Jessie, I have exactly the same problem with `/run/shinken`.

Thanks.

**Comment by hvad** [comment]
Hi,

You can see
https://github.com/naparuba/shinken/blob/master/for_fedora/init.d/shinken-arbiter
or use systemd on Jessie (
https://github.com/naparuba/shinken/blob/master/for_fedora/systemd/shinken-arbiter.service
).

Best regard

2015-05-26 7:26 GMT+02:00 Guillaume Subiron <notifications@github.com>:

> Hello,
>
> On Jessie, I have exactly the same problem with /run/shinken.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/naparuba/shinken/issues/1624#issuecomment-105397301>.
>



-- 
David Hannequin

**Comment by maethor** [comment]
Systemd service doesn't solve the problem because it doesn't even create `/var/run/shinken` and `/run/shinken`. I have add the following to make them work:

```
ExecStartPre=/bin/mkdir -p /run/shinken
ExecStartPre=/bin/chown shinken:shinken /run/shinken
ExecStartPre=/bin/mkdir -p /var/run/shinken
ExecStartPre=/bin/chown shinken:shinken /var/run/shinken
```

But this is not a solution, because paths, user and group are now hardcoded.

**Comment by naparuba** [comment]
A valid way is with the default file, but as it's limited to the user that are using the init.d and linux.

I look at more code level solution like create and chown the directory is need

**Comment by naparuba** [comment]
fixed by https://github.com/naparuba/shinken/commit/ac2b318624e3cd6c76e1f726d7109fb31453d626
