### ISSUE TITLE
Shinken 2.4 - receiver log_level not working

### ISSUE THREAD

**Issue by Corbyn** [naparuba/shinken#1625]
Since update to Shinken 2.4 the receiver log grows excessive because of NSCA INFO log records.
Like: "[1431436592] INFO: [receiver-master] [NSCA] packet: version 3, pad: 8242, crc32: 2036878354, host/service: ..."
The problem is, these records are logged regardless of what the daemon log_level is set to!
We had about 250.000 of these entries in one day resulting in > 200 MB receiverd.log (with log_level=ERROR in receiverd.ini)

It would be nice to have a quick workaround because It seems to me this also has impact on Shinken performance.

Best regards,
Andy

**Comment by mohierf** [comment]
You are right ... the workaround is in the nsca_module that was published with a wrong log level set to INFO for these logs ... it is my fault ... sorry !

The rapid workaround is that you change the `logger.info`to `logger.debug`, line 171 in the module.py of nsca module !

**Comment by Corbyn** [comment]
I successfully implemented the workaround. After a restart of the shinken-receiver no more nsca INFO records are logged.
Tanks for the quick response!

**Comment by mohierf** [comment]
You are welcome.

Issue may be closed.
