### ISSUE TITLE
Cannot find python lib crypto ?

### ISSUE THREAD

**Issue by algorys** [naparuba/shinken#1628]
Hello,

I have install Shinken via pip and when I want to install some module or use some shinken commands I have the following error : 

ERROR: [Shinken] Cannot find python lib crypto: export to kernel.shinken.io isnot available

Is there something to do to remove this ? I've install this lib : 

pip install crypto

But it seems have no effects.

Thank you for your help.

**Comment by algorys** [comment]
Nobody has an idea please ?

**Comment by olivierHa** [comment]
1- Installing lib crypto should work. Are you using the same version of
python ?

2- And this is a error for the statsd feature, it shouldn't affect shinken
at all.

Is this message preventing you from using the cli commands ?


2015-05-18 16:06 GMT+02:00 Mestra <notifications@github.com>:

**Comment by k0ste** [comment]
On CentOS 7 install python2-crypto, m2crypto, that's resolve this problem.

**Comment by algorys** [comment]
1- It's install for 2.7 version of python (for all version in fact)

2- It seems not but I have this bug on the monitoring plugin in GLPI https://github.com/ddurieux/glpi_monitoring/issues/170 and I don't know if there is a link beetween this 2 issues.

...

I have not this issues in Shinken 2.2 before.

**Comment by algorys** [comment]
@k0ste I'm under Debian... I install m2crypto but seems not solve it. There is no package python2-crypto on Debian.... :(

**Comment by olivierHa** [comment]
python-crypto ?

2015-05-18 16:25 GMT+02:00 Mestra <notifications@github.com>:

**Comment by algorys** [comment]
yes python-crypto works and solve it :)
