### ISSUE TITLE
Livestatus mapping issue

### ISSUE THREAD

**Issue by floppy84** [naparuba/shinken#1630]
Hi all,

I got an issue on 2.4 shinken and thruk.

the $Key$ value passed in argument work well in shinken web ui 

But in thruk i got the service name display like this : Slave SQL running port-$KEY$
 in spite of SQL running port-3306

In cat /tmp/shinken_checkconfig_result log i got issue with livestatus mapping ::

/var/lib/shinken/modules/livestatus/mapping.py:45: DeprecationWarning: shinken.schedulerlink is deprecated module path ; schedulerlink must now be imported from shinken.objects.schedulerlink ; please update your code accordingly
  from shinken.schedulerlink import SchedulerLink
/var/lib/shinken/modules/livestatus/mapping.py:46: DeprecationWarning: shinken.reactionnerlink is deprecated module path ; reactionnerlink must now be imported from shinken.objects.reactionnerlink ; please update your code accordingly
  from shinken.reactionnerlink import ReactionnerLink
/var/lib/shinken/modules/livestatus/mapping.py:47: DeprecationWarning: shinken.brokerlink is deprecated module path ; brokerlink must now be imported from shinken.objects.brokerlink ; please update your code accordingly
  from shinken.brokerlink import BrokerLink
/var/lib/shinken/modules/livestatus/mapping.py:48: DeprecationWarning: shinken.receiverlink is deprecated module path ; receiverlink must now be imported from shinken.objects.receiverlink ; please update your code accordingly
  from shinken.receiverlink import ReceiverLink
/var/lib/shinken/modules/livestatus/mapping.py:49: DeprecationWarning: shinken.pollerlink is deprecated module path ; pollerlink must now be imported from shinken.objects.pollerlink ; please update your code accordingly
  from shinken.pollerlink import PollerLink

I supose that the problem come from this.
Any idea ?

![image](https://cloud.githubusercontent.com/assets/3499449/7613125/1be020d8-f98f-11e4-83e6-0fd0e4e4d7e2.png)

![image](https://cloud.githubusercontent.com/assets/3499449/7613148/466e5bbc-f98f-11e4-8494-539b8ddf11f9.png)

whereas in shinken webui all work fine ::

![image](https://cloud.githubusercontent.com/assets/3499449/7613176/7192ddf4-f98f-11e4-896c-ef569de8df34.png)

**Comment by gst** [comment]
> In cat /tmp/shinken_checkconfig_result log i got issue with livestatus mapping ::

s/got issue/got warnings/   (DeprecationWarning more precisely)  ;)

> I supose that the problem come from this.

so nope ;)

**Comment by floppy84** [comment]
I changed in mapping.py 

shinken.schedulerlink by shinken.objects.schedulerlink and i did the same for other modules.
But i still have issue in thruk ui.

**Comment by floppy84** [comment]
Hi gst could you say me if this is a bug that you can reproduce or if i am the only one to have this bug ?
And how can i fix it ?

**Comment by oliiivier** [comment]
I have same bug with thruk 1.88-4 and shinken 2.4, have you some patch we could apply to fix this issue?

**Comment by k0ste** [comment]
Have some bug https://github.com/naparuba/shinken/issues/1635

**Comment by olivierHa** [comment]
See #1635

You can temporary fix this by editing the livestatus mapping file , just 1
word to change and it should be fine.


2015-05-21 10:18 GMT+02:00 oliiivier <notifications@github.com>:

**Comment by oliiivier** [comment]
perfect, it was what i'm looking for, thanks ;)

**Comment by olivierHa** [comment]
https://github.com/naparuba/shinken/commit/0cfcc2adcb6f5be0fa351def9f59881bfe2cdbe5

This should fix this issue.
