### ISSUE TITLE
[Shinken 2.4] Big problems with service_description

### ISSUE THREAD

**Issue by k0ste** [naparuba/shinken#1635]
I updated 2.2 to 2.4, try test https://github.com/naparuba/shinken/issues/1472

1.When use duplicate_foreach:

![selection_004](https://cloud.githubusercontent.com/assets/7759548/7694827/597547f6-fdff-11e4-8134-545150269d09.jpg)

How it look at 2.2 (old screenshot, but 'Service' is the point):

![selection_004](https://cloud.githubusercontent.com/assets/7759548/7178465/7994f322-e448-11e4-8cc1-1f1d2ac49881.jpg)

2.Service_description not inherit from templates. If make something like this:

```
define service {
register 0
name test
service_description TEST-DESC
check_command check_host_alive
}
define service {
use test
host_name router
}
```

Check config, no any exception
```
shinken-arbiter -v -c /etc/shinken/shinken.cfg | grep Checked | grep services
[1432006287] INFO: [Shinken] 	Checked 89 services
```

If like this:
```
define service {
register 0
name test
service_description TEST-DESC
check_command check_host_alive
}
define service {
use test
host_name router
service_description SUPERTEST-DESC
}
```

```
shinken-arbiter -v -c /etc/shinken/shinken.cfg | grep Checked | grep services
[1432006274] INFO: [Shinken] 	Checked 90 services
```

Need test?

**Comment by olivierHa** [comment]
Hello,

About duplicate_foreach and service_description, it is "just" a display
issue. Thruk is querying "display_name" to get "service_description" (it
seems legit :)) MK Multisite doestn't use this field (like Nagios cgi I
would say)
So don't worry, it doesn't affect the scheduling system at all.

If you want a quick dirty hack to fix that, just edit the livestatus
mapping (/var/lib/shinken/modules/livestatus/mapping.py) ,  and change the
display_name mapping to query the service_description instead

 845         'display_name': {
 846             'description': 'An optional display name (not used by
Nagios standard web pages)',
 847             'function': lambda item, req: item.service_description,
 848         },

The real "fix" will come later.

Olivier

2015-05-19 5:35 GMT+02:00 Konstantin Shalygin <notifications@github.com>:

**Comment by k0ste** [comment]
olivierHa, problem in Thruk? I downgraded to 1.88-2 - the same.

**Comment by olivierHa** [comment]
I didn't say it was a thruk issue. I said Thruk and Multisite are doing
different queries.
Did you try to edit the mapping file ?


2015-05-21 7:41 GMT+02:00 Konstantin Shalygin <notifications@github.com>:

**Comment by k0ste** [comment]
olivierHa, is described here https://github.com/naparuba/shinken/issues/1630
I uderstand you.

**Comment by olivierHa** [comment]
OK, for the 1st issue, https://github.com/naparuba/shinken/commit/0cfcc2adcb6f5be0fa351def9f59881bfe2cdbe5 should fix it.

Will try to see the 2nd one

**Comment by k0ste** [comment]
Thanks for patch, works perfect.

**Comment by k0ste** [comment]
https://github.com/naparuba/shinken/issues/1638
