### ISSUE TITLE
Solution for "access denied" with pid problem (debian 7/8)

### ISSUE THREAD

**Issue by motsan** [naparuba/shinken#1639]
Hy, everybody.
At first, sorry for my language, im french.... :)

there is some issues related to debian "pid error access denied (13)".
After some research :
1- It seems that in recent debian and ubuntu release, "/var/run" is tmpfs... so, this folder is "reset" to default at each boot.
2- When processing /etc/init.d/shinken script, it seems that $SHINKENUSER and $SHINKENGROUP are not set. That's why we have problem.
3- Changing by "hard value" (eg shinken:shinken) solve the problem.

finally, the solution said before solve the problem, but it s a workarround !
which solution to avoid this workarround ??? I dont know... I'm new in "supervision software" and python scripting

Best regards

Motsan

**Comment by halysan** [comment]
Hi,

There are lot of topics on the question..
#1622 
#1624 
The only solution to my knowledge is changed the hard value.

Halysan

**Comment by motsan** [comment]
Hi,

yes, at this time, this is the only solution.
I have opened this issue to inform the community from my search, and may avoid a lot of issues for this subject, and users find rapidely a solution.

I believe the dev team reads my issue to find a better and generic solution for this issue to the next version of shinken.

Best regards

Motsan
