### ISSUE TITLE
IMPROVE : alert of some plugins doesn't triggers notifications

### ISSUE THREAD

**Issue by algorys** [naparuba/shinken#1642]
Hello,

I've noticed that some commands who changes to WARNING or CRITICAL doesn't triggers notifications. I'm not sure that's part of monitoring plugin or Shinken issue...

--> Here is some example :

SERVICE ALERT: routeur;currentconnections;CRITICAL;HARD;3;SNMP CRITICAL - 1098

Corresponding command :

./check_snmp -H $HOSTADDRESS$ -c public -o .1.3.6.1.4.1.8741.1.3.1.2.0 -w 800 -c 1000

--> Another example :

SERVICE ALERT: esx2;esx_net_receive;OK;SOFT;2;CHECK_VMWARE_API.PL OK - net receive=123.00 KBps

Corresponding command :

./check_vmware_api.pl -D $HOSTADDRESS$ -f auth.cfg -l vmfs -w 80% -c 90% -s BDD01 -o used

Is there some bug in monitoring plugins ?

Or the command doesn't works for notifications ?

Or it's due to Shinken ?

I must clarify that I receive another notifications from GLPI for another commands. Certains command send me notifications for some hosts and not for other. yet it is the exactly same command...

Does I missed something ?

Thanks for help.

GLPI 0.85.4
Monitoring 0.85.1
Shinken 2.4
Debian 7

**Comment by algorys** [comment]
Is this may be because I'm using the python script for the two template contact ?

**Comment by claneys** [comment]
Hi,

SOFT alert doesn't trigger notification, it is a normal behavior. If you don't want use SOFT state, just set the max_check_attempts option on services or hosts to 1, then it will pass on HARD state immediately.

**Comment by algorys** [comment]
Ok,

But my hosts and services are defined by GLPI, so I will check that if it works with it. Thans for tip.

**Comment by claneys** [comment]
Do you still have the issue ?

**Comment by algorys** [comment]
Hello,

Sorry, to not update this issue. I've make a new install and it seems to work. I close this issue.

Thanks for help.

**Comment by claneys** [comment]
Glad to hear that.
