### ISSUE TITLE
Simplified Getting Started Documentation

### ISSUE THREAD

**Issue by pcj** [naparuba/shinken#1662]
I found the following document useful to get shinken setup on ubuntu, but it's for version 1.4

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-shinken-on-ubuntu-12-04-to-monitor-a-vps-instance

Could someone please contribute a similar document for 2.4?  

The current documentation does not seem to demonstrate how a new user can go from a fresh install to a basic working configuration.  The getting started shows how to get a fresh install going, but then then next step is basically:

```
The default configuration deployed with the Shinken sources contains:

one arbiter
one scheduler
one poller
one reactionner
one broker
one receiver (commented out)

All these elements must have a basic configuration. The Arbiter must know about the other daemons and how to communicate with them, just as the other daemons need to know on which TCP port they must listen on.
```

I'm sorry, but WTF is that supposed to mean?  Doing a complete core-dump on the terminology is very daunting.  That's a complete non-starter for potential shinken newbies like myself.  A better way would be to resist the temptation to explain everything at once and just do a walk through of setting up something basic and useful.

If such a document exists, please point me in the right direction.  Frustrated to have spent the entire day on this and have to retreat to 1.4, or possibly abandon efforts to use shinken.

**Comment by david-guenault** [comment]
here it is =>
http://shinken.readthedocs.org/en/latest/02_gettingstarted/installations/index.html



2015-06-17 21:06 GMT+02:00 Paul Cody <notifications@github.com>:

**Comment by pcj** [comment]
I do appreciate your response but I have read that document, which is why I posted this issue.  Those docs are not digestible for a new user.  Once you finish the install, the next step is:

http://shinken.readthedocs.org/en/latest/03_configuration/config.html

...which makes one want to throw oneself out the nearest window.

What I am looking for is something that can takes a new user post-fresh install and *shows* how to configure something basic and useful, not try to *explain* why things are the way they are.

**Comment by david-guenault** [comment]
ok so you are really new to all this stuff. Take a look at the online
courses.

http://shinkenlab.io/tag/online-course.html



2015-06-17 21:54 GMT+02:00 Paul Cody <notifications@github.com>:

**Comment by olivierHa** [comment]
I am closing this issue. Online course is the best way to learn.
