### ISSUE TITLE
How do we install check_nwc_health in Shinken 2.4?

### ISSUE THREAD

**Issue by Routhinator** [naparuba/shinken#1668]
It appears the documentation needs to be updated for Shinken 2.4

    install -p check_nwc_health
    install: missing destination file operand after ‘check_nwc_health’
    Try 'install --help' for more information.

This line is taken from http://shinken.readthedocs.org/en/latest/13_monitoring/router-or-switch.html

Atttempted 'shinken install check_nwc_health' but it isn't a package. I installed the 'switch' package but cannot find any documentation on it's use in relation to 2.4 and I am missing the check_nwc_health command.

**Comment by k0ste** [comment]
Before use check_nwc must be makes from sources. Last source u can fetch from here https://labs.consol.de/nagios/check_nwc_health/ (and if u need RPM, spec from here https://github.com/k0ste/check_nwc_health-rpm).

Sample command definition:

```
define command {
    command_name	check_nwc_interface_status
    command_line	$PLUGINSDIR$/check_nwc_health.pl --hostname $HOSTADDRESS$ --domain $_HOSTNWCDOMAIN$ --protocol $_HOSTNWCPROTO$ --community $_HOSTSNMPCOMMUNITY$ --timeout $_HOSTNWCTIMEOUT$ --mode interface-status --name $ARG1$
}

define command {
    command_name	check_nwc_interface_usage
    command_line	$PLUGINSDIR$/check_nwc_health.pl --hostname $HOSTADDRESS$ --domain $_HOSTNWCDOMAIN$ --protocol $_HOSTNWCPROTO$ --community $_HOSTSNMPCOMMUNITY$ --timeout $_HOSTNWCTIMEOUT$ --mode interface-usage --name $ARG1$ --units $_HOSTNWCUNIT$ --warning $_HOSTNWCIFACEWARNING$ --critical $_HOSTNWCIFACECRITICAL$
}

define command {
    command_name	check_nwc_link_state
    command_line	$PLUGINSDIR$/check_nwc_health.pl --hostname $ARG1$ --domain $_HOSTNWCDOMAIN$ --protocol $_HOSTNWCPROTO$ --community $_HOSTSNMPCOMMUNITY$ --timeout $_HOSTNWCTIMEOUT$ --mode interface-status --name $ARG2$
}
```

**Comment by olivierHa** [comment]
Indeed, the documentation is outdated :(

The "install" script is deprecated.
You can still use it at your own risk, it is located under the contrib folder 'contrib/install'. 
To install check_nwc_health, it is "just" a old configure/make/make install procedure :)

I will update the documentation. Thanks for the report.
If you got any issues, feel free to come on #shinken on freenode.
