### ISSUE TITLE
Migration from Nagios to Shinken 2.4

### ISSUE THREAD

**Issue by halysan** [naparuba/shinken#1670]
Hi everyone,

I've a Nagios and I would like migrate to shinken.
I've installed shinken 2.4 on Debian Jessie.
Can I copy/paste my configuration Nagios on my Shinken?

Or, other solution?
Best regards,

**Comment by k0ste** [comment]
shinken-arbiter -v -c /etc/shinken/shinken.cfg
And you get answers to all questions.

**Comment by halysan** [comment]
How this command answers my question?!

I ask a question on how migrate from nagios to shinken...

**Comment by k0ste** [comment]
Read the Docs. Shinken is compatible with Nagios configuration.

**Comment by halysan** [comment]
thank you I know it... --"
I just asks if copy / paste is sufficient

**Comment by k0ste** [comment]
Environment depends. If u use very base checks/plugins - yes.

**Comment by halysan** [comment]
I use base checks/plugins and other check/plugin create.

**Comment by olivierHa** [comment]
Hello, 

Did you got any questions about your migration? 
Shinken is 100% compatible with nagios configuration, it should be easy.
I will close this issue.  If you encounter issues, please come on #shinken on freenode.

Regards
