### ISSUE TITLE
Services ignored because of service description

### ISSUE THREAD

**Issue by fullmetalucard** [naparuba/shinken#1676]
Hello,

I'm actually migrating a huge shinken plaform from 1.4 to 2.4 on Debian Jessie.
Everything seemed to be fine, until i realized that only 25% of my original checks were scheduled.
Putting my eyes on it, I found that every service defined in my templates with a service_desription like that was ignored:     service_description   $KEY$

Ex:
define service{
    host_name             vmware
    name                  check_esxi_hardware
    use                   generic-service
    service_description    $KEY$
    register              0
    check_command         check_esxi_hardware!$KEY$
    check_interval              5
    duplicate_foreach     __VMWARE_ESXI_HARDWARE
    poller_tag       POLLERVMWARE
}

The $KEY$ was then defined in the host definition file, kind of:

__VMWARE_ESXI_HARDWARE          Hardware state

Which was very usefull to change the service_description directly in host configurations files.
The fact that $KEY$ isn't interpreted is strange because shinken should get the variables given in the host configuration file as it did in the previous versions.

I know that the last version of shinken uses the display_name to show up in webui instead of service_description and some patches have been done to avoid to display the "$KEY$" pattern not expanded. Is this behavior related to our problem?

After some researches,  also tried to put a "definition_order" in each service  defined as above. Does'nt work.
The fact is that i cannot rename manually each service_description, because I will loose all my PNP graphs. As you surely know it, they're all based on the service description's name. And i have thousands and thousands of graphs to migrate/rename which should take thousands of years... we're in deep deep troubles :)

I guess there's a way to keep this compatibility in 2.4.

Thx in advance for your help

**Comment by k0ste** [comment]
Try patch https://github.com/naparuba/shinken/commit/4715b8dbba4335e2f6c0cbecea3914a83109d932

**Comment by fullmetalucard** [comment]
Thanks, we allready had applied this patch, and it doesn't change this behavior (at least in our case)
Actually we have applied all those patches in our Debian 8.0 - shinken 2.4:

## Debian 8/pycurl dead lock on POST Bug:
https://github.com/naparuba/shinken/commit/e8d929c5aa8fb0e9e8b524919997715640335485

## Shinken bad display_name in webui
https://github.com/naparuba/shinken/commit/0cfcc2adcb6f5be0fa351def9f59881bfe2cdbe5

## service_description inheritance:
https://github.com/naparuba/shinken/commit/4715b8dbba4335e2f6c0cbecea3914a83109d932

Still searching

**Comment by fullmetalucard** [comment]
I must precise that shinken check considers things are OK.
Looking at the warnings in /tmp/shinken_checkconfig_result , i can see tons of lines like this:

[[93m[1436963824] WARNING: [Shinken] [service::NFS status] duplicate service name (u'servername', u'NFS status') in /etc/shinken/conf.d/SHARED/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.

I've been llooking for informations about the definition_order paramter which seems to be quite new in shinken (https://www.openhub.net/p/Shinken/commits/317470925). I didn't founs so much example of implementation for this, but i tried it in two different ways:

- adding definition_order	    0 in one of my missing services works.
- adding definition_order	    1 and 2 and 3 and so on, incrementing the number in each of my missing services doesn't work
- adding definition_order	    0 in all of my missing services doesn't work either.

**Comment by fullmetalucard** [comment]
Looks like shinken does not interpret/expand the  variables when it reads the templates files as it use to do so in the previous versions.
If i modify each one of those services with service1: $KEY$, service2:$KEY$, service3: $KEY$ "it works" but not as expected (services are scheduled but with a different service_description as before, which is bad to match with their original graphs).  For me it's impossible to manage/intend to modify those RRDs, I absolutly need to find a way to make it work as it always did in the past.

Any help appreciated
Thx

**Comment by olivierHa** [comment]
I will look into this issue.

Regards

2015-07-16 9:41 GMT+02:00 fullmetalucard <notifications@github.com>:

**Comment by fullmetalucard** [comment]
Thanks, FYI this problem/behavior occurs since the 2.2 version (tested a few months ago in another new shinken platform). I had to put explicitly each service_description in the template definition, which wasn't really a problem because i did'nt have to manage dependencies or graph migration.

**Comment by jamiemwanza** [comment]
I am a newbie to shinken. I have just configured it and added a few network hosts. I have noticed that even the ones that are offline are showing an online status. What do I need to do to monitor the live status of a host?



Jamie.

**Comment by fullmetalucard** [comment]
@jamiemwanza : Excuse me but your problem has nothing to deal with the current issue. This Github isn't a forum, but a place where you can report technical issues related to specific bugs or evolutions of shinken. For your problem you should read more the doc before posting something in the wrong place. 
@naparuba : Could you please remove this post post and mine so that this issue can stay clear and readable. Anyway please @jamiemwanza do not answer to this. 
I must also precise we didn't find any solution to this problem. In some cases we could directly replace the "$KEY$" directly by the value given in the host definition, but in most of them we cannot do it whithout rewriting completly our templates. It would be also very bad in terms of administration. Thousands of checks are still missing. Thanks for your patience and work.

Regards

**Comment by jthebert** [comment]
To complement the issue, below is a more complete extract of your configuration. 

The problem is present only when the "service_description" only contains "$KEYS". If "service_description"  contains any other character with $KEYS, then the issue is no more present ( the service description is taken into account ).

This seems like a simple bug and could impact a large number of users. Could you please see  if this can be fixed rapidly ? 

# Example of configuration 

**We define a host template for vmware**
<pre>
define host {
        name             vmware
        use              generic-host
        hostgroups       +vmware
        notes            Serveur VMware
        icon_image_alt   Serveur VMware
        icon_image       vendors/vmware.gif
        vrml_image       vendors/vmware.gif
        statusmap_image  vendors/vmware.gd2
        __wiki_page      VMWare
        register         0
}
</pre>

**We define services associated to the host template**

This service is scheduled correctly:
<pre>
define service{
    host_name              vmware
    name                      generic-esx3_datacenter_status
    use                       generic-service
    service_description       Status sur: $KEY$
    register                  0
    check_command             check_esx3_datacenter_status!$KEY$!$VALUE$
    check_interval        5
    duplicate_foreach          __VMWARE_ESX_DATACENTER_STATUS
}
</pre>

This service is **not scheduled** ( only "$KEY$" is present in the service description )

<pre>
define service{
    host_name                 vmware
    name                      generic-esx3_host_vm_list
    use                       generic-service
    service_description       $KEY$
    register                  0
    check_command             check_esx3_host_vm_list!$KEY$
    check_interval        5
    duplicate_foreach         __VMWARE_ESX_HOST_VM_LIST
}

</pre>

**Then we declare an host using the vmware template**
<pre>
define host{
           use                                 client_serveurs,vmware
        host_name                           ESXI01
        address                             XXXXXXX
        notes                               Adresse NAT : XXXXXXXX
        realm                               realm_client
        __VMWARE_ESX_STATUS                 Status
        __VMWARE_ESX_HOST_VM_LIST           VM list
}
</pre>

**Comment by GrdNico** [comment]
Hello, 
(sorry not english fluent) 

I made some test on a dev plateform   : 

5 hosts all linux 
shinken 2.4.1 / debian 8  

HOSTS : 
<pre>
define host{
        host_name       vm-Mail
        alias           SrvMail
        use             T-Linux

        address         192.168.106.10
        __DISK                        /,/tmp,/usr,/var,/var/log,/data
}
define host{
        host_name       vm-Monit
        alias           SrvMonitoring
        use             T-Linux

        address         192.168.106.20
        __DISK                        /,/tmp,/var/log,/data
}
</pre>

on T-Linux.cfg
<pre>
define host{
        name            T-Linux
        use             generic-host
        contact_groups  supervision
        __CPU           sys: cpu
        register                        0

}
define service{
        service_description     sys: $KEY$
        use                     gen-service-15,gen-pnp
        host_name               T-Linux
        check_command           check_nrpe_args!check_disk!$KEY$!$_HOST_DISK_WARN$!$_HOST_DISK_CRIT$
        duplicate_foreach       __DISK
        __DISK_WARN                     10%
        __DISK_CRIT                     5%
        register 0
}
define service{
        service_description     $KEY$
        use                     gen-service-5,gen-pnp
        host_name               T-Linux
        check_command           check_nrpe_args!check_cpu!$_HOST_CPU_WARN$!$_HOST_CPU_CRIT$
        register 0
        duplicate_foreach       __CPU
        __CPU_WARN                    85
	__CPU_CRIT                    90
}
</pre>

on this configuration I got all check (disk AND cpu ) on the 2 hosts ( in fact on the five hosts but i only give 2 host conf here)

now : 

on T-Linux.cfg
<pre>
define host{
        name            T-Linux
        use             generic-host
        contact_groups  supervision
        __CPU           cpu
        register                        0

}
define service{
        service_description     sys: $KEY$
        use                     gen-service-15,gen-pnp
        host_name               T-Linux
        check_command           check_nrpe_args!check_disk!$KEY$!$_HOST_DISK_WARN$!$_HOST_DISK_CRIT$
        duplicate_foreach       __DISK
        __DISK_WARN                     10%
        __DISK_CRIT                     5%
        register 0
}
define service{
        service_description     sys: $KEY$
        use                     gen-service-5,gen-pnp
        host_name               T-Linux
        check_command           check_nrpe_args!check_cpu!$_HOST_CPU_WARN$!$_HOST_CPU_CRIT$
        register 0
        duplicate_foreach       __CPU
        __CPU_WARN                    85
	__CPU_CRIT                    90
}
</pre>
service_description  is the same "sys: $KEY$" ==> reload shinken only see "sys: cpu " on all my hosts. 
now I try to reverse conf : 
<pre>
define host{
        name            T-Linux
        use             generic-host
        contact_groups  supervision
        __CPU           cpu
        register                        0

}

define service{
        service_description     sys: $KEY$
        use                     gen-service-5,gen-pnp
        host_name               T-Linux
        check_command           check_nrpe_args!check_cpu!$_HOST_CPU_WARN$!$_HOST_CPU_CRIT$
        register 0
        duplicate_foreach       __CPU
        __CPU_WARN                    85
	__CPU_CRIT                    90
}

define service{
        service_description     sys: $KEY$
        use                     gen-service-15,gen-pnp
        host_name               T-Linux
        check_command           check_nrpe_args!check_disk!$KEY$!$_HOST_DISK_WARN$!$_HOST_DISK_CRIT$
        duplicate_foreach       __DISK
        __DISK_WARN                     10%
        __DISK_CRIT                     5%
        register 0
}
</pre>
service_description  is the same "sys: $KEY$" ==> reload shinken : I see all my disk check but no more "sys: CPU" 

So the issue is not with "service_description $KEY$" only. if in a template two (or more) service description are exactly the same ==> only the last is here. (I try with tree (3)  define service { ..} with the same "service_description" and is exactly the same , only the last one is here ) 

I less " /tmp/shinken_checkconfig_result" each try and there is no Warning or ERROR statement on the particular service.

hope it's help and continue such a good job    

Regards,

Nicolas.

**Comment by olivierHa** [comment]
Thanks for this report. I will starting at this issue next week.
Keep you in touch.

**Comment by olivierHa** [comment]
First step of resolution : a simple working test case :)
https://github.com/naparuba/shinken/commit/24de3c81a2fcfd1d7da404530faf726e424d5fbf

**Comment by olivierHa** [comment]
Could you test the master version ?

**Comment by Pi3R1k** [comment]
I just test master version but unfortunately the problem is still there.

I always have this warnings in arbiter file log and services are not loaded.

```
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host05', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host02', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host06', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host08', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host01', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host04', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host07', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
[1439827950] WARNING: [Shinken] [service::NFS status] duplicate service name (u'host03', u'NFS status') in /etc/shinken/conf.d/OS/tmpl_Linux.cfg:577, using lastly defined. You may manually set the definition_order parameter to avoid this message.
```
