### ISSUE TITLE
Shinken versions

### ISSUE THREAD

**Issue by arthru** [naparuba/shinken#1679]
Latest release of shinken is 2.4.1 and the previous one was 2.4.

I package shinken for arch linux and that change in version semantic come with a problem that version 2.4.1 < 2.4. So the update won't be proposed if you use a repository.

So I suggest for the future to name version after X.Y.Z convention instead of X.Y

2.4 would then be 2.4.0 and latest 2.4.1 would be proposed during update.

I don't know if this problem can occur with other distributions...

**Comment by rohit01** [comment]
Sounds good. +1

**Comment by naparuba** [comment]
Valid, I'll use the .0 for the next big release :)
