### ISSUE TITLE
perfdata metrics management and storage

### ISSUE THREAD

**Issue by mohierf** [naparuba/shinken#1689]
As described in https://github.com/shinken-monitoring/mod-webui/issues/274, Shinken may store all the received metrics in the service perfdata and not only the last one.

 This feature is not interesting in the core but may be interesting in some modules (like WebUI or Graphite) ...

Let me explain with an example : 
- you receive a service check with perfdata containing **counter1=1**
- you receive a new check for the same service with perfdata containing **counter2=1**

Only the metric counter2 is known by Shinken whereas **counter1** is a metric that should be available for the service ... it may be interesting that all the metrics received in the perfdata are stored with the service and not only the last one !

 An host or service item should update a received metrics dictionnary and not only a perfdata string ?

**Comment by naparuba** [comment]
Just too dangerous, some plugins are exporting new keys every checks, will be a memory nightmare.

It's up to modules to manage this, not for the framework. (I think something like a leveldb base can be a good solution for this :) ).
