### ISSUE TITLE
Manage option 'initial_state' on conf (host and service)

### ISSUE THREAD

**Issue by hvad** [naparuba/shinken#1693]
Hi,

initial_state is not managed in shinken.
See https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html

Arguments initial_state don't work because is not present in shinken code but present in the doc.

Best regard

**Comment by hvad** [comment]
version 2.4.1

**Comment by geektophe** [comment]
You're right, the initial_state was in the list of hosts or services attributes, but not taken into account. It's added in https://github.com/naparuba/shinken/pull/1711

**Comment by geektophe** [comment]
Pull request has been merged. I think  we may close this issue.
