### ISSUE TITLE
[Shinken 2.4] Inheritance issue (rel to issue #1472 ?)

### ISSUE THREAD

**Issue by bplessis** [naparuba/shinken#1695]
Hi,

We have a big nagios3 configuration using hostgroup and service templates, the configuration loaded successfully within shinken 2.0.3 (debian) but we where have some unexplained issue (check not being performed, errors, ..) so we tried shinken 2.4 but there the configuration fail, with two kind of messages:

1/ If there is only one host declared for the hostgroup:
> ERROR: [Shinken] [service::r1/SSH] a service item has been defined without unique_key in /etc/shinken-org/services/test.cfg:1
> ERROR: [Shinken] [items] In SSH is incorrect ; from /etc/shinken-org/services/test.cfg:1
> ERROR: [Shinken]   services conf incorrect!!

2/ If there is two or more host declared for the hostgroup:
> ERROR: [Shinken] [service::UNKNOWN-SERVICE] a service item has been defined without unique_key in /etc/shinken-org/services/test.cfg:1
> ERROR: [Shinken] The service 'SSH' got an unknown host_name 'r1,r2'.
> ERROR: [Shinken] [items] In SSH is incorrect ; from /etc/shinken-org/services/test.cfg:1
> ERROR: [Shinken]   services conf incorrect!!

Example configuration:

```
define hostgroup {
        hostgroup_name  	cisco-routers
	alias			Cisco Routers
        }
define host{
	use		router-host
	host_name	r1
	address		1.1.1.1
        hostgroups      +cisco-routers
	}

define host{
	use		router-host
	host_name	r2
	address		1.1.1.2
        hostgroups      +cisco-routers
	}

# Service template:
define service{
        name                    ssh-critical-service
        use                     generic-service

        service_description     SSH
        check_command           check_ssh

        register                0
}

define service {
        use			ssh-critical-service
        hostgroup_name          cisco-routers
}
```

**Comment by hvad** [comment]
Hi,

Try to replace name by service_description for ssh-critical-service.  

Best regard

**Comment by olivierHa** [comment]
Please try 2.4.1 version

**Comment by bplessis** [comment]
Le 14/08/2015 13:21, hvad a écrit :
> Try to replace name by service_description for ssh-critical-service. 

I don't understand what you mean, the only way i found to make the
configuration work is to duplicate the service_description line from the
template
to the real service definition, but it's going to make the configuration
quite harder...


> Please try 2.4.1 version

Obviously this fixes that, sorry i used pip to install shinken, didn't
saw 2.4.1 was published.


I don"t know if it's expected however but including a hostgroup twice in
another hostgroup, either like this:


```
define hostgroup{
        hostgroup_name  preprod_web_servers
        }

define hostgroup{
        hostgroup_name          preprod_servers
        hostgroup_members       preprod_web_servers
        }

define hostgroup{
        hostgroup_name          web_servers
        hostgroup_members       preprod_web_servers
        }

define hostgroup{
        hostgroup_name          servers
        hostgroup_members       web_servers,preprod_servers
        }
```

or like this:

```
define hostgroup{
        hostgroup_name  preprod_web_servers
        }

define hostgroup{
        hostgroup_name          preprod_servers
        hostgroup_members       preprod_web_servers
        }

define hostgroup{
        hostgroup_name          servers
        hostgroup_members       web_servers,preprod_web_servers
        }
```


Still give the following un-intuitive error message:

> [hostgroup::preprod_web_servers] got a loop in hostgroup definition

**Comment by bplessis** [comment]
Ok, that's weird my "extracted-example" work with 2.4.1, but not the full original configuration, i need to see why

**Comment by hvad** [comment]
It's because your template is like this : 
define {
 name                    ssh-critical-service
 use                      generic-service
....
}

Test like that : 
define {
 service_description                    ssh-critical-service
 use                                            generic-service
....
}

**Comment by bplessis** [comment]
@olivierHa Ok, 2.4.1 doesn't fix the problem in fact, i was testing with a workaround applied in the configuration.

@hvad i can't do that, ssh-critical-service is a service template, it need a name to be re-used elsewhere. If i do what you suggest i get the following error:
Shinken] [items] Service 'SERVICE-DESCRIPTION-MISSING' use/inherit from an unknown template (u'ssh-critical-service') !


The only way that seem to work is to duplicate the service_description in the child service:
# Service template:
define service{
        name                    ssh-critical-service
...
        service_description     SSH
..
        register                0
}
# real service
define service {
        use         ssh-critical-service
        service_description     SSH
        hostgroup_name          cisco-routers
}

**Comment by hvad** [comment]
I had similare problem and i solved it with that. 

### Template generic-service
define service{
        name                            generic-service
        service_description             generic-service
        is_volatile                     0
        max_check_attempts              3
        normal_check_interval           5
        retry_check_interval            1
        active_checks_enabled           1
        passive_checks_enabled          0
        check_period                    24x7
        notification_period             24x7
        notification_interval           0
        notification_options            w,c,r
        notifications_enabled           1
        register                        0
}

define service{
        host_name                       generic-host
        service_description             Ping
        use                             generic-service
        check_command                   check_fping!3!3000,40%!5000,50%
        register                        0
}

Do as you like. it's a bug present in shinken 2.4.x   and name doesn't existe on doc -> https://shinken.readthedocs.org/en/latest/08_configobjects/service.html#configobjects-service.

**Comment by geektophe** [comment]
This bug has been introduced in 6f32e24535c4ba313d590eec90dc6e9e5ab5bc1f by the introduction of `add_partial_service` method.

I'll try to see if I can find a solution.

**Comment by geektophe** [comment]
I have the feeling that the fix in https://github.com/naparuba/shinken/issues/1472 did not fix the issue. I'll have a closer look.

**Comment by geektophe** [comment]
The problem should be fixed in https://github.com/naparuba/shinken/pull/1710. Could you try and confirm it works with this patch ?

**Comment by bplessis** [comment]
Hi,

Sorry for the delay, anyway it's ok now our configuration is loaded without errors
