### ISSUE TITLE
IPv6 for interconnection between shinken components

### ISSUE THREAD

**Issue by favadi** [naparuba/shinken#1696]
Hi,

I'm trying to use IPv6 to connect between shinken components.

Version:

```
Pyro==3.16
Shinken==2.0.3
```

I install all shinken components in a server that has an IPv6 address available and use this address in config. I found out that if I use this address in shinken-scheduler and shinken-broker configs, the web ui didn't listen on 7767 port any more. If I replace this IPv6 address with IPv4 address, the web ui will start listening to port 7767 and works as normal. There is nothing in shinken log even with level=DEBUG.

So my questions:

* is shinken officially support IPv6?
* if yes, how can I debug my setup?

**Comment by hvad** [comment]
Hi,

Pyro is not require and Shinken doesn't support ipv6 between components. 

Best regard
