### ISSUE TITLE
Problem with trailing space in the description of a service

### ISSUE THREAD

**Issue by flaf** [naparuba/shinken#1697]
Hi,

Here is an example:

```
define host {
    host_name host-foo
    use       template-with-duplicate-foreach-key
    address   www.xxx.yyy.zzz

    # Key from a "duplicate_foreach" instruction.
    _my_key description n1 $(val1)$ $(val2)$, \
            description n2 $(val1)$ $(val2)$, \
            description n3 $(val1)$ $(val2)$,
}
```

In this example, the descriptions of the services will be `"description n1 "`, `"description n2 "` and `"description n3 "` with a trailing space in the name which will trigger some problems for instance in the WebUI. Indeed, the WebUI will have some dead links (error 500) such as `http://fqdn/service/<host>/<description-of-a-service>` (link to a service).

Currently, there is a workaround: just remove the space between the description and the dollar like this:

```
define host {
    host_name host-foo
    use       template-with-duplicate-foreach-key
    address   www.xxx.yyy.zzz

    # Key from a "duplicate_foreach" instruction.
    _my_key description n1$(val1)$ $(val2)$, \
            description n2$(val1)$ $(val2)$, \
            description n3$(val1)$ $(val2)$,
}
```
In this case, no problem, the descriptions will be `"description n1"`, `"description n2"` and `"description n3"`  without the trailing space.

But it should be smarter if the description of a service was systematically striped, ie with `desc = desc.strip()` somewhere in the code.

Regards.

**Comment by geektophe** [comment]
Are you sure it works with a space between the val1 and val2 placeholders ?

**Comment by geektophe** [comment]
It should be possible with https://github.com/naparuba/shinken/pull/1712. Could you have a test ?

**Comment by olivierHa** [comment]
up ?

**Comment by naparuba** [comment]
no news, I close.
