### ISSUE TITLE
Retain State Information will not be implemented?

### ISSUE THREAD

**Issue by ianling** [naparuba/shinken#1698]
Line 205 in config.py:

    'retain_state_information':
            UnusedProp(text='sorry, retain state information will not be implemented '
                            'because it is useless.'),

Does this mean that Shinken has a feature that replaces this? It is definitely not a useless feature of nagios. When I restart Shinken, I receive 400+ emails about down hosts and services that were already known to be down.

**Comment by olivierHa** [comment]
In Shinken, it is called "retention".
You "just" need to configure a retention module in daemons configuration.

Regards

Olivier

2015-08-21 18:11 GMT+02:00 Ian <notifications@github.com>:

**Comment by ianling** [comment]
Got it, thanks a lot!
