### ISSUE TITLE
Can't have host_notification_period without _command in contact cfg

### ISSUE THREAD

**Issue by ianling** [naparuba/shinken#1699]
I am trying to set Shinken up in such a way that contacts use the same email notificationway, but then each contact has their own timeperiod set. 

In the notificationway, the period is set to 24x7.

In the contact:

    define contact{
        use                             generic-contact
        contact_name                    ianl
        email                           <my email>
        address1                        <some other address>
        is_admin                        1
        notificationways                email
        host_notification_period        ianl_workhours
        service_notification_period     ianl_workhours
    }

This gives me the following error when I restart arbiterd:

    [1440442778] INFO: [Shinken] Checking notificationways...
    [1440442778] WARNING: [Shinken] [notificationway::ianl_inner_notificationway] do not have any service_notification_commands defined
    [1440442778] WARNING: [Shinken] [notificationway::ianl_inner_notificationway] do not have any host_notification_commands defined
    [1440442778] ERROR: [Shinken] [items] In ianl_inner_notificationway is incorrect ; from unknown
    [1440442778] ERROR: [Shinken]     notificationways conf incorrect!!
    [1440442778] INFO: [Shinken]      Checked 10 notificationways

However, if I add host_notification_commands and service_notification_commands to the contact, it works. Is this a bug, or am I configuring something incorrectly?

You might suggest that I abandon notificationways altogether if simply setting _commands fixes the issue, but it doesn't. I actually need two notification commands to run, so I separate them by commas, like:

     host_notification_commands     notify-host-by-email,notify-host-by-somethingelse

However, it ends up running neither of these, effectively breaking notifications. 

Any ideas?

**Comment by ianling** [comment]
Looking through old issue reports, I see that contacts inherit nothing from notificationways, which explains my problem. I will have contacts inherit from something else then.

**Comment by LoveIsGrief** [comment]
I might like to add a little more information and say that I had *host_notification_options* and *service_notification_options* in my `define contact`, which led to this error. Removing them and letting the notificationway take over, fixed this issue.
