### ISSUE TITLE
$KEY$ not replaced in thruk

### ISSUE THREAD

**Issue by h4wkmoon** [naparuba/shinken#1700]
Hi, 

I'm using thruk 2, with shinken 2.4.
I have a service definied like this : 

define service{
	        process_perf_data        0
                icon_image 171px-Logo_der_Software_collectd.svg.png

   service_description    PROC $KEY$
   use            	  generic-service
   register       	  0
   host_name	  	  collectd
   check_command          check_process_collectd_list!$KEY$
   duplicate_foreach	  _processes
}

In the "services" view in Thruk, I can still see $KEY$ instead of the values.
It becomes even weirder when I check the configuration view. In this view, every thing is fine. The $KEY$ are replaced by the values.

I don't think this is a thruk issue because only asks the livestatus module for info. It's not supposed to know that the service is an exploded version of the "duplicate_foreach" template.

I'll have a look into the module to see if I find something.

This is somehow a regression. I'm sure it worked correctly a few months ago, with shinken 2.1.

**Comment by olivierHa** [comment]
Hello,

Are you using Shinken 2.4 or 2.4.1 ?

Regards

Olivier

2015-08-24 22:33 GMT+02:00 Frédéric Pégé <notifications@github.com>:

**Comment by h4wkmoon** [comment]
Found it.
This issue is that Thruk displays the display_name.
This prop is not handled by duplicate_for_each.
I'm about to make a PR.

**Comment by halysan** [comment]
Hi !
I think that Thruk 1.88-4 is more stable that 2.0...

I had the same problem with 2.0 and Thruk 1.88-4 solves the problem.

**Comment by olivierHa** [comment]
This bug should have been resolved in 2.4.1
What is your shinken version Frederic ?

2015-09-09 15:18 GMT+02:00 halysan <notifications@github.com>:

**Comment by halysan** [comment]
Sorry, with "pip" the last version is 2.4..

But Thruk 1.88-4 resolved this problem..

**Comment by h4wkmoon** [comment]
@halysan, problem is not in Thruk.
The issue was that KEY value was not replaced in display_name. ==> This is obviously a shinken issue.

@olivierHa, I don't know currently my version. It was the pip version of the moment. Certainly, 2.4.
If you say, it's solved in 2.4.1 then I believe you.
