### ISSUE TITLE
Shinken using old version of plugin

### ISSUE THREAD

**Issue by ianling** [naparuba/shinken#1707]
I have a service that uses a custom plugin for its check_command. When I first started testing this plugin, Shinken gave me an error, which was just a Python syntax error because I'd made a mistake in the plugin. I fixed it by removing the problematic line from the plugin completely, so this line doesn't even exist anymore.

To make sure Shinken started using this new, fixed version of my custom plugin, I restarted Shinken completely (wiped the retention data as well, just in case). This didn't work, it's still using the old, broken version of my plugin somehow.

There are no copies of the plugin anywhere on the server, so it's not pulling an old version from some other folder. Just to be sure, I copied the plugin and gave it a different name, so that it wouldn't try to use a cached version, and then made the service's check_command point to the copy of the plugin.

Using the copy, Shinken says the file doesn't exist (i.e. the copy of the plugin doesn't exist). 

This makes no sense to me. This doesn't even work with retention turned off, when Shinken shouldn't be caching anything between restarts, yet it appears to be caching things. Any ideas?

edit: just to add on to this, if I "su shinken" and then try running the plugin directly, it works perfectly.

**Comment by ianling** [comment]
Shinken does not push plugins to other servers (we use distributed monitoring). That was the issue. I copied the updated plugin to the other servers and it's working now.

**Comment by hvad** [comment]
Hi,

Deploy plugins is not shinken feature but you can use ansible or puppet or chef, etc... . I use ansible to do that ^^.  

Regard
