### ISSUE TITLE
Latest release 2.4.1 unavailable at PyPI

### ISSUE THREAD

**Issue by rdoursenaud** [naparuba/shinken#1714]
Only 2.4 is available.

This prevents install or upgrade via pip.

**Comment by Pi3R1k** [comment]
For now, you can use : 
```
pip install https://github.com/naparuba/shinken/archive/2.4.1.zip
pip install --upgrade https://github.com/naparuba/shinken/archive/2.4.1.zip
pip install https://github.com/naparuba/shinken/archive/master.zip
```

Just care of your /etc/shinken/

**Comment by rdoursenaud** [comment]
Thanks @Pi3R1k. I didn't know that. Worked a treat :)
I manage my /etc/shinken under git since ages. Helps to  safe upgrades

**Comment by olivierHa** [comment]
Closing. 2.4.2 is available, and another release will be available too
