### ISSUE TITLE
the module named-pipe is unknown for arbiter-master

### ISSUE THREAD

**Issue by Megachip** [naparuba/shinken#1718]
After upgrading shinken 2.2-1 to 2.4.1-1 on Mageia Caldron I've got lost the named-pipe module.

```
Sep 17 15:40:22 server shinken-arbiter[4523]: [1442497222] ERROR: [Shinken] [item::arbiter-master] Error: the module named-pipe is unknown for arbiter-master
Sep 17 15:40:22 server shinken-arbiter[4523]: [1442497222] ERROR: [Shinken] [items] In arbiter-master is incorrect ; from /etc/shinken/arbiters/arbiter-master.cfg:13
```

**Comment by geektophe** [comment]
- Did you set the `modules_dir` accordingly to where modules are installed ?
- Is there any other modules that the arbiter, or other daemons fail to start ?
- Which module version are you using ?
- Could you paste an arbiter configuration sample ?

**Comment by Megachip** [comment]
> Did you set the modules_dir accordingly to where modules are installed ?

modules_dir=/var/lib/shinken/modules set in schedulerd, brokerd, reactionerd,receiverd, pollerd

> Is there any other modules that the arbiter, or other daemons fail to start ?

nope, other modules working fine

> Which module version are you using ?
Hard to say cause module did not exist. 

> Could you paste an arbiter configuration sample ?

**non working**:
modules            named-pipe, import-glpi, ws-arbiter
**working**:
modules            import-glpi, ws-arbiter

**Comment by jgwinner** [comment]
I ran into the same thing with a totally vanilla install of Oracle Linux, then loading Shinken from the website, THEN laying 2.4.2 on top of THAT version :) 

== John ==
