### ISSUE TITLE
wall view problem Error 404

### ISSUE THREAD

**Issue by jhautefeuille** [naparuba/shinken#1728]
Error 404: Not Found
Sorry, the requested URL 'http://10.59.6.80:7767/wall' caused an error:
Not found: '/wall'

I've checked nano /var/lib/shinken/modules/webui/plugins/wall/views/wall.tpl and globals() present.

I use Shinken 2.2 installed with pip on Centos 7. 

Can you give me where I can search ?

**Comment by mohierf** [comment]
This problem is relating to Shinken WebUI ... not Shinken core. You should have a look here for the Shinken WebUI: https://github.com/shinken-monitoring/mod-webui

I suppose that you did not installed the new WebUI (version 2) because you should not have met this problem!

**Comment by jhautefeuille** [comment]
Thank you, I've just updated it.
It could be great to indicate it in official documentation.

**Comment by mohierf** [comment]
As far as I remember, the official documentation does not request to install WebUI ?

@naparuba : anyway, @jhautefeuille is right ... updating documentation to link to the WebUI installation  will help new users ...
