### ISSUE TITLE
Livestatus will not change logstore modules

### ISSUE THREAD

**Issue by ianling** [naparuba/shinken#1730]
In /etc/shinken/modules/livestatus.cfg, I have tried to change it from logstore-sqlite to logstore-null or logstore-mongodb, however, these changes do not appear to take effect at all. 

If I restart the broker after making these config changes, and then watch the logs, they show that logstore-sqlite is still being used. I have installed logstore-mongodb and -null so that is not the problem, and I am already using retention-mongodb, so I know mongodb itself is working.

The reason I'm trying to do this in the first place is that there seems to be an extreme performance issue that occurs over time when sqlite is used for the logstore. Livestatus slows to a crawl, making each request to it take 30+ seconds, which makes using multisite nearly impossible because it's so slow. The slowness is resolved by restarting the shinken-broker service.

**Comment by gst** [comment]
restart the arbiter and it should be fine.
It's the arbiter which manage that setting as well (as about all others settings).
All others daemons only manage/load themselves their respective *daemon*.ini file. The others settings are uploaded from the arbiter to each of them (basically when the arbiter (re)start).
