### ISSUE TITLE
can't login after reboot

### ISSUE THREAD

**Issue by sdarwin** [naparuba/shinken#1742]
Operating System: Ubuntu 14.04
Shinken: 2.4.2
We had Shinken 2.4 and noticed it wasn't starting on reboot due to permissions problems on /var/run/shinken.  Therefore, upgraded to 2.4.2.
Now, a new problem appears during reboot.  All the shinken services start.  Try to login to the webui, and it says "Warning! Invalid user or Password".
Manually restart shinken services.   
Then it works.
Any ideas how to fix this?
The problem is reproducible.   If you'd like me to turn on some type of debugging and report the information, let me know.
Thanks.

**Comment by geektophe** [comment]
It takes time for configuration to be dispatched to all services (including modules). It is very common not being able to login just after the configuration changed, or the broker has been restarted. You just have to wait a little bit.

**Comment by sdarwin** [comment]
Hi geektophe, are you running this configuration specifically:   Shinken 2.4.2 , Ubuntu/Debian , and webui?      if so, it would be good to get another data point, try it out.  reboot. login.  I did not see a noticable delay when restarting the service, but rebooting was the problem.     I have not revisited this since the original post, because we downgraded back to 2.4.0.

**Comment by geektophe** [comment]
I'm running shinken 2.4.2 running on ubuntu trusty with WebUI. I also ran all previous releases from 1.2, under lucid and trusty, but did not face this issue.

Once rebooted, could you check that the broker did well start, and sucessfully loaded the webui, and the authentication module that you rely on ? (have a look in brokerd.log).

**Comment by sdarwin** [comment]
Upgraded to 2.4.3.   Not seeing the same issue, after the upgrade.  closing ticket.
