### ISSUE TITLE
Error: 500 Internal Server Error on System->Logs menu

### ISSUE THREAD

**Issue by Azef1** [naparuba/shinken#1747]
Hi, 
I installed Shinken 2.4, webUI2 and mod-mongo-log.
When i would like to access page : System->Logs, i have this message: 
Error: 500 Internal Server Error
![err_logs](https://cloud.githubusercontent.com/assets/15362041/10904882/b705eed4-8216-11e5-8043-40a776b3e3fc.PNG)
![err500](https://cloud.githubusercontent.com/assets/15362041/10904995/85b8235a-8217-11e5-9c7e-ec7b5f1f17dc.png)

I have been bottle.py and logs.tpl

Thx

**Comment by mohierf** [comment]
You should have opened this issue in https://github.com/shinken-monitoring/mod-webui ... please do it and close this one.
