### ISSUE TITLE
Notification email command doesn't work with double quotes in 2.4.2

### ISSUE THREAD

**Issue by erny** [naparuba/shinken#1752]
In stock 2.4.2, the notification email command in something like this:

    define command {
        command_name    notify-service-by-email
        command_line    $PLUGINSDIR$/notify_by_email.py -n service -S localhost -r $CONTACTEMAIL$ -f html -c "$NOTIFICATIONTYPE$,,$HOSTNAME$,,$HOSTADDRESS$,,$LONGDATETIME$" -o "$SERVICEDESC$,,$SERVICESTATE$,,$SERVICEOUTPUT$,,$SERVICEDURATION$"
}

The log shows something like this:

    [1447328413] WARNING: [Shinken] The notification command '/var/lib/shinken/libexec/notify_by_email.py -n service -S localhost -r user@example.org -f html -c "PROBLEM,,hostname,,192.168.14.41,,Thu 12 Nov 12:40:10 CET 2015" -o "Memory,,WARNING,,Memory: WARNING Total: 3949 MB - Used: 3717 MB - 94% used!,,00h 04m 01s"' raised an error (exit code=1): '

When I run the command in bash, I get:

    bash: !,,00h: event not found

So there's some nasty shell expansion problem. If I you use single quotes instead of double quotes in the shell command, the problem disappears. I'm not sure why ! is used to cut the strings.

I changed my the command definition to use single quotes. I hope this helps.

**Comment by erny** [comment]
Ok, it seems that the shell does replace ! and !! if it's not enclosed by single quotes.

**Comment by arthurlogilab** [comment]
+1

**Comment by olivierHa** [comment]
This should be fixed.
