### ISSUE TITLE
Notification mails fails due to sys.stdout.encoding being None

### ISSUE THREAD

**Issue by erny** [naparuba/shinken#1754]
When starting supervisor from non-interactive shell, sys.stdout.encoding may be None. That causes that notify that https://github.com/naparuba/shinken/blob/master/libexec/notify_by_email.py#L228 fails.

**Comment by mohierf** [comment]
May be fixed with #1745 proposed workaround? Did you try ?

**Comment by erny** [comment]
Well, the error is different, something like: TypeError: encode() argument 1 must be string, not None

I just put: html_msg = html_content.encode(sys.stdout.encoding or 'utf8')
