### ISSUE TITLE
No notification mail sent since upgrade 2.4.0 --> 2.4.2

### ISSUE THREAD

**Issue by sdarwin** [naparuba/shinken#1755]
Hello,

notification emails not sent after an upgrade 2.4.0 --> 2.4.2.
Ubuntu 14.04

Testing:

/var/lib/shinken/libexec/notify_by_email.py -n service -S localhost -r sam@example.com -f html -c "field 1 testing" -o "field 2 testing"

ImportError: No module named html

pip install html

It solved that particular error.  So, html should be added as a module dependency during shinken installation.  Can that be done more automatically, rather than as a manual step?

Next,

/var/lib/shinken/libexec/notify_by_email.py -n service -S localhost -r sam@example.com -f html -c "field 1 testing" -o "field 2 testing"

Traceback (most recent call last):
  File "/var/lib/shinken/libexec/notify_by_email.py", line 297, in <module>
    'Hostname': macros[1],
IndexError: list index out of range

any idea?

Thanks.

**Comment by sdarwin** [comment]
good progress on this one:

In the previous example I had written -c "field 1 testing" -o "field 2 testing" as arguments to the command.  That is wrong.

changing the command line to:   -c "PROBLEM,,server1,,server1.example.com,,Sat 14 Nov 19:59:49 EST 2015"

Then it says the mail is sent successfully, but it does not arrive.

Then, in notify_by_email.py, change the code, socket.gethostname() to socket.getfqdn() in the two places it appears.

The mail arrives now.  Why? Email systems often depend on a full qualified domain name.

So, the fix in this case was to have socket.getfqdn() in notify_by_email.py , and add html as a python module dependency.        

the ticket can be closed.

**Comment by arthurlogilab** [comment]
got hit by this bug too

**Comment by hvad** [comment]
Don't use notify_by_email.py for test shinken notification it's not a part of shinken core. Use standard command like nagios way.

**Comment by arthurlogilab** [comment]
I don't understand the "it's not part of shinken core". 

How come it's in the default configuration : https://github.com/naparuba/shinken/blob/master/etc/commands/notify-host-by-email.cfg and the code is shipped with shinken : https://github.com/naparuba/shinken/blob/master/libexec/notify_by_email.py

**Comment by N-Mi** [comment]
I can confirm installing "html" library (using pip as there is no Debian package) and changing socket.gethostname() to socket.getfqdn() in notify_by_email.py fixes the issue on Debian Jessie running Exim4 (default MTA).

**Comment by olivierHa** [comment]
Fixed. Closing
