### ISSUE TITLE
Déplacer le dépot de shinken dans https://github.com/shinken-monitoring/

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1758]

**Comment by olivierHa** [comment]
Not a real issue ;)
Closing it. you can discuss about that with Jean

**Comment by dguenault** [comment]
and i don't think it will be that easy. ;-)



2016-02-27 11:01 GMT+01:00 Olivier H <notifications@github.com>:

**Comment by arthurlogilab** [comment]
shame, I think it sends mixed signals to new comers.
