### ISSUE TITLE
Use standard logs to file errors, not /tmp/bad_start_*

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1759]
Using standard log files to display errors for services not starting would be nicer. 

On top of that with version 2.4 the /tmp/bad_start_* have color codes in them so that makes them unreadable using less or tail, one has to cat them to read them (you can probably have a duplicate of the log somewhere with color).

**Comment by naparuba** [comment]
less -r is your friend. And here are mainly error about thng that are done before open logs and such things. So nop.
