### ISSUE TITLE
Atomic files to enable modules in brokers, arbiters, etc.

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1760]
I deploy my shinken configuration using centralised configuration management sofware (salt in my case, but this issue also works for puppet and the others). 

I would like to enable modules without touching the "default" configuration files. Having an include mechanism like in most services (these days) would be useful for this scenario. 

That way, a package manager won't have to try out a diff when replacing the new default configuration since all the custom configuration is in the ```config.d``` directory. I don't think I have to list the advantages since part of the shinken configuration is already that way (```resource.d``` for example).

For the example I would like to enable webui2 in my broker configuration and pickle-retention-arbiter in /etc/shinken/arbiters/arbiter-master.cfg. 

```
# shinken --version
shinken 2.4.2
```

**Comment by arthurlogilab** [comment]
with this same idea, rename contacts to contacts.d ?

**Comment by geektophe** [comment]
Shinken uses the exact same inclusion mechanism as Nagios. As soon as you specify a `cfg_dir` directive, it will include all files into it recursively.

As the configuration is a flat list of objects, you may organize your files to mach your needs exactly as you want. Your are absolutely not obliged to stick to default layout.

**Comment by olivierHa** [comment]
Closing this issue. As @geektophe  said, you can already organized all directories as you want.
