### ISSUE TITLE
restarting shinken-broker is not enough to enable a module configured in broker.cfg

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1761]
To reproduce: 

* configure shinken
* start all components
* enable webui (or livestatus) in /etc/shinken/brokers/broker-master.cfg
* service  shinken-broker restart (no error)
* netstat -apn | grep 5000 or netstat -apn | grep 7767

**Comment by olivierHa** [comment]
Hey, you need to restart arbiter, not broker.
This isn't a bug. Broker are passive, just waiting for arbiter config.

2015-11-25 9:57 GMT+01:00 Arthur Lutz <notifications@github.com>:

**Comment by arthurlogilab** [comment]
OK, then this is a documentation bug, it should appear in a comment next to the list of modules so that a new user doesn't have to understand the architecture of shinken to start using it.

**Comment by olivierHa** [comment]
Closing this one. Feel free to update documentation if you think something isn't clear.
