### ISSUE TITLE
Use human readable dates in logs

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1764]
Example : 
```
/var/log/shinken/arbiterd.log:[1448441815] ERROR: [Shinken] [module] unknown SQLitedb module from webui2
```
timestamps are for machines, not sysadmins. 

or is this configurable ?

**Comment by guillaumefort** [comment]
Hi,

Did you try this ? http://shinken.readthedocs.org/en/latest/03_configuration/configmain-advanced.html#human-format-for-log-timestamp

**Comment by arthurlogilab** [comment]
@guillaumefort thanks for the tip. Have configured that and it seems to work well. 

Two things : 
* it's a shame this attribute does not appear in the default configuration shipped with shinken. 
* I would argue that the default should be human_timestamp_log=1 because by default I think we should assume a shinken beginner user will not use another tool to process his logs programmaticaly. I agree that have a switch for this is useful but the "advanced" mode should be timestamp, and the "default" mode should be "human readable".

**Comment by olivierHa** [comment]
Hello,

Maybe it has changed, but this will break nagios compatibility. Some nagios
UIs are expecting timestamp.

Olivier

2015-12-01 10:55 GMT+01:00 Arthur Lutz <notifications@github.com>:

**Comment by naparuba** [comment]
I close. All you need is a simple log tool or just a perl command like this:
| perl -pe's/([(\d.)]+)/localtime $1/e;'

Breaking nagios UIs is not ok, so won't change this sorry.
