### ISSUE TITLE
Q: Alerting for dynamic hosts and resources 

### ISSUE THREAD

**Issue by activars** [naparuba/shinken#1769]
Hi, 

This is more of a question I hope you may have some ideas or direction I can look into. We have some mixed static servers in bare metal environment and dynamic hosts in the cloud. In the cloud environment, a lot of hosts are provisioned in mass on their own schedule and go away on another schedule. You would imagine we need some ways to tell shinken a new host is available and some existing host went away for good reason. 

A couple of ideas we have to make Shinken reactive to dynamic hosts alerts:
- Load configuration from MySQL database, an external process will make changes to configuration in DB
- If a live reload of shinken configuration can happen without downtime? (not the case right now)
- REST API to delete hosts if they are terminated (trashed)

All these ideas seem not really great. Have you had similar request from users? Could you suggest any other solutions may help resolving this type of workload?

**Comment by geektophe** [comment]
We have a similar need. An idea we had was to rely on service discovery system, such as consul, or something similar, that would keep track of down hosts for a given period of time before  considering it down. This way, you could trust the host list given by the auto discovery system, and use an Arbiter module to load hosts from it.

We did not have time to deeply study this solution, but it's a subject I have in mind.

I'll let you know if we have some working results.

**Comment by activars** [comment]
Do you have any example of Arbiter module that I can investigate further?

**Comment by mohierf** [comment]
I do not know if this may suit to your needs, but I use GLPI (http://glpi-project.org/) as an hosts/services configuration tool ... in some few words: 
 - GLPI manages assets as your hosts
 - when a new host is declared, GLPI sends a reload order to the shinken arbiter (thanks to shinken `ws-arbiter` module)
 - thanks to the Shinken `import-glpi` module, the arbiter reloads its configuration from the Glpi database

 This solution is interesting if you do not have too many hosts/services and too frequent updates in your configuration

**Comment by activars** [comment]
That might be something I can look into, we might be able to write extension on top of this code base.

Anther question might be related to this. A none-nrpe check has been defined, but service check has not been defined. I wonder if there are any methods to test a new service configuration via API, simply return the check result without adding it to the configuration?

Reason for asking this feature is that I would like our users to create alerts via some abstraction tools, we need a method to speed up the test & alert deploy cycle.

**Comment by geektophe** [comment]
Sorry for my late answer. You can define passive services, and push the check result externally through the receiver daemon. It may run the `ws_arbiter` module which provides a REST API allowing to publish passive check results.

**Comment by naparuba** [comment]
Off topic for gihub ticket and no news. Iff need please switch to forum instead :)
