### ISSUE TITLE
Sanitize information obtained from configuration (email addresses for example)

### ISSUE THREAD

**Issue by arthurlogilab** [naparuba/shinken#1770]
Trying to make the email notification work with shinken I was looking through the logs when I found this : 

```
/var/log/shinken/schedulerd.log:[1448960690] WARNING: [Shinken] The notification command '/var/lib/shinken/libexec/notify_by_email.py -n service -S smtp.logilab.fr -r none #email@example.org -f html -c "[snip]" raised an error (exit code=1): 'Traceback (most recent call last):'
```

Ignoring the fact that the information about the traceback is truncated making this line less useful that what it could be, I ticked on the presence of the "#" character here... 

I wanted to deactivate the email notification for a given user and so replaced 

```
        email                                   email@example.org
```
by
```
        email                                   none #email@example.org
```

Looking at the nagios documentation about the syntax of configuration files I realise that I should not use the pound key (#) but a semicolon instead to comment inline https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html but still... 

Maybe a little checking on things that then end up in nagios macros and in the end in ```command_line``` would be nice.

**Comment by geektophe** [comment]
I don't clearly understand what you mean in your last comment. What are your suggestions ?

**Comment by arthurlogilab** [comment]
I'm talking about input handling https://en.wikipedia.org/wiki/Secure_input_and_output_handling#Input_handling where shinken could check that the configuration (input) is correct.

**Comment by geektophe** [comment]
There is already a a bunch of checks to assert the configuration is correct syntactically, and that attributes are not set wrongly typed values.

Perhaps could it be more restrictive for some of them, but there's more chances that it creates new problems than it solves them.

To follow your example, imagine we enforce an email address format to follow the common pattern 'mailbox@domain'. If someone wants to use a local mail alias, or use the email address for another usage in one of its custom notification scripts, he's locked.

The Nagios/Shinken strength is its flexibility. In my opinion, it would be a heavy job to track down and maintain all the use cases for each attribute, and we'd loose the benefit to use the attributes as we want.

In this particular case, this is clearly a bug, and I'll fix it soon.

**Comment by naparuba** [comment]
# in nagios format is onlyfor a new line    ; is the format for ending line comments.
