### ISSUE TITLE
Issues after reloading shinken

### ISSUE THREAD

**Issue by syruis** [naparuba/shinken#1782]
[EN]
Dear everybody,

I have a issue, with shinken (lastest version), when i reload configuration "sometimes", i have duplicated services (the same services as twice), it's really randomize, and it's never the sames services. Sometimes i have output of services can be melted... 

A restart of shinken solves the problem.

Best Regards,
[FR]
Bonjour à tous,

J'ai des problèmes avec les reload de shinken certains services, jamais les mêmes et façon assez aléatoires ce déboublent. Parfois, certains restent à un ancien statut alors que le double lui change de statut... et des fois ils gardent le même status.

J'ai également des "output" qui ce mélangent.

Seul un redémarrage (de notre production!)  solutionne le problème.

Cordialement,

Tested on RHEL 6 and 7 64bits.

**Comment by X-dark** [comment]
This may be related to #1691

**Comment by olivierHa** [comment]
Quand tu redémarres pour régler le soucis,  c'est bien uniquement le broker
?

2016-01-13 12:23 GMT+01:00 Cedric Girard <notifications@github.com>:

**Comment by syruis** [comment]
Pour l'instant je redémarrais tout comme une brute.

**Comment by olivierHa** [comment]
Tu peux déjà ne redémarrer que le broker (la visu), ca ne coupera pas le
scheduling/alerting de ton infra de prod.

**Comment by X-dark** [comment]
This has been fixed by PR #1783. (At least we have not sen the issue again since @syruis applied the patch).

**Comment by naparuba** [comment]
Et hop on close :)
