### ISSUE TITLE
can't load sqlitedb

### ISSUE THREAD

**Issue by jbelafa** [naparuba/shinken#1790]
Hi I followed carefully this online course 
http://shinkenlab.io/online-course-2-webui/
and still I can't get to configure the dashboard. 

I have the following error . 
shinken  unknown sqlitedb module from webui

I noticed there was a couple of python modules created for each  shinken  plugins and the one for sqlite is preset and working ( as I can load it with a standalone python process)  

where else should I check to troubleshoot this ? 

Thanks

**Comment by mohierf** [comment]
This online course is quite outdated for the WebUI. You should have a look at: https://github.com/shinken-monitoring/mod-webui/wiki/Installation

**Comment by jbelafa** [comment]
Thanks ! 

I wasn't aware of webui2 . 

Keep it up #frenchtech
