### ISSUE TITLE
 $DOMAINPASSWORD$ need double quote around the password

### ISSUE THREAD

**Issue by Langlais115** [naparuba/shinken#1791]
Hi There,

I notice that the password  **$DOMAINPASSWORD$** need to be double quote to work properly.
Like so:
$DOMAINPASSWORD$=""superpassword""

If I don't, the authentication fail.

Can some one confirm that I'm not the only one having this problem?
And if I'm right, can we consider that as a bug?

Best regards.

**Comment by geektophe** [comment]
Do you have "special" characters in your password ($, \, ...) ?

**Comment by Langlais115** [comment]
yes

**Comment by naparuba** [comment]
It mainly depend on the plugin, like check_wmièplus.pl that is doing thing with perl etc etc. Shinken is respecting what user is putting, but plugins can change the behavior.
