### ISSUE TITLE
Shinken DeprecationWarning

### ISSUE THREAD

**Issue by Azef1** [naparuba/shinken#1793]
Hi,

When i start my shinken with `shinken-arbiter -d -c /etc/shinken/shinken.cfg` i have these errors:

>/var/lib/shinken/modules/livestatus/mapping.py:45: DeprecationWarning: shinken.schedulerlink is deprecated module path ; schedulerlink must now be imported from shinken.objects.schedulerlink ; please update your code accordingly
  from shinken.schedulerlink import SchedulerLink
/var/lib/shinken/modules/livestatus/mapping.py:46: DeprecationWarning: shinken.reactionnerlink is deprecated module path ; reactionnerlink must now be imported from shinken.objects.reactionnerlink ; please update your code accordingly
  from shinken.reactionnerlink import ReactionnerLink
/var/lib/shinken/modules/livestatus/mapping.py:47: DeprecationWarning: shinken.brokerlink is deprecated module path ; brokerlink must now be imported from shinken.objects.brokerlink ; please update your code accordingly
  from shinken.brokerlink import BrokerLink
/var/lib/shinken/modules/livestatus/mapping.py:48: DeprecationWarning: shinken.receiverlink is deprecated module path ; receiverlink must now be imported from shinken.objects.receiverlink ; please update your code accordingly
  from shinken.receiverlink import ReceiverLink
/var/lib/shinken/modules/livestatus/mapping.py:49: DeprecationWarning: shinken.pollerlink is deprecated module path ; pollerlink must now be imported from shinken.objects.pollerlink ; please update your code accordingly
  from shinken.pollerlink import PollerLink

But shinken start well

**Comment by geektophe** [comment]
Which livestatus version are you using ?

**Comment by Azef1** [comment]
I using livestatus 1.4.2 (https://github.com/shinken-monitoring/mod-livestatus/archive/1.4.2.zip)

**Comment by geektophe** [comment]
This ticket should be opened on https://github.com/shinken-monitoring/mod-livestatus for the module to be updated.

**Comment by Azef1** [comment]
ok thx i will open ticket on mod-livestatus
