### ISSUE TITLE
The scheduler got no broker in its realm or upper

### ISSUE THREAD

**Issue by ironashram** [naparuba/shinken#1797]
I'm getting this error on shinken service start, it was working before upgrading from 2.0.2 to 2.4.2.

root@dc01shinken01:~# cat  /etc/shinken/schedulers/dc01scheduler01.cfg 
define scheduler{
    scheduler_name      dc01scheduler01
    address             10.11.0.26
    port                7768        ; TCP port of the daemon
    ## Optional
    spare               0   ; 1 = is a spare, 0 = is not a spare
    weight              1   ; Some schedulers can manage more hosts than others
    timeout             3   ; Ping timeout
    data_timeout        120 ; Data send timeout
    max_check_attempts  3   ; If ping fails N or more, then the node is dead
    check_interval      60  ; Ping node every N seconds

    ## Interesting modules that can be used:
    # - pickle-retention-file     = Save data before exiting in flat-file
    # - MemcacheRetention   = Same, but in a MemCache server
    # - RedisRetention      = Same, but in a Redis server
    # - retention-mongodb    = Same, but in a MongoDB server
    # - NagiosRetention     = Read retention info from a Nagios retention file
    #                         (does not save, only read)
    # - SnmpBooster             = Snmp bulk polling module
    #modules   pickle-retention-file
    modules

    ## Advanced Features
    # Realm is for multi-datacenters
    realm               DC1

    # Skip initial broks creation. Boot fast, but some broker modules won't
    # work with it!
    skip_initial_broks  0

    # In NATted environments, you declare each satellite ip[:port] as seen by
    # *this* scheduler (if port not set, the port declared by satellite itself
    # is used)
    #satellitemap    poller-1=1.2.3.4:1772, reactionner-1=1.2.3.5:1773, ...

    # Enable https or not
    use_ssl               0
    # enable certificate/hostname check, will avoid man in the middle attacks
    hard_ssl_name_check   0
}

root@dc01shinken01:~# cat  /etc/shinken/brokers/broker-master.cfg 
define broker {
    broker_name     broker-master
    address         localhost
    port            7772
    spare           0

    ## Optional
    manage_arbiters     1   ; Take data from Arbiter. There should be only one
                            ; broker for the arbiter.
    manage_sub_realms   1   ; Does it take jobs from schedulers of sub-Realms?
    timeout             3   ; Ping timeout
    data_timeout        120 ; Data send timeout
    max_check_attempts  3   ; If ping fails N or more, then the node is dead
    check_interval      60  ; Ping node every N seconds

    ## Modules
    # Default: None
    # Interesting modules that can be used:
    # - simple-log              = just all logs into one file
    # - livestatus              = livestatus listener
    # - tondodb-mysql           = NDO DB support (deprecated)
    # - npcdmod                 = Use the PNP addon
    # - graphite                = Use a Graphite time series DB for perfdata
    # - webui                   = Shinken Web interface
    # - glpidb                  = Save data in GLPI MySQL database
    modules     livestatus,webui2

    # Enable https or not
    use_ssl               0
    # enable certificate/hostname check, will avoid man in the middle attacks
    hard_ssl_name_check   0
    
    ## Advanced
    realm   All
}

Any advice on this?

**Comment by olivierHa** [comment]
What are the definition of your realms ?
Did you specify "broker_complete_links        1" in your realm ?

**Comment by ironashram** [comment]
Thanks i was missing "broker_complete_links 1"
