### ISSUE TITLE
Macros does not work with timeperiods

### ISSUE THREAD

**Issue by syruis** [naparuba/shinken#1799]
Hi,

I just want to use a macro to set a different timeperiod per host in the services

I can use a macro to set the timeperiod, but when i do my config check :
> +1: [[91m[1452695317] ERROR: [Shinken] [service::xxxx/xxxx] The check_period of the service 'xxx' named '$_HOSTMAGASINPERIOD$'

it seems that macros aren't interpreted by shinken....

Example:
> define host{
> [..]
>          _MAGASINPERIOD longhours
> }
> define service{
>          hostgroup_name                  xx
>          service_description     xx
>         use generic-service
>          check_command           xx
>
>         check_period            $_HOSTMAGASINPERIOD$ ; <- does not work
>          check_period    workhours                                      ; <- works....
>          notes TEST MACRO $_HOSTMAGASINPERIOD$
>}
Regards,

[FR]
Le problème est assez simple j'aimerais "simplement", attribué une timeperiod vie une macro sur le host.

Cordialement,

**Comment by geektophe** [comment]
Macros are interpreted only on a subset of the attributes. This is not the case for timeperiods, which need to be linked to objects on configuration parse phase.

So what you describe is not possible with macros, unfortunately.

**Comment by syruis** [comment]
Well, does anybody know a solution, to have a different timeperiods per host/hostgroup?

If i haven't any solutions i have to create a service by period....

**Comment by geektophe** [comment]
A solution would be to define intermediate templates with the correct timeperiods, and use this template when defining hosts. This parameter being inherited from template, it will do what you want.

Example:

    # Templates
    define host {
        name workhours
        cehck_period workhours
        register 0
        ...
    }

    define host {
        name 24x7
        cehck_period 24x7
        register 0
        ...
    }


    # Only during workhours
    define host {
        host_name host-1
        use workhours,...
        ...
    }

    define host {
        host_name host-2
        use workhours,...
        ...
    }

    # 24x7
    define host {
        host_name host-3
        use 24x4,...
        ...
    }

    define host {
        host_name host-4
        use 24x4,...
        ...
    }

**Comment by syruis** [comment]
I don't want to define a different timeperiod for a host, but for a service!

I aready used templating, but the only solution is to create a specific template for this service and duplicate host name and timeperiod but it's not what i want.

**Comment by geektophe** [comment]
If you don't explicitly specify a timeperiod at service level (nor the service itself nor its upper level templates), it inherits the host timeperiod. I think it does what you want.

**Comment by syruis** [comment]
Hi,

if i change the period of my hosts, the hosts will be not check out of the period, it's not a solution.

I have 70 hosts for 70 shops, in a near future, all shop will have different "timeperiod" (somes open at night, or on sunday), just 10 services of 30 running only in the openning hours. So, the only solution i have today is to create 700 services (sic!). It's possible by scripting but it's a very "sad/bad" solution.
Today, shinken makes 5minutes to reloading configuration if i had 700 services i think, we can have 10/15 just to reloading configuration.... 

Regards,

**Comment by geektophe** [comment]
Another solution I may propose is to use `service_overrides`. This attribute is to be set on a host to overload a specific service attribute.

Example:

    define host {
    	host_name host-1
        use ...
        service_overrides HTTP,check_period workhours
        ...
    }

This will enforce the `check_period` attribute on the `HTTP` service attached to `host-1` host.

I think it's more what you want. Could you have a test with this ?

**Comment by syruis** [comment]
it seems like i search...

I have tested it but i don't how i can show if the directive work correctly.

Regards,
Thomas.

**Comment by geektophe** [comment]
You may have a look at the service configuration if you have a running thruk instance.

**Comment by syruis** [comment]
It seems working well in my testing env and in my production env...
Thanks for all,
Regards,
Thomas.

**Comment by geektophe** [comment]
You're welcome.
