### ISSUE TITLE
[shinken 2.2/2.4] HA configuration - spared scheduler/poller setup not working

### ISSUE THREAD

**Issue by Leryan** [naparuba/shinken#1807]
Hi, again (I hope you will not hate me :-) )

I have a question about shinken ability to correctly handle scheduler/poller spare systems.

Here is the setup:

![pic](https://cloud.githubusercontent.com/assets/4390126/12291090/830a097e-b9e5-11e5-9884-1ea5b4ed0340.png)

Take only one "silo" first. We have 3 machines:

 o First machine: Arbiter, Broker, Reactionner and Receiver
 o Second machine: Poller and Scheduler
 o Third machine: Spare Poller and Scheduler (for another realm, but anyway, we wil assume it is for our current realm)

_With_ spare poller and scheduler, it doesn't work: arbiter is constantly saying (in logs) that "Poller seems down, must redispatch it's configuration" bla bla bla.

On 5000 services, the poller/scheduler only do 255 of them, and it takes an awful amount of time.

_Without_ spare poller and scheduler, it works just fine! 5000 services checked in no time.

What's the problem with this setup? In arbiter's logfile, it correctly defferentiale Spare from Active poller/scheduler/whatever.

Thanks.

PS: can be related to #1798

**Comment by Leryan** [comment]
For information, I disabled all modules I used in the setup before trying to remove spare daemons.

**Comment by jfpik** [comment]
maybe you can set the poller in debug mode.
/etc/shinken/daemons/poller.ini 
  #log_level=WARNING
  log_level=DEBUG

Then have a look at the log file (/var/log/shinken/pollerd.log) if you see ERROR.
For us, we have had  "too many open files, because we have a very big configuration with more than 20.000 services per poller (yes it can !)
```
[1454427771] ERROR: [Shinken] NRPE poller exited with an unmanaged exception : Traceback (most recent call last):
  File "/var/lib/shinken/modules/booster-nrpe/module.py", line 515, in work
    self.do_work(s, returns_queue, c)
  File "/var/lib/shinken/modules/booster-nrpe/module.py", line 554, in do_work
    self.launch_new_checks()
  File "/var/lib/shinken/modules/booster-nrpe/module.py", line 453, in launch_new_checks
    n = NRPEAsyncClient(host, port, use_ssl, timeout, unknown_on_timeout, cmd)
  File "/var/lib/shinken/modules/booster-nrpe/module.py", line 188, in __init__
    self.create_socket(family, socket.SOCK_STREAM)
  File "/usr/lib64/python2.7/asyncore.py", line 297, in create_socket
  File "/usr/lib64/python2.7/socket.py", line 187, in __init__
error: [Errno 24] Too many open files
```

solution was to modify the system settings for allowed  opened files :+1: `
```
# less /etc/security/limits.d/nofile.conf 
# Default limit for user's max number of opened files

*          soft    nofile     1024
shinken    soft    nofile     8192
root       soft    nofile    16384
```
but you may have to modify the service start script too (shinken-poller.service, or default script depending on the os version kernel you use), to forced the value (ulimit -n 8192).

Hope it may help !

**Comment by Leryan** [comment]
Here it seems related to the nrpe booster that opens too many sockets, but in this setup, this module was disabled, for debugging purpose.

And if it was that problem, the normal setup (without spares) shouldn't work either since it would hit the limit by opening too many sockets.

**Comment by jfpik** [comment]
what is the configuration of the realm ?
realm ALL and BE DE & FR ?

should be
define realm {
    realm_name All
    realm_members BE, DE, FR 
    default 1
}

define realm {
    realm_name      BE
}
and so on ?

**Comment by Leryan** [comment]
And yep, this is the active realm configuration.
