### ISSUE TITLE
[Shinken 2.2] GLPI: instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'

### ISSUE THREAD

**Issue by vinnitino** [naparuba/shinken#1808]
Hello,

I'm running Shinken 2.2, Monitoring GLPI plugin (0.85+1.3) and Webservices (1.5.1), I have managed to configure Monitoring to create a components catalogue however I'm not getting any updates on checks, indeed it's stating "UNKNOWN" for "Host state" column. I can see that the connection between GLPI (monitoring) and Shinken is well established (via Webservices).
However, here are two interesting points I've noticed:

1) If I run 'shinken-arbiter -v -c /etc/shinken/shinken.cfg', here is the only error that I get: 

[1453804732] ERROR: [Shinken] Instance import-glpi raised an exception 'NoneType' object has no attribute 'monitoring'. Log and continue to run
[1453804732] ERROR: [Shinken] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.2-py2.7.egg/shinken/daemons/arbiterdaemon.py", line 343, in load_config_file
    r = inst.get_objects()
  File "/var/lib/shinken/modules/import-glpi/module.py", line 119, in get_objects
    all_commands = self.con.monitoring.shinkenCommands(arg)
AttributeError: 'NoneType' object has no attribute 'monitoring'

2) Moreover, here is the output of /var/www/glpi/files/_log/webservices.log:
AccÃ¨s refusÃ© (anonymous, ::1, glpi.doLogin, xml-rpc)
-->It looks like Webservices is trying to establish a connection via IPv6 so it fails forever (while I'm able to restart Shinken from Monitoring plugin, so this is strange), right ? If that's the case how to circumvent it ?
Please could you advise ? 
Big thanks for the support.

**Comment by mohierf** [comment]
Issue moved to https://github.com/shinken-monitoring/mod-import-glpi ... may be closed!
