### ISSUE TITLE
Documentation confusing for plugin output perfdata format/syntax ?

### ISSUE THREAD

**Issue by gst** [naparuba/shinken#1812]
I find the following shinken related docs, about the perfdata (and more specifically about multiple metrics within the perfdata), quite confusing (not to say totally) : 

1)  http://shinken.readthedocs.org/en/latest/15_development/pluginapi.html#development-pluginapi
@ "case 3: Multiple lines of output", we see this : 

```
DISK OK - free space: / 3326 MB (56%);"|"/=2643MB;5948;5958;0;5968/ 15272 MB (77%);/boot 68 MB (69%);/home 69357 MB (27%);/var/log 819 MB (84%);"|"/boot=68MB;88;93;0;98/home=69357MB;253404;253409;0;253414 /var/log=818MB;970;975;0;980
```

which already is not a multi-line. and where the perfdata are either semicolon separated (like **1**;_2_;**3**;_4_; :  **/=2643MB;5948;5958;0;5968/ 15272 MB (77%)**;_/boot 68 MB (69%)_;**/home 69357 MB (27%)**;_/var/log 819 MB (84%)_; ) or not at all (after the (also confusing) second "|" : **1**_2_**3** : **/boot=68MB;88;93;0;98**_/home=69357MB;253404;253409;0;253414_**/var/log=818MB;970;975;0;980** ).

and

2) http://shinken.readthedocs.org/en/latest/07_advanced/perfdata.html#plugin-performance-data
where we see:

```
PING ok - Packet loss = 0%, RTA = 0.80 ms | percent_packet_loss=0, rta=0.80
```

Here the 2 metrics (percent_packet_loss and rta) are coma(+ a space) separated.

**vs**

https://www.monitoring-plugins.org/doc/guidelines.html#AEN201 -> **notes 1**
or
http://docs.icinga.org/latest/en/perfdata.html#formatperfdata also **notes 1**

which states that the plugin perfdata must be **space separated**.

Am I missing something or do others agree that these docs (**1 + 2**) are really confusing about this perfdata format ?

At the end you are really not sure what to follows.. for not trivial perfdata cases..

**Comment by naparuba** [comment]
doc issue instead, shoudl be space, nothing else.
