### ISSUE TITLE
pnp4nagios setup

### ISSUE THREAD

**Issue by duanyihai** [naparuba/shinken#1827]
I have installed shinken 2.4.2 in the centos6,and I correctly install rrdtool and pnp6nagios0.6.25
next ,I setup module configure as shinken 2.4 document

define module{
     module_name       NPCDMOD
     module_type       npcdmod
     config_file       /usr/local/pnp4nagios/etc/npcd.cfg
}

define broker{
    broker_name      broker-1
    [...]
    modules          NPCDMOD
}

and I set process_perf_data to 1 in the shinken.cfg 
 the user and group of pnp4nagios is shinken but I don't install webui and thruk,

then I start shinken and npcd
service shinken start
service npcd start
when shinken is starting ,I can get the performance data but no rrd,

 it cann't find the module NPCDMOD in the broker.log

please help me ,I am a beginner

**Comment by duanyihai** [comment]
pnp4nagios has 5 modules 
1.Synchronous mode
2.Bulk mode
3.Bulk mode with NPCD
4.Bulk Mode with NPCD and npcdmod
5.Gearman mode

Integration With pnp4nagios ，I think shinken use the .Bulk Mode with NPCD and npcdmod of pnp4nagios ,but I am not sure.

**Comment by kh-git-hub** [comment]
In broker-master.cfg please try:

```
modules            npcdmod
```

If possible use livestatus, in broker-master.cfg append:

```
modules            livestatus,npcdmod
```

In /usr/local/pnp4nagios/etc/config_local.php:

...
$conf['livestatus_socket'] = "tcp:localhost:6557";
...

**Comment by duanyihai** [comment]
thank you 
I don't use livestatus.
if I want to use pnp4nagios ,do I have to use livestatus?

I haved used this in broker-master.cfg
modules            npcdmod
but cann't get rrd
