### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by nicodmf** [naparuba/shinken#1829]
Thanks for this good and beautiful project.

I want to use it, but i don't have time to search all the dependancies for my particuliar server. I think that the Shinken's power is not in the multi system installation, but more on the efficienceness of the supervision.

So the question is : Have you an official docker repository on docker HUB : https://hub.docker.com.

The docker system is simple and repetable. For me this would be the best choice, as the system is know and the same for all final users. 

Best Regards, 

Nicolas

**Comment by david-guenault** [comment]
No, no official docker container but some already did this. Just search on docker hub there are automated builds

**Comment by naparuba** [comment]
Docker is great, but not available everywhere for production, so currently upstream is only sources, and docker images are maintain by the communty :)

**Comment by nicodmf** [comment]
Maybe, this process isn't a shinken process, in fact i don't think that the php image is make by the php group but more that the docker and php team have links and communications which defined this result.

So to be clear, i think that to have an official image this is more social development than code writing. And as the docker team come from Paris, Shinken could be start with 10 points more.

**Comment by david-guenault** [comment]
from my point of view (and as a docker user for a long time), i agree with @nicodmf. But we have so much work pending around (shinken, packs, modules ...) that i don't think we have enough time to deal with this. But feel free to start a project like this and i will try to help on spare time ;-). But at the moment it will not be official and just friendly project. 

cheers ;-)

**Comment by airbinder** [comment]
Anyone can enlight or nudge us to right direction? Which docker image is good? Thanks.
