### ISSUE TITLE
Shinken Arbiter won't start

### ISSUE THREAD

**Issue by 3allai** [naparuba/shinken#1830]
Hello guys ,
i installed shinken and worked fine at first , but after editing " /etc/shinken/hosts/regularuserStation.cfg "file for snmp monitoring i couldn't start the shinken arbiter service . here's the error : 

################################
[35m[1459028172] INFO: [Shinken] Shinken 2.2[0m
[35m[1459028172] INFO: [Shinken] Copyright (c) 2009-2014:[0m
[35m[1459028172] INFO: [Shinken] Gabes Jean (naparuba@gmail.com)[0m
[35m[1459028172] INFO: [Shinken] Gerhard Lausser, Gerhard.Lausser@consol.de[0m
[35m[1459028172] INFO: [Shinken] Gregory Starck, g.starck@gmail.com[0m
[35m[1459028172] INFO: [Shinken] Hartmut Goebel, h.goebel@goebel-consult.de[0m
[35m[1459028172] INFO: [Shinken] License: AGPL[0m
[35m[1459028172] INFO: [Shinken] Loading configuration[0m
[35m[1459028172] INFO: [Shinken] [config] opening '/etc/shinken/shinken.cfg' configuration file[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_snmp_storage.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_host_alive.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-service-by-android-sms.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-host-by-xmpp.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_nrpe.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/restart-shinken.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_snmp_service.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/detailled-host-by-email.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_tcp.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/reload-shinken.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-service-by-email.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/detailled-service-by-email.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_snmp_time.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_dig.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/configuration-check.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-service-by-xmpp.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_ping.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/check_nrpe_args.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-host-by-email.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/commands/notify-host-by-android-sms.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/us-holidays.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/none.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/24x7.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/timeperiods/workhours.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/escalations/sample.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/dependencies/sample.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/templates/generic-service.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/templates/generic-contact.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/templates/generic-host.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/templates/srv-pnp.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/templates/time_templates.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/notificationways/email.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/notificationways/detailled-email.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/notificationways/sms-android.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/servicegroups/sample.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/hostgroups/linux.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/contactgroups/admins.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/contactgroups/users.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/hosts/localhost.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/hosts/regularStation.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/hosts/regularuserStation.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/services/services.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/contacts/admin.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/contacts/guest.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/readme.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/discovery.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/templates.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/commands.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/logFiles.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/cpu.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/time.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/load.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/disks.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/network_usage.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/packs/linux-snmp/services/memory.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/modules/sqlitedb.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/modules/sample.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/modules/auth_cfg_password.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/modules/webui.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/arbiters/arbiter-master.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/schedulers/scheduler-master.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/pollers/poller-master.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/reactionners/reactionner-master.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/reactionners/reactionner-android-sms.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/brokers/broker-master.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/receivers/receiver-master.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/realms/all.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/paths.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/snmp.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/active-directory.cfg'[0m
[35m[1459028172] INFO: [Shinken] Processing object config file '/etc/shinken/resource.d/nmap.cfg'[0m
[35m[1459028172] INFO: [Shinken] And arbiter is launched with the hostname:ShinkenManager from an arbiter point of view of addr:ShinkenManager[0m
[35m[1459028172] INFO: [Shinken] I am the master Arbiter: arbiter-master[0m
[35m[1459028172] INFO: [Shinken] My own modules: [0m
[35m[1459028172] INFO: [Shinken] Modules directory: /var/lib/shinken/modules[0m
[35m[1459028172] INFO: [Shinken] Modules directory: /var/lib/shinken/modules[0m
[35m[1459028172] INFO: [Shinken] I correctly loaded the modules: [][0m
[35m[1459028172] INFO: [Shinken] All: (in/potential) (schedulers:1) (pollers:1/1) (reactionners:1/1) (brokers:1/1) (receivers:1/1)[0m
[33m[1459028172] WARNING: [Shinken] The following parameter(s) are not currently managed.[0m
[35m[1459028172] INFO: [Shinken] enable_predictive_service_dependency_checks[0m
[35m[1459028172] INFO: [Shinken] host_perfdata_file_processing_interval[0m
[35m[1459028172] INFO: [Shinken] use_embedded_perl_implicitly[0m
[35m[1459028172] INFO: [Shinken] use_regexp_matching:  if you go some host or service definition like prod*, it will surely failed from now, sorry.[0m
[35m[1459028172] INFO: [Shinken] service_perfdata_file_processing_command[0m
[35m[1459028172] INFO: [Shinken] use_true_regexp_matching[0m
[35m[1459028172] INFO: [Shinken] enable_embedded_perl: It will surely never be managed, but it should not be useful with poller performances.[0m
[35m[1459028172] INFO: [Shinken] enable_predictive_host_dependency_checks[0m
[35m[1459028172] INFO: [Shinken] service_perfdata_file_processing_interval[0m
[35m[1459028172] INFO: [Shinken] host_perfdata_file_processing_command[0m
[35m[1459028172] INFO: [Shinken] passive_host_checks_are_soft[0m
[35m[1459028172] INFO: [Shinken] date_format[0m
[35m[1459028172] INFO: [Shinken] translate_passive_host_checks[0m
[35m[1459028172] INFO: [Shinken] auto_rescheduling_interval[0m
[35m[1459028172] INFO: [Shinken] soft_state_dependencies[0m
[35m[1459028172] INFO: [Shinken] auto_reschedule_checks[0m
[35m[1459028172] INFO: [Shinken] auto_rescheduling_window[0m
[33m[1459028172] WARNING: [Shinken] Unmanaged configuration statement, do you really need it? Ask for it on the developer mailinglist https://lists.sourceforge.net/lists/listinfo/shinken-devel or submit a pull request on the Shinken github [0m
[33m[1459028172] WARNING: [Shinken] The parameter status_update_interval is useless and can be removed from the configuration (Reason: This parameter is not longer take from the main file, but must be defined in the status_dat broker module instead. But Shinken will create you one if there are no present and use this parameter in it, so no worry.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retained_contact_service_attribute_mask is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter command_check_interval is useless and can be removed from the configuration (Reason: another value than look always the file is useless, so we fix it.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retained_process_service_attribute_mask is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter debug_verbosity is useless and can be removed from the configuration (Reason: This parameter is no longer useful in the Shinken architecture.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter max_check_result_file_age is useless and can be removed from the configuration (Reason: Shinken do not use flat file check resultfiles.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter sleep_time is useless and can be removed from the configuration (Reason: this deprecated option is useless in the shinken way of doing.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter bare_update_checks is useless and can be removed from the configuration (Reason: This parameter is no longer useful in the Shinken architecture.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter service_inter_check_delay_method is useless and can be removed from the configuration (Reason: This option is useless in the Shinken scheduling. The only way is the smart way.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter check_result_path is useless and can be removed from the configuration (Reason: Shinken use in memory returns, not check results on flat file.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter use_retained_program_state is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter free_child_process_memory is useless and can be removed from the configuration (Reason: this option is automatic in Python processes)[0m
[33m[1459028172] WARNING: [Shinken] The parameter check_for_updates is useless and can be removed from the configuration (Reason: network administrators will never allow such communication between server and the external world. Use your distribution packet manager to know if updates are available or go to the http://www.shinken-monitoring.org website instead.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter max_concurrent_checks is useless and can be removed from the configuration (Reason: Limiting the max concurrent checks is not helpful to got a good running monitoring server.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter use_large_installation_tweaks is useless and can be removed from the configuration (Reason: this option is deprecated because in shinken it is just an alias for enable_environment_macros=0)[0m
[33m[1459028172] WARNING: [Shinken] The parameter admin_pager is useless and can be removed from the configuration (Reason: sorry, not yet implemented.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retained_contact_host_attribute_mask is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter max_check_result_reaper_time is useless and can be removed from the configuration (Reason: Shinken do not use reaper process.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter event_broker_options is useless and can be removed from the configuration (Reason: event broker are replaced by modules with a real configuration template.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter debug_level is useless and can be removed from the configuration (Reason: This parameter is no longer useful in the Shinken architecture.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter object_cache_file is useless and can be removed from the configuration (Reason: This parameter is not longer take from the main file, but must be defined in the status_dat broker module instead. But Shinken will create you one if there are no present and use this parameter in it, so no worry.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retained_service_attribute_mask is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter child_processes_fork_twice is useless and can be removed from the configuration (Reason: fork twice is not use.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter use_retained_scheduling_info is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter debug_file is useless and can be removed from the configuration (Reason: This parameter is no longer useful in the Shinken architecture.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter temp_file is useless and can be removed from the configuration (Reason: Temporary files are not used in the shinken architecture. Skipping)[0m
[33m[1459028172] WARNING: [Shinken] The parameter host_inter_check_delay_method is useless and can be removed from the configuration (Reason: This option is unused in the Shinken scheduling because distribution of the initial check is a random one.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retained_process_host_attribute_mask is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter service_interleave_factor is useless and can be removed from the configuration (Reason: This option is useless in the Shinken scheduling because it use a random distribution for initial checks.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter admin_email is useless and can be removed from the configuration (Reason: sorry, not yet implemented.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retain_state_information is useless and can be removed from the configuration (Reason: sorry, retain state information will not be implemented because it is useless.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter external_command_buffer_slots is useless and can be removed from the configuration (Reason: We do not limit the external command slot.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter max_debug_file_size is useless and can be removed from the configuration (Reason: This parameter is no longer useful in the Shinken architecture.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter precached_object_file is useless and can be removed from the configuration (Reason: Shinken does not use precached_object_files. Skipping.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter check_result_reaper_frequency is useless and can be removed from the configuration (Reason: Shinken do not use reaper process.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter status_file is useless and can be removed from the configuration (Reason: This parameter is not longer take from the main file, but must be defined in the status_dat broker module instead. But Shinken will create you one if there are no present and use this parameter in it, so no worry.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter log_file is useless and can be removed from the configuration (Reason: This parameter is not longer take from the main file, but must be defined in the status_dat broker module instead. But Shinken will create you one if there are no present and use this parameter in it, so no worry.)[0m
[33m[1459028172] WARNING: [Shinken] The parameter retained_host_attribute_mask is useless and can be removed from the configuration (Reason: We do not think such an option is interesting to manage.)[0m
[35m[1459028172] INFO: [Shinken] Running pre-flight check on configuration data...[0m
[35m[1459028172] INFO: [Shinken] Checking global parameters...[0m
[35m[1459028172] INFO: [Shinken] Checking hosts...[0m
[31m[1459028172] ERROR: [Shinken] [host::UNNAMEDHOST] host_name property not set[0m
[31m[1459028172] ERROR: [Shinken] [host::UNNAMEDHOST] alias property not set[0m
[33m[1459028172] WARNING: [Shinken] [host::UNNAMEDHOST] Guessing the property host-name type because it is not in Host object properties[0m
[31m[1459028172] ERROR: [Shinken] [host::UNNAMEDHOST] a host item has been defined without host_name in /etc/shinken/hosts/regularStation.cfg:1[0m
[31m[1459028172] ERROR: [Shinken] [items] In UNNAMEDHOST is incorrect ; from /etc/shinken/hosts/regularStation.cfg:1[0m
[31m[1459028172] ERROR: [Shinken] [host::UNNAMEDHOST] host_name property not set[0m
[31m[1459028172] ERROR: [Shinken] [host::UNNAMEDHOST] alias property not set[0m
[33m[1459028172] WARNING: [Shinken] [host::UNNAMEDHOST] Guessing the property host-name type because it is not in Host object properties[0m
[31m[1459028172] ERROR: [Shinken] [host::UNNAMEDHOST] a host item has been defined without host_name in /etc/shinken/hosts/regularuserStation.cfg:1[0m
[31m[1459028172] ERROR: [Shinken] [items] In UNNAMEDHOST is incorrect ; from /etc/shinken/hosts/regularuserStation.cfg:1[0m
[31m[1459028172] ERROR: [Shinken] 	hosts conf incorrect!![0m
[35m[1459028172] INFO: [Shinken] 	Checked 3 hosts[0m
[35m[1459028172] INFO: [Shinken] Checking hostgroups...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 hostgroups[0m
[35m[1459028172] INFO: [Shinken] Checking contacts...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 2 contacts[0m
[35m[1459028172] INFO: [Shinken] Checking contactgroups...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 2 contactgroups[0m
[35m[1459028172] INFO: [Shinken] Checking notificationways...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 3 notificationways[0m
[35m[1459028172] INFO: [Shinken] Checking escalations...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 escalations[0m
[35m[1459028172] INFO: [Shinken] Checking services...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 services[0m
[35m[1459028172] INFO: [Shinken] Checking servicegroups...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 servicegroups[0m
[35m[1459028172] INFO: [Shinken] Checking timeperiods...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 4 timeperiods[0m
[35m[1459028172] INFO: [Shinken] Checking commands...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 30 commands[0m
[35m[1459028172] INFO: [Shinken] Checking hostsextinfo...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 hostsextinfo[0m
[35m[1459028172] INFO: [Shinken] Checking servicesextinfo...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 servicesextinfo[0m
[35m[1459028172] INFO: [Shinken] Checking checkmodulations...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 checkmodulations[0m
[35m[1459028172] INFO: [Shinken] Checking macromodulations...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 macromodulations[0m
[35m[1459028172] INFO: [Shinken] Checking servicedependencies...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 servicedependencies[0m
[35m[1459028172] INFO: [Shinken] Checking hostdependencies...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 hostdependencies[0m
[35m[1459028172] INFO: [Shinken] Checking arbiters...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 arbiters[0m
[35m[1459028172] INFO: [Shinken] Checking schedulers...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 schedulers[0m
[35m[1459028172] INFO: [Shinken] Checking reactionners...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 reactionners[0m
[35m[1459028172] INFO: [Shinken] Checking pollers...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 pollers[0m
[35m[1459028172] INFO: [Shinken] Checking brokers...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 brokers[0m
[35m[1459028172] INFO: [Shinken] Checking receivers...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 receivers[0m
[35m[1459028172] INFO: [Shinken] Checking resultmodulations...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 resultmodulations[0m
[35m[1459028172] INFO: [Shinken] Checking discoveryrules...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 1 discoveryrules[0m
[35m[1459028172] INFO: [Shinken] Checking discoveryruns...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 discoveryruns[0m
[35m[1459028172] INFO: [Shinken] Checking businessimpactmodulations...[0m
[35m[1459028172] INFO: [Shinken] 	Checked 0 businessimpactmodulations[0m
[35m[1459028172] INFO: [Shinken] Cutting the hosts and services into parts[0m
[35m[1459028172] INFO: [Shinken] Creating packs for realms[0m
[35m[1459028172] INFO: [Shinken] Number of hosts in the realm All: 3 (distributed in 3 linked packs)[0m
[35m[1459028172] INFO: [Shinken] Total number of hosts : 3[0m
[31m[1459028172] ERROR: [Shinken] Configuration is incorrect, sorry, I bail out[0m
Configuration is incorrect, sorry, I bail out
######################################

please what's wrong ? thank you :)

**Comment by 3allai** [comment]
no help ? :/

**Comment by olivierHa** [comment]
Hello

Just check the logs you have pasted... , there is an error your config
files.

Olivier

**Comment by naparuba** [comment]
Seems to be a configuration problem, I close.
