### ISSUE TITLE
Question: command log

### ISSUE THREAD

**Issue by nicodmf** [naparuba/shinken#1832]
Hello,

This is maybe a newbe question, but I demand me how can i log the poller command ? I try the to start the service whith debug flag, but nothing appears. 

For the little story, i want to test the network command check_netint.pl and to make a good test, i would like to know the command with the real used parameters.

Best Regards

**Comment by mohierf** [comment]
There is not log for the commands ... but you can easily append some in the `action.py` file ... as far as I remember ,there is a commented line strating with `logger.debug ...`

**Comment by david-guenault** [comment]
This is really easy to achieve. Use this plugin (http://www.waggy.at/nagios/capture_plugin.htm) and everything is logged in /tmp/captured-plugins.log

**Comment by naparuba** [comment]
Thanks David for the solution :)

**Comment by nicodmf** [comment]
Thanks a lot for your link
