### ISSUE TITLE
No more tags available in service objects

### ISSUE THREAD

**Issue by mohierf** [naparuba/shinken#1841]
Relating to this issue: https://github.com/shinken-monitoring/mod-webui/issues/492.

I investigated in the framework and I noticed that the Regenerator used by the WebUI broker did not built the tags property in the service objects. In the service initial brok, the broker receives an empty tags property in the brok ...

 I suspect that the templates / tags transformation in the objects does not take place correctly.

 I added some logs in the source code to track the tags for the services and I noticed that the specific service object `linkify_templates` function in the `service.py` file is not called on Shinken start ...

 **edit**: my bad ... this function is called but not as I supposed it should be :angry: 

**edit**: found !

**Comment by naparuba** [comment]
Merged :)
