### ISSUE TITLE
High check latency

### ISSUE THREAD

**Issue by KunX** [naparuba/shinken#1849]
I'm migrating a Nagios installation with 2000 hosts and 6000 services to Shinken, but with just half the hosts and services already configured in Shinken, I'm already experiencing an average latency of over 10 seconds, sometimes even getting to the 40 seconds mark, while Nagios remains under 2 seconds all the time. 
I currently have 2 pollers with the following hardware:

CPU: 12 CPU Cores (Xeon E5-2680 @ 2.70GHz)
Memory: 4Gb

The pollers sit between 4 and 6 of Load Average.

Is there anything I can do to try and solve this? I already tried increasing the check interval from 1 minute to 5, with little to no success.

I'm using Shinken 2.4.3

**Comment by hahahafr** [comment]
I have high latency and high execution_time as well (between 10 and 99+ seconds) on a 600 services and 90 hosts configuration.
Something strange is that the check_icmp is giving high response times as well until I restart the arbiter, then everything is normal including the latency and execution_time.

Here's an image of the check_icmp results before and after arbiter reload (same as restart apparently) :
![Image of the results of check_icmp before and after arbiter reload](http://i.imgur.com/Wp0XCo1.jpg)

I use Shinken 2.0.3 (on CentOS 6.7).

**Comment by hahahafr** [comment]
Rebooting doesn't solve the issue.

**Comment by hahahafr** [comment]
Quand le temps de réponse diminue, l'usage du CPU augment à 70-80%. Alors je sais pas si c'est volontaire ou pas ce bug en fait. Mais si c'est le cas, juste mettre une option save_cpu=1 ou save_cpu=0 serait cool.

**Comment by hahahafr** [comment]
**ping** d'un équipement en haut
**CPU** du serveur de supervision en bas
![high ping bug correlates with low CPU usage bug Shinken 2.0.3](http://i.imgur.com/ws9F88t.jpg)

**Comment by olivierHa** [comment]
Could you try with the latest version of Shinken ? or at least a 2.4.x ?

2016-05-20 9:34 GMT+02:00 Mika <notifications@github.com>:

**Comment by hahahafr** [comment]
It's shinken-arbiter stop & start ! not shinken-poller... shinken-poller stop & start doesn't change anything.

**Comment by hahahafr** [comment]
shinken-scheduler stop & start solve the issue as well.
I upgraded today, I'm waiting tomorrow to see if it remains fixed.

**Comment by hahahafr** [comment]
Something is wrong with the scheduler, the bug is still present and disappears with a scheduler stop & start  :
![bug with the scheduler Shinken 2.4.3 git master 20160523](http://i.imgur.com/El3IsD4.jpg)

**Comment by KunX** [comment]
It seems my problem with high check latency is caused by a memory leak on the scheduler after doing an arbiter reload. I solved it temporarily by adding a scheduler restart after every configurations deploy and arbiter reload.

**Comment by geektophe** [comment]
Hi, could you have a test with this PR (https://github.com/naparuba/shinken/pull/1828) by setting `max_q_size` to `1024` and `results_batch` to `2048` on poller and reactionners, and `broks_batch` to `2048` on the broker in the shinken configuration ?

**Comment by geektophe** [comment]
Any news about this issue ? Could you test the linked PR ?

**Comment by KunX** [comment]
Sorry @geektophe, I haven't had the time to test the PR yet. I'll try doing it this week and will give you feedback. Thank you.

**Comment by KunX** [comment]
@geektophe I tested my environment with your PR, but it breaks all my broker modules, making it impossible to test if there is any added stability.
```
[1472509007] CRITICAL: [broker-master] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/brokerdaemon.py", line 861, in main
    self.do_mainloop()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemon.py", line 413, in do_mainloop
    self.do_loop_turn()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/daemons/brokerdaemon.py", line 765, in do_loop_turn
    b.need_send_to_ext = False
AttributeError: 'int' object has no attribute 'need_send_to_ext'

[1472509007] ERROR: [broker-master] [graphite2] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/var/lib/shinken/modules/graphite2/module.py", line 373, in main
    b.prepare()
AttributeError: 'int' object has no attribute 'prepare'

[1472509009] ERROR: [broker-master] [livestatus] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.3-py2.7.egg/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/var/lib/shinken/modules/livestatus/module.py", line 242, in main
    self.do_main()
  File "/var/lib/shinken/modules/livestatus/module.py", line 281, in do_main
    self.main_thread_run()
  File "/var/lib/shinken/modules/livestatus/module.py", line 417, in main_thread_run
    b.prepare()  # Un-serialize the brok data
AttributeError: 'int' object has no attribute 'prepare'

```

**Comment by geektophe** [comment]
I'll have a look at that, thanks.

**Comment by geektophe** [comment]
- Which module version are you using ?
- How did you deploy the PR code ? (fresh install ?)

It's just to be sure. I'm using the livestatus module, and I don't have such an error.

**Comment by geektophe** [comment]
Could you also try to reset your retention data (if it's possible) ? This will give me clues on the origin of this error.

**Comment by KunX** [comment]
Hi, I tryed installing over my existing production shinken, so I could test it with the same kind of workload we run on a day-to-day basis. As it is a production system, it limits a little the actions I can perform, like resetting retention data. I'll try to setup a staging environment with the same configuration to test it out, but I don't know when I'll have the time.

**Comment by geektophe** [comment]
OK, keep me posted.

**Comment by geektophe** [comment]
@KunX did you have time to test a fresh install with my PR ?

**Comment by KunX** [comment]
I'll do it this weekend. Finished installing shinken on the staging servers, now I need to deploy the plugins and configurations and finish intalling the supporting services, like MySQL, Logstash, etc.

**Comment by KunX** [comment]
@geektophe The test with a fresh install and the same configurations and modules present in my production system worked without any problems. I don't know what is causing the problem on my production environment.

**Comment by geektophe** [comment]
Do you have a mean to force your test platform to load the retention data from the production platform ? I'd like to be sure the problem doesn't come from there.

**Comment by KunX** [comment]
I've tested with retention data and livestatus logs imported from production system, and it didn't generate any errors.

**Comment by geektophe** [comment]
Great. Could you tell me if you see some improvements with the parameters I gave higher ?

**Comment by KunX** [comment]
Yes,

there is definitely improvement on the memory leak, but I was never able to make it work on my production environment, even reinstalling completely, I keep getting those attribute errors.

**Comment by geektophe** [comment]
I'll try to identify the reason why it breaks. Did you try to flush the retention data on your production platform ?

**Comment by KunX** [comment]
Yes, I tried completely removing all retention data and shinken packages and reinstalling with your code, and the error still happened.

**Comment by KunX** [comment]
The fix by @geektophe was merged. Closing the issue.
