### ISSUE TITLE
check_icmp doesn't work after upgrade

### ISSUE THREAD

**Issue by hahahafr** [naparuba/shinken#1852]
from 2.0.3 to 2.4.3 git master 20160523
After using

`python setup.py install --upgrade`

check_icmp gives this error :

> Warning: This plugin must be either run as root or setuid root. 
>  To run as root, you can use a tool like sudo.
> To set the setuid permissions, use the command:
> chmod u+s yourpluginfile
> check_icmp: Failed to obtain ICMP socket: Operation not permitted

I did

```
# chown root:root /var/lib/shinken/libexec/check_icmp
# chmod 4000 /var/lib/shinken/libexec/check_icmp
# chmod uao+rwx /var/lib/shinken/libexec/check_icmp
```

then it worked again

**Comment by olivierHa** [comment]
Shinken  doesn't install "plugin"  like check_icmp. But python install "chown/mod" the libexec directory.
You should move the check_icmp elsewhere I think. I don't see a proper way to fix that.
Any ideas ?

**Comment by hahahafr** [comment]
Would it be possible to not modify the permissions of the libexec directory and its content when updating?
