### ISSUE TITLE
Shinken sends notification for host with notifications_enabled = 0

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [naparuba/shinken#1865]
Hello,

Today i've got notification that host is down. Normally it would be great, but the problem is that particular host have notifications_enabled = 0 set to 0.

Here is host definition:

```
define host {
    address                        IP
    alias                         ALIAS
    contact_groups                 adminonduty
    host_name                      HOST
    hostgroups                     Some hostgroups
    notifications_enabled          0
    use                            generic-host
}
```

Template **generic-host** is default, I didn't change it.

So first issue - notification was, sent but shouldn't.

Second problem - who received this notification. In my configuration we have contactgroup **adminonduty** which looks like this:

```
define contactgroup {
    contactgroup_name              adminonduty
    members                        tolszewski,monitor_bot
}
```

We rotate on-call admin every few days by changing member of adminonduty contactgroup, and then reload shinken arbiter (reload - not restart).

So who received notification? Me, Tomasz, and one of previous On-Calls admin (which is even not set in configuration).

So i see 2 problems here
- Notification for host was sent, but shouldn't be
- Notification was sent to all persons from current adminonduty contactgroup + previous member of adminonduty group set BEFORE shinken arbiter reload.

I'm using Shinken 2.4.3 (problem number 2 existed also previously).
Debian Jessie
Latest WebUI + monto retention

**Comment by geektophe** [comment]
I noticed a bug one time: I disabled notifications, and re-enabled them back, but they remained disabled. Dropping retention data fixed the issue.

Could you try to delete retention data on the schedulers ?

**Comment by TomaszUrugOlszewski** [comment]
Problem wasn't permanent. It fixed after shinken restart, or something similar.

**Comment by geektophe** [comment]
OK, great.
