### ISSUE TITLE
Notifcations not send for some hosts or services

### ISSUE THREAD

**Issue by Fall711** [naparuba/shinken#1873]
For some hosts or services notifications aren't send and i get this message in logs 

http://reho.st/view/self/f1a125f2c6d7a84da9a51bb3c27c9d5c8ecb83cd.png

When launched manually it appears that the error is related to notify_by_email.py script 

http://reho.st/view/self/931a6810ec5477b2322788b81202b694d0837ba5.png

Thanks

**Comment by geektophe** [comment]
There should be a missing parameter in the notification command line.

We have too few information to diagnose anything. Could you please give us a sample configuration with the the definition of the notification command an one of the hosts that did not notify ?

Which shinken release are you running ?

**Comment by Fall711** [comment]
Thank you geektophe.

I'm running version 2.4.3 of Shinken.

Notification command definition file :

[notify-host-by-email.txt](https://github.com/naparuba/shinken/files/519140/notify-host-by-email.txt)

One of the Host declaration file :

[antennes.txt](https://github.com/naparuba/shinken/files/519150/antennes.txt) 

If you need more please ask me !

Fall711

**Comment by geektophe** [comment]
I had a test with the following command line, and the notification was successfully sent.

    ./libexec/notify_by_email.py -n host -S localhost -r xxx@yyy.zzz -f html -c 'PROBLEM,,test-01,,test-01.test.com,,Sun 09 Oct 15:33:18 CEST 2016' -o 'UP,,00h 05m 31s'

Could you try the same command line and tell us if it works ?

- It it fails, could you please try with the latest script version from the shinken repository ?
- If it works, could you have a look at `shedulerd.log` file, look for a failed execution command line, and give it to us ?

Many thanks.

**Comment by Fall711** [comment]
Ok, so when i typed the command manually i've no errors like in your it works.

So i checked for error messages in shedulerd.log and found some related to notifications errors : 

[url=http://reho.st/view/self/7ad5c16b6c314c705e2322e0682bd098ffdfee00.png][img]http://reho.st/thumb/self/7ad5c16b6c314c705e2322e0682bd098ffdfee00.png[/img][/url]

Why does the scheduler time out ? We are running Shinken in a virtual environnement.

**Comment by geektophe** [comment]
The `notify_by_email.py` script execution times out after 30s.

The only blocking call is the SMTP server connection to send the email. I think you have a problem with it.

Perhaps did you configure a connection limit or rate threshold. Don't forget that each script execution establishes a new connection to your SMTP server. If there's many notification raised, you probably exhaust a limit.

**Comment by Fall711** [comment]
Ok, i wasn't sure if it was working properly, so i will check that. 

I found this other message in schedulerd log file : 

http://reho.st/view/self/33cbf45a141256bc11f176b9a23be76e7fe8d8d5.png

It look like it's the same as the first one.

Thanks :)

**Comment by k0ste** [comment]
@Fall711, you use "detailed" notifications, but your args for DETAILLEDDESC and IMPACT are empty.
Try to use "not detailed" command instead.

**Comment by Fall711** [comment]
Thanks, it seems that k0ste is right. 

I removed the setting in contact definition for sending detailled-email only... To me it was like if it is able to send a detailled email then it is able to send a non detailled one...

Maybe Shinken doesn't think like me.

Error message is clear now "Cannot concatenate str type with nonetype objects" because there is no DETAILLEDDESC and IMPACT.

Now, when i need a detailled email notification, will shinken send it ? I've setup one service check qui DETAILLEDDESC and IMPACT.

Glad to see it's not a bug but only a misconfiguration from me :)

**Comment by Fall711** [comment]
After a test there is no detailled notifications if you don't force it by adding notificationways detailled-email to the contact definition... If you do that like i did before openning this ticket, there is no notifications anymore. I tried to set DETAILLEDDESC and IMPACT on test host and on the service check definition like in read the doc but without changing the notificationways detailled-email i receive only simple notifications.

Maybe is there way to rewrite entirely or partially notify-by-mail.py to determine by itself whether it's a simple notification or not. Basically if DETAILLEDDESC or IMPACT is null use notifiy-host-by-mail command or notify-service-by-email else use detailled-host-by-email or detailled-service-by-email ?

If it's ok, do i need to create a new ticket for improovement or can i transform this one ?

Thanks a lot :)
