### ISSUE TITLE
No availability graphs on WebUI

### ISSUE THREAD

**Issue by ghost** [naparuba/shinken#1874]
Good morning everyone,

When i try to access to general availability graphs and also the one on specific host i don't get anything, no report, no graphs, nothing.

The thing i noticed is that when i go to a single host and access it's availability report on Chrome console i get this error.

![shinken](https://cloud.githubusercontent.com/assets/14274161/19233206/5a5fe460-8ee4-11e6-87b3-691b01c07b78.PNG)

What should i do? Thanks

**Comment by dabcoder** [comment]
Did you manage to solve this issue? Does `http://yourURL:7767/all` returns the same error?

**Comment by Revengeic3** [comment]
> Did you manage to solve this issue? Does http://yourURL:7767/all return the same error?

No i didn't solve the error, i have no clue on how to solve this. Also the error doesn't appear anymore so i think it wasn't related to the graphs problem.
