### ISSUE TITLE
duplicate_foreach not work with hostgroup_name

### ISSUE THREAD

**Issue by cyberflow** [naparuba/shinken#1877]
Hello.

Shinken==2.4.3
I have next definition for service:

```
define service {
  hostgroup_name                computes
  service_description           test: $KEY$-mount
  check_command               check_partition_mount_by_ssh!50!30!$VALUE$
  contact_groups                admins
  duplicate_foreach             _PARTITIONS
  register                      1
  use                           generic-services
}
```

and services not appears.

if i change it to:

```
define service {
  host_name                       compute1
  service_description           test: $KEY$-mount
  check_command               check_partition_mount_by_ssh!50!30!$VALUE$
  contact_groups                admins
  duplicate_foreach             _PARTITIONS
  register                      1
  use                           generic-services
}
```

it's work

It's bug or features?

Bit it's doesn't work for multi hosts if register 1. 
And how it's may look with template definitions?

**Comment by geektophe** [comment]
This is due to the fact that `duplicate_foreach` evaluation is done before the hostgroups are expanded into hosts.

I'll have a look at this and see if we can safely change the order the operations are done.

**Comment by geektophe** [comment]
Hi, sorry for the delay. This issue should be fixed by https://github.com/naparuba/shinken/pull/1905

Could you have a test  ?
