### ISSUE TITLE
Shinken forum down

### ISSUE THREAD

**Issue by jimbowarrior** [naparuba/shinken#1887]
Hello,

forum is down ...

**Comment by Alex85651** [comment]
The forum is now up but some news about the project would be great :D

**Comment by jimbowarrior** [comment]
maybe when http://shinkenlab.io/ will be up !!! we hope

2017-02-10 15:12 GMT+01:00 Alex85651 <notifications@github.com>:

**Comment by Jorilx** [comment]
Sorry to "hijack" this issue, but I've been trying to register on the Shinken forum for **months** but I'm still getting a "reCAPTCHA™ could not be verified due to server issues. Please try again later" error. Is it a problem on my end?

**Comment by dfranco** [comment]
Shinken forum is full of spam new thread.

I'd be glad to help in any way to clean up and improve spam protection.

Best regards

**Comment by Jorilx** [comment]
See #1860 :(

**Comment by dfranco** [comment]
Really sad :(

**Comment by Jorilx** [comment]
It looks like Naparuba is working on a new monitoring project, see [here](https://github.com/naparuba/shinken/issues/1930#issuecomment-329747077)

**Comment by dfranco** [comment]
Thanks @Jorilx 

I think this bug report can be closed.
