### ISSUE TITLE
Platofrm detection defines OS X as Windows

### ISSUE THREAD

**Issue by df-jetole** [naparuba/shinken#1899]
In setup.cfg (lines 272-338), the script uses sys.platform to detect the platform / OS. It uses the string `if 'win' in sys.platform` which also matches "darwin" for the platform. One possible alternative is to use the methods described with examples on the sys.platform documentation: https://docs.python.org/2/library/sys.html#sys.platform

**Comment by geektophe** [comment]
It would be even simpler to use `sys.platform.startswith('win')`

**Comment by df-jetole** [comment]
`sys.platform.lower().startswith('win')` (Just in case future changes and unusual environments) ?

**Comment by geektophe** [comment]
Let's fix this.

**Comment by geektophe** [comment]
Please note that installation on OS X won't be possible, as there's no section for `darwin`. I let people willing to install it on that platform do a pull request :)
