### ISSUE TITLE
duplicate_foreach with hostgroup

### ISSUE THREAD

**Issue by guillaume-u** [naparuba/shinken#1903]
Hello,

It seems not possible to define a service with "duplicate_foreach" with an hostgroup (and without a host).

Here is the configuration I want to test :
```
define host {
  host_name    linux-server
  use generic-host
  hostgroups +linux
  register 0
  _partitions   var $(/var)$, root $(/)$
}

define service{
  service_description     disk-$KEY$
  hostgroup_name linux
  check_command           check_disk!$VALUE$
  duplicate_foreach       _partitions
}
```

With this configuration, the arbiter, does not add disk-XXX services to hosts defined in linux hostgroup.
To work, I need to add a host_name like that :

**Comment by olivierHa** [comment]
Hello, 

I don't think it is possible, and it is not with the "shinken" logic.
Hostgroups mustn't be used in your case.

Use a template, and it will fine.

**Comment by guillaume-u** [comment]
You are right. Thanks a lot.

Guillaume.
