### ISSUE TITLE
Installing Shinken on Windows server

### ISSUE THREAD

**Issue by Yk-wim** [naparuba/shinken#1904]
Hi,

I need to do a school project about Shinken and I wanted to know if it's possible to install Shinken server on a windows server.

Best Wishes,
Yk-Wim

**Comment by Thibautg16** [comment]
Hi,

Some information in the doc : 
http://shinken.readthedocs.io/en/latest/02_gettingstarted/installations/shinken-installation.html#gettingstarted-installations-shinken-installation-windows-installation

It's an opportunity to do a nice documentation :)

Best
Thibaut
