### ISSUE TITLE
Error unknown module

### ISSUE THREAD

**Issue by CCoruble** [naparuba/shinken#1920]
Hello,

I know this error involve modules so this might not come from shinken itself but I do think it come from it.

Error:
[item::broker-master] Error: the module Livestatus is unknown for broker-master

Broker conf:
define broker {
    broker_name     broker-master
    address         localhost
    port            7772
    spare           0

    ## Optional
    manage_arbiters     1   ; Take data from Arbiter. There should be only one
                            ; broker for the arbiter.
    manage_sub_realms   1   ; Does it take jobs from schedulers of sub-Realms?
    timeout             3   ; Ping timeout
    data_timeout        120 ; Data send timeout
    max_check_attempts  3   ; If ping fails N or more, then the node is dead
    check_interval      60  ; Ping node every N seconds

    ## Modules
    # Default: None
    # Interesting modules that can be used:
    # - simple-log              = just all logs into one file
    # - livestatus              = livestatus listener
    # - tondodb-mysql           = NDO DB support (deprecated)
    # - npcdmod                 = Use the PNP addon
    # - graphite                = Use a Graphite time series DB for perfdata
    # - webui                   = Shinken Web interface
    # - glpidb                  = Save data in GLPI MySQL database
    modules Livestatus

    # Enable https or not
    use_ssl               0
    # enable certificate/hostname check, will avoid man in the middle attacks
    hard_ssl_name_check   0

    ## Advanced
    realm   All
}

The livestatus module is in the module directory aside webui auth-cfg-password ...

Here is my config file for livestatus : 
define module {
        module_name livestatus
        module_type livestatus
        host * ; * = listen on all configured IP addresses
        port 50000 ; port to listen
        #socket /usr/local/shinken/var/rw/live ; If a Unix socket is required
        ## Available modules:
        # - logstore-sqlite: send historical logs to a local sqlite database
        # - logstore-mongodb: send historical logs to a mongodb database
        # - logstore-null : send historical logs to a black hole
        modules logstore-sqlite
        #debug /tmp/ls.debug ; Enable only for debugging this module
        #debug_queries 0 ; Set to 1 to dump queries/replies too (very verbose)
}

I don't understand how the broker doesn't know the Livestatus module while he "recognize" and can use webui, auth-cfg-password and other modules ...
I believe this come from shinken and not the module so I posted this here.

Regards

**Comment by hvad** [comment]
Hi,

There is a spelling mistake Livestatus and livestatus...

Regards

**Comment by CCoruble** [comment]
Hi, 
well, thanks you ... 
I feel idiot right now but you solved it, might have been doing config files for too long so I was to tired to see it.

Regards
