### ISSUE TITLE
Python traceback debian 9

### ISSUE THREAD

**Issue by gizmo15** [naparuba/shinken#1921]
Hi,

I try to use shinken 2.4.2 on debian 9 (without systemd).
Python version: Python 2.7.13 (default, Jan 19 2017, 14:48:08)

scheduler-debug:
https://paste.swordarmor.fr/PZDO

poller-debug:
https://paste.swordarmor.fr/iKw3

reactionner-debug:
https://paste.swordarmor.fr/ZRBb

broker-debug:
https://paste.swordarmor.fr/MVFQ

receiver-debug:
https://paste.swordarmor.fr/2l5e

arbiter-debug:
https://paste.swordarmor.fr/iHDL

I installed the python module bottle manually (i don't use mongodb for now and ever).
i tried to update to 2.4.3 but i have the same behavior

Thanks

**Comment by geektophe** [comment]
Hello,

Sorry for the lag. It seems there's something wrong with the multiprocessing library, which is used in all the shinken modules. The manager process cannot communicate with the spawned slave process.

Isn't there some kind of firewall that could prevent it from communicating ?

Could you try this code snippet (from the multiprocessing module documentation) and tell us if it worked ?

    from multiprocessing import Process, Manager
    
    def f(d, l):
        d[1] = '1'
        d['2'] = 2
        d[0.25] = None
        l.reverse()
    
    if __name__ == '__main__':
        manager = Manager()
    
        d = manager.dict()
        l = manager.list(range(10))
    
        p = Process(target=f, args=(d, l))
        p.start()
        p.join()
    
        print d
        print l

**Comment by gizmo15** [comment]
Hi,

Sorry for the lag ^^

I don't have any more a debian 9 so i can't test :/
