### ISSUE TITLE
Check cherrypy version

### ISSUE THREAD

**Issue by efficks** [naparuba/shinken#1935]
It took me 3 days to figure out why the communication between the broker and the scheduler was not working after hours of checking the code.
The OS is Ubuntu 16.04. I figured out that the apt packaged names python-cherrypy is CherryPy version 2.x. Shinken needs CherryPy version 3+. So I need the packages names python-cherrypy3 and now everything works correctly.
I suggest to add cherrypy>=3 in the requirements.txt file to inform everybody you need at least version 3 and more. Also, It would be great to have a nice warning message when starting the HTTP daemon and falling back on the old HTTP backend.
Also, I suggest to remove completly the old HTTP server that does not use cherrypy at all.

**Comment by geektophe** [comment]
Thanks for the feedback !

I totally agree, at least enforcing the version number in the requirement file is so simple that there's no reason not to do it.

**Comment by dgilm** [comment]
Related: https://github.com/naparuba/shinken/pull/1983

I complete agree about warning the user about the use of an old and demo wsgi server...
