### ISSUE TITLE
Problèmes de notification

### ISSUE THREAD

**Issue by yoyox0123** [naparuba/shinken#1945]
_

> Bonjour, 
> 
> Je souhaiterai modifier les période de notification pour les hôte et service Windows
> J'ai donc modifié le fichier timeperiod/workhours.cfg pour le faire correspondre avec nos horaire de travail
> 
> Avant de vous donnez mon mode de fonctionnement, je vais essayer de comprendre le fonctionnement du système et je vais vous joindre mes fichiers de conf 
> 
> dans le dossier hosts, j'ai un fichier ou je met tout mes hote
> ![image](https://user-images.githubusercontent.com/29423744/38092587-f15a04ac-3368-11e8-9e49-6525a5105c06.png)
> 
> c'est hôtes on un templates contenant  les valeurs par défaut des variables que j'ai crée 
> ![image](https://user-images.githubusercontent.com/29423744/38092645-1de100e8-3369-11e8-87dc-9ad692ceb049.png)
> 
> Ne faite pas attention au guillemet fermante elle y est plus bas
> Pareil pour les services,
> ![image](https://user-images.githubusercontent.com/29423744/38092742-6269199e-3369-11e8-9b2c-f13c3a01f4fd.png)
> 
> il sont renvoyé sur un template service : 
> ![image](https://user-images.githubusercontent.com/29423744/38092782-7bd9b384-3369-11e8-8c85-14adf318b479.png)
> 
> Déjà je vais avoir l'air bête, cela fait longtemps que j'ai fait cela et récemment j'ai fait des modification et je me suis aperçu qu'il n'y avait aucun lien entre les services et les hôte et pourtant j'ai bien les service dans les hôte sur webUI
> ![image](https://user-images.githubusercontent.com/29423744/38092876-b505c53a-3369-11e8-9403-fa43081feaad.png)
> 
> Si quelqu'un peut me dire comment shinken fait la liaison pour regrouper toutes les info s'il vous plait ça serait cool, dois-je utiliser un USE windows-hote dans windows-service ?
> Test 1 : **Peut etre grace à  : _host_name               windows-hote_ du fichier services/windows-services.cfg**
> Reponse Test 1 : **Même en modifiant la ligne host_name du service CPU, en remplacent windows-hote par windows (du fichier services/windows-services.cfg) j'ai quand même accès au CPU de la machine dans WebUI, donc ce n'est pas host_name qui fait la liaison entre les deux template**
> 
> 
> La deuxieme question est que j'ai beaux modifier mes template pour changé le timeperiods en workhours mais rien ne se passe ??? pourquoi ?
> 
> ![image](https://user-images.githubusercontent.com/29423744/38092994-f6dc3a20-3369-11e8-8175-fb6bc7d64746.png)
> 
> est ce que j'ai fait une erreur et donc il by-pass mes paramètre ?
> 
> Merci pour votre aide, je continue de creuser de mon coté

_

J'ai résolu le problème, suite à des modifications j'ai oublier de changer les droit des fichier présent dans /etc/shinken/hosts

mais j'ai un second problème qui est en faite le principal de base

A mon boulot nous avons deux  services : un service réseau et un parc, je souhaitais donc différencier hôte réseau donc switch de hôte machine pour régler les plages horaires 

J'ai donc le problème du template generic-hote qui refuse que je change le contact_group admins et users par un autre contact groupe, si je le faite les élément n'apparaissent plus dans WebUI

pareil si je copie le template et que je le modifie, je souhaiterais donc savoir si vous auriez une solution car je ne trouve pas les explication du template dans la doc shinken

de plus j'ai remarqué un décalage horaire sur les remonter en workhours, les remonté arrivé à 9h alors que je les ai réglé sur 7h, j'ai vérifier, je suis à UTC + 2, je suis en France donc pourquoi le décalage de 2h ? 

Merci pour votre aide

**Comment by yoyox0123** [comment]
Je pense qu'il y a un problème, j'ai même enlevé la partie host_name et use du fichier services/windows-services.cfg et j'ai restart et ça ne ma pas fait apparaitre de message d'erreur et le service au quel j'ai enlevé c'est deux valeur affiche toujours l’état du service Oo, ca doit être la drogue que je prend... :)

**Comment by yoyox0123** [comment]
Je suis sur une piste, ayant mis les ancien fichier dans des dossier old il ne prenner pas les nouveau, du coup j'ai tout zip et virer les dossiers, mais la j'ai plus rien dans Webui de la nouvelle config je resoud les problème au fur et a mesure

**Comment by yoyox0123** [comment]
Ok je mis retrouve enfin, problème de droit sur les fichier dans le dossier hosts qui était en root

mais le plus gros problème c'est que apparemment je n'arrive pas a ne pas passer par un autre fichier que generic-host.cfg dans template sinon shinken me fait la misère ex: plus rien dans webui

quand je passe par generic-host.cfg et que j'ose modifier les contact_group pareil tout est vide dans le webUI mdr

Je vais regarder les pré-requis concernant c'est fichier en revanche vous pourrez me conseiller ?

En faite nous avons deux pole réseau et machine, je souhaiterai c'est des template service et hosts pour chaque filière comment puis-je faire a par en créant deux fichiers template host différent du generic ?

Merci

**Comment by yoyox0123** [comment]
Je ne trouve pas les template dans shinken read docs, peut être que sa n'utilise pas le nom template ?

**Comment by yoyox0123** [comment]
J'ai réussi à dupliquer le template generique-host et à le modifier mais : 
Je suis obligé de laisser au minimum dans contact_group, admins
Y à t-il une raison à cela ?

Problème restant : le décalage horaire ?

**Comment by hvad** [comment]
Bonjour,
Ceci n'est pas un forum et tu devrais lire la documentation avant de te lancer dans un produit que tu ne connais pas.
Cordialement

**Comment by yoyox0123** [comment]
Merci c'est gentil comme conseil, j'ai rechercher dans la doc la partie sur les template en vain, je pense avoir acquis pas mal de connaissance sur le produit au fils du temps et pour finir a quoi sa sert que tu consomme de l'espace disque si ce n'est pour dire ce genre de chose

ca aurait été plus utile de me fournir un lien pour que je puisse continuer mes recherches non ?
en tout cas merci pour ton aide elle n'était pas précieuse :)

**Comment by yoyox0123** [comment]
pourtant je suis bien dans la partie "issue", si cela te gène de m'aider nul besoin de répondre :) 
tu dois être omniscient pour savoir si je connais ou non le produits, je suis peut être pas aussi expérimenté que toi qui d’ailleurs ne ma pas fourni de solution mais au moins je cherche c'est pour cela que la plus part du temps je résout le problème moi même, pourquoi posté des messages alors ? pour aider les prochains qui aurait fait la même erreur sa s’appelle du partage ça existe aussi dans les bibliothèque

cordialement

**Comment by yoyox0123** [comment]
j'ai simplifié mon problème, peut être que tu aurais un lien a me fournir pour la partie template dans la docs ?

Merci
