### ISSUE TITLE
domain shinken.io expiré

### ISSUE THREAD

**Issue by xila76** [naparuba/shinken#1947]
Comment peut-on utiliser "shinken install webui2" si shinken.io n'a pas été renouvelé ?
Est-il prévu de renouveler ? est-ce que le projet shinken est toujours maintenu et continuera d'être développer ?

`
\# shinken install webui2
Grabbing : webui2
[1525955415] ERROR: [Shinken] There was a critical error : (6, 'Could not resolve host: shinken.io')
`

`# ping shinken.io
ping: shinken.io: Nom ou service inconnu
`

> Domain Name: SHINKEN.IO
> Registry Domain ID: D503300000040631291-LRMS
> Registrar WHOIS Server:
> Registrar URL: https://www.gandi.net/whois
> Updated Date: 2018-05-10T10:32:29Z
> Creation Date: 2013-05-10T12:30:01Z
> Registry Expiry Date: 2018-05-10T12:30:01Z

**Comment by starpeak** [comment]
Ran into the same problem today :(

**Comment by geektophe** [comment]
The shinken.io domain has been renewed. Sorry for the inconvenience.

**Comment by vaxvms** [comment]
shinken.io is back online, i'm closing

**Comment by NicoAdrian** [comment]
Domain expired again :(
