### ISSUE TITLE
Impossible d'accéder à shinken.io

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1948]
Bonjour,
Je voudrais savoir quand est ce que le domaine shinken.io sera remise en fonction.
Merci

**Comment by naparuba** [comment]
C'est en cours, j'ai raté la date d’expiration du domaine, je pensais que gandi me préviendrais, faut croire que non ^^

C'est l'occasion de tester le check d'expiration DNS alors ^^

**Comment by naparuba** [comment]
http://www.shinken.io/ est de retour, http://shinken.io/ (alias DNS) ne devrait pas tarder je pense.

**Comment by naparuba** [comment]
ok le temps d'écrire il est de retour (je suis chez orage).

Je clôt le ticket, encore merci de l'info ^^
