### ISSUE TITLE
Erreur de type [1526288879] ERROR : [shinken] There was a critical error : 

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1949]
Boujour voici mon erreur quand je veux installer une clé ssh pour commencer une supervision de mon locale host.  

]$ shinken search linux
 [1525955415] ERROR: [Shinken] There was a critical error : (6, 'Could not resolve host: shinken.io ; Name or service not known ' )
Pareille quand je voudrais installer webui.
Merci de bien vouloir m'aider à résoudre mon problème svp.
Merci.

**Comment by geektophe** [comment]
D'après le message, il s'agit d'un problème de résolution de noms.

Est-ce que la résolution de shinken.io fonctionne depuis la ligne de commande ?

`$ dig shinken.io`

**Comment by geektophe** [comment]
Il semblerait que le domaine shinken.io ait expiré. Il a été renouvelé. Tout devrait fonctionner à nouveau normalement.

Désolé pour le dérangement.
