### ISSUE TITLE
Webui

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1950]
Bonjour,
après avoir modifier le fichier broker-master.cfg comment avoir accès l'interface shinken dans le navigateur (webui).
Merci.

**Comment by geektophe** [comment]
Le port sur lequel elle écoute doit être spécifié par un paramètre de configuration. Sinon, le port standard devrait être le `7767`.

**Comment by hvad** [comment]
https://www.howtoforge.com/tutorial/server-monitoring-with-shinken-on-ubuntu-16-04/
