### ISSUE TITLE
Email notification in text mode

### ISSUE THREAD

**Issue by gizmo15** [naparuba/shinken#1951]
Hi,

Juste to give you the information, i change the notification mail type from html to txt and in this case, the mime type is incorrect :
`[-- text/text is unsupported (use 'v' to view this part) --]`

I juste change this line :
`msgText = MIMEText(txt_content, 'text')`

to

`msgText = MIMEText(txt_content, 'plain')`

And it's work perfectly!

It's with Shinken 2.4.2.

Thanks for the work ;)

**Comment by geektophe** [comment]
Thanks for the feedback ! We'll update the script.
