### ISSUE TITLE
Installation de shinken et ces modules sans internet 

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1955]
Bonjour je voudrais savoir est-il possible d'installer shinken et ses modules sans internet.
Si oui peut-on installer comment?
sans installer les modules de shinken un par un manuellement serai t'-il possible d'installer toutes ses modules  de manière automatique sans internet
Merci.

**Comment by hvad** [comment]
Oui et merci de ne pas ouvrir de bug pour ça et plutôt de voir soit sur irc, doc ou forum.
