### ISSUE TITLE
Mot de passe invalide

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1957]
Bonjour,
j'ai installer shinken et le module webUI2
J'arrive pas à me loger avec le mot de passe et le contact name par défaut.
il m'affiche mot de passe et user name incorrect.
J'ai vérifier la configuration de shinken et j'ai trouver cette erreur
[1528183376] ERROR: [Shinken] [module] unknown Apache_passwd module from webui2

**Comment by olivierHa** [comment]
Sorry this isn't a shinken issue.
Check your config file and the passwd file
