### ISSUE TITLE
After 10 Minute Installation WebUI missing (and forums dead)

### ISSUE THREAD

**Issue by bernd-wechner** [naparuba/shinken#1958]
I posted this on the now seemingly dead forums and was advised to go with a github issue instead (as the forums are dead it seems). Here is what I wrote:

OK, total noob here, but some feedback on the docs I guess and maybe a request for a pointer:

1) Looks like Shinken is written in Python2. Fine, but as a product nearing its end of life ([2020](https://pythonclock.org/)) I'm confident a Python3 transition is planned? But even if not, it's certainly time on the [10 minute install guide](https://shinken.readthedocs.io/en/latest/02_gettingstarted/installations/shinken-installation.html#gettingstarted-installations-shinken-installation) stopped reading "Python 2.6 or higher" as I wasted time on account of fact that pip is python3 by default now and I had to use pip2. Not crisis, but worth keeping clear for noobs who think python=python3 (guilty as charged here ;-).

2) [Use Shinken with ...](https://shinken.readthedocs.io/en/latest/11_integration/use-shinken-with.html) states that "If you install Shinken using the 10 minutes installation recommended method, you will have the Shinken WebUI installed.", great. But I did that and it's not. Well if it is I can't see it and there is not tip there on how to use it. So I go to [Use Shinken with WebUI](https://shinken.readthedocs.io/en/latest/11_integration/webui.html) and alas I'm none the wiser. It doesn't tell me much that I can digest quickly, but does give me a tip that "Enable the webui module in ‘’modules/webui.cfg’’ configuration file" yet there is not webui.cfg file to found anywhere on my system after the 10minute install (method 1 using pip). Still there's a clue that it serves on port 7767 so a quick check:

```
$ sudo netstat -tulpe | grep shinken
tcp        0      0 localhost:46068         *:*                     LISTEN      shinken    13734645    21116/python2.7 
tcp        0      0 localhost:42549         *:*                     LISTEN      shinken    13734735    21296/python2.7 
tcp        0      0 *:7768                  *:*                     LISTEN      shinken    13742757    20851/python2.7 
tcp        0      0 *:7769                  *:*                     LISTEN      shinken    13739812    21115/python2.7 
tcp        0      0 *:7771                  *:*                     LISTEN      shinken    13745166    21003/python2.7 
tcp        0      0 *:7772                  *:*                     LISTEN      shinken    13739845    21212/python2.7 
tcp        0      0 *:7773                  *:*                     LISTEN      shinken    13739908    21295/python2.7 
tcp        0      0 localhost:40222         *:*                     LISTEN      shinken    13742987    21213/python2.7 
tcp        0      0 localhost:41900         *:*                     LISTEN      shinken    13743434    20853/python2.7
```

reveals nothing's listening on 7767 yet Shinken is listening elsewhere. Yet:

- http://localhost:46068/   returns nothing
- http://localhost:42549/   returns nothing
- http://localhost:7768/   returns "OK" - neat but not a WebUI
- http://localhost:7769/   returns "OK" - neat but not a WebUI
- http://localhost:7771/   returns "OK" - neat but not a WebUI
- http://localhost:7772/   returns "OK" - neat but not a WebUI
- http://localhost:40222/   returns nothing
- http://localhost:41900/   returns nothing

So it's not secretly there listening on another port so a fair assumption is it's not installed.

Anyhow I guess I'm stuck and wondering why the I don't have a webui.cfg to work with when reading [how to use the WebUI](https://shinken.readthedocs.io/en/latest/11_integration/webui.html).

That's today's noob conundrum for anyone happy to point one in the right direction and/or consider fixing the docs (which I'm happy to do if I learn enough to qualify for that task).

Originally posted here:
http://forum.shinken-monitoring.org/threads/15081-WebUI-missing

**Comment by naparuba** [comment]
Hi,

For 1: will be possible, but will ask time. I alrady did in another project (opsbro) and it's quite possible to have 2.6, 2.7 and 3 with the same code. But even if we drop 2.6 (why not, its quite old now), the main issue is performance drop if we want to have 2.7 and 3 (because of more function call to manage the differences). But should be ok, and the main question is: should we make 2.7 slower or the 3.X? ^^

Another problem we will face are the modules, we should change all of them for this, and there are lot of them ^^


For 2:
This part of the documentation is outdated, I will change it to a link to the tutorials (http://shinkenlab.io/tag/online-course.html) will be better :)

**Comment by bernd-wechner** [comment]
Thanks. The on-line course is excellent!

Re: Python 3, inevitable necessity I think. Personally I would not worry too much about maintaining Python 2 compatibility/ I really don't know which environments have python 2 and not 3 anymore given EOL (end of life) for python 2 is 2020, and they may as well be stuck with an old Shinken as well if they are stuck with an old python. Guess I'm just progressive by nature. The conversion can be time consuming alas I know, but is future looking ...
