### ISSUE TITLE
Shinken and python3

### ISSUE THREAD

**Issue by hvad** [naparuba/shinken#1962]
Hi,

Make shinken compatible python 3.

Best regard

**Comment by vaxvms** [comment]
Which version of python 3 ? 
- EPEL support 3.4 for RHEL 6 and 3.6 for RHEL 7. 
- RHEL 8 will have python 3 but i can't find the specific version.
- Ubuntu 18.04 LTS have 3.6 by default and 3.7 as an option

Can't we start by deprecating python 2.6 and make a shinken 2.5 release with it and all bugfixes lying in PR ?

alignak seems to have a patchset for python 3. Maybe there is good bits to borrow

**Comment by hvad** [comment]
3.6 seem be the best option...

**Comment by tanertas** [comment]
Python 2.7 will be history in [January,1 2020](https://github.com/python/devguide/pull/344). I guess this have to be really considered. @naparuba

**Comment by bernd-wechner** [comment]
> Python 2.7 will be history in [January,1 2020](https://github.com/python/devguide/pull/344). I guess this have to be really considered. @naparuba

I think it a priority to be python 3.6 compatible indeed, but this is all the same unnecessarily alarmist. Python 2.7 will cease to be maintained (improved or fixed) after then and it (presumably) won't be delivered preinstalled on any distros out there shortly thereafter too if not already. But it won't stop working overnight, in fact it might keep working for decade hence! Heck I'm still using a 32bit Java app that died over a decade ago (was taken from the market, hasn't had a line of code touched etc). and I'm pretty sure there'll be (lamentably) Python2 apps still in service a decade hence.

I don't think Shinken wants to be one of them though!

**Comment by danirod** [comment]
My two cents: some people are going to be bitter at the stats for PyPI on January 2020. Don't just expect that the usage percentage for Python 2 will simply drop to 0% in the night from 2020-01-01 to 2020-01-02.

Not even taking into account long term Linux distros that still provide Python 2 and that are still supported after 2020-01-01. I cannot predict the future, but if a security vulnerability on Python 2 is disclosed after 2020-01-01, my bet is that supported Linux distros that ship with Python 2 will find a way to have the vulnerability patched.

__Said that__, it's not just about Shinken; it's about dependencies. You can decide your project to stay on Python 2.7, but you will probably cannot control your dependencies, which may drop support for Python 2.7. Unless you pin them, but then you have to care about your dependencies' dependencies, which may not be trivial.

**Comment by jgwinner** [comment]
And here we are a significant fraction of a decade later ...

Any chance of Python 3 being revisited? We really have to.

https://python3statement.org/practicalities/

**Comment by geektophe** [comment]
Hello,

I've started to work on this, but there's quite a bit of work, and I've not so much spare times these days. But I agree, it's an absolute requirement we'll have to tackle.
