### ISSUE TITLE
check_snmp_load.pl et interrogation CPU linux

### ISSUE THREAD

**Issue by yoyox0123** [naparuba/shinken#1963]
Bonjour, 

J'ai fais pas mal de recherche sur mon problème mais soit je ne pose pas la bonne question soit j'ai lu entre les lignes

J'ai un petit problème concernant la remonté d'information CPU avec ce plugin, il fonctionne nikel sous Windows mais sous Linux je me retrouve avec cela : Numeric value for warning or critical !

Voici toute les information et test que j'ai effectué

Si je prend le plugin et que je le test sur un serveur linux j'ai bien un retour possitif : 
![image](https://user-images.githubusercontent.com/29423744/43313794-65845202-9191-11e8-894c-4f0f52f06875.png)

La commande en question une fois dans /var/lib/shinken/libexec : 
./check_snmp_load.pl -H 192.168.4.104 -C public -f -w 80 -c 90

je fonctionne par template,c'est a dire que tout mes parametre avec variable si situe dans /etc/shinken/templates/montemplate.cfg

![image](https://user-images.githubusercontent.com/29423744/43313925-b0ada58a-9191-11e8-88dc-f43a24c50dd6.png)

je n'ai pas tout mis mais pour la memoire et disk ca fonctionne

voici ce que j'ai dans /etc/shinken/services/monservice.cfg
![image](https://user-images.githubusercontent.com/29423744/43313977-d830b46c-9191-11e8-9783-f33f6e74e227.png)
 
/etc/shinken/hosts/monhote.cfg

![image](https://user-images.githubusercontent.com/29423744/43314095-2f6701dc-9192-11e8-871d-528a56d03b3c.png)

/etc/shinken/commands/monfichiercmd.cfg

![image](https://user-images.githubusercontent.com/29423744/43314226-9e428360-9192-11e8-9352-6a94ac5fa6e7.png)

Je continue mes test et vous tient informé

 Ce qui ne va pas c'est que les même commande dans un autre template pour windows ca fonctionne
comme je vous les montré quand je fais la commande en manuelle ca fonctionne et le resultat et sous le même format sous windows et linux

Si je comprend bien le problème, c'est que le format récupérer n'est pas le bon,
j'ai test en mettant l'option -T avec netsc et netsl sans résultat
 avec plusieur valeur de warning et critical non fonctionnel
j'ai essayé de mettre les valeur warning et critical en pourcentage mais j'ai le même message

Merci pour l'aide

Si quelqu'un pourrait me dire comment voir dans les log en modifiant la verbosité par exemple ce que récupère shinken et pourquoi il pense qu'il y a un problème, ca serait cool merci

**Comment by hvad** [comment]
Bonjour,

Ici ce n'est pas un forum et déjà dit. Mais pour répondre à ta question la load  (https://fr.wikipedia.org/wiki/Load_average) a des seuils à 1,5 et 15 minutes pour Linux. 
Donc si tu utilise netsl (valeur par défaut du plugin) le seuil warning doit être de la forme 2,3,4 et critical 4,5,6. 

Pour plus de détail la documentation d'utilisation du plugin est ici http://nagios.manubulon.com/snmp_load.html 

Cordialement

**Comment by yoyox0123** [comment]
Merci hvad, je vais regarder cela,
