### ISSUE TITLE
[Shinken] Could not import bare 'module.py' from /var/lib/shinken/modules/elastic-logs : No module named elasticsearch

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1964]
hi,
I need your help to fix my problem so i use shinken and ELK stack to make my monitoring
I install elastic-logs to store shinken logs in elasticsearch
so I don't have nothings logs  in elasticsearch
I have this probleme
[Shinken] Could not import bare 'module.py' from /var/lib/shinken/modules/elastic-logs : No module named elasticsearch
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Shinken-2.4.3-py2.7.egg/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/shinken/modules/elastic-logs/module.py", line 40, in <module>
    from elasticsearch import Elasticsearch,helpers,ElasticsearchException,TransportError
ImportError: No module named elasticsearch

Thank you for your help

**Comment by s-dewailly** [comment]
Hi,


Is python module "elasticsearch" installed ?

To check, you can try to import it in a python prompt.

To install it :

  pip install elasticsearch


	
Serge Dewailly

Le 02/08/2018 à 15:28, m2cci-KGY a écrit :

**Comment by m2cci-KGY** [comment]
Yes I installed elasticsearch-py with the sources 
I don't use pip because my serveur doesn't have internet access

**Comment by naparuba** [comment]
It's a issue related to the elk module, not the framework.
