### ISSUE TITLE
Demande SVP

### ISSUE THREAD

**Issue by m2cci-KGY** [naparuba/shinken#1965]
Bonjour,
Je sais que vous ne jouez pas le rôle de support mais j'ai un problème avec elasticsearch 
- J'ai installé shinken le moteur il marche bien, j'ai installé elasticsearch et kibana qui marche bien 
- J'ai installé le module elastic-logs qui pour rôle d'intercepter les journaux Shinken et analyser chaque journal pour le stocker dans ElasticSearch. Les journaux sont alors disponibles pour une application telle que Kibana.
- J'ai installé elasticsearch-curator et ses pré-réquis (elasticsearch-py et autres)
Mon problème j'arrive pas à alimenter la base elasticsearch
De plus quand je consulte la config de shinken j'ai ce problème : 
[1533281494] ERROR: [Shinken] Could not import bare 'module.py' from /var/lib/shinken/modules/elastic-logs : No module named elasticsearch
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Shinken-2.4.3-py2.7.egg/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/shinken/modules/elastic-logs/module.py", line 40, in <module>
    from elasticsearch import Elasticsearch,helpers,ElasticsearchException,TransportError
ImportError: No module named elasticsearch

Merci pour vos explications et vos solutions.

**Comment by vaxvms** [comment]
Avez vous essayé d'importer le module dans un interpreteur python :

Si vous avez ce resultat, c'est qu'il est bien installé :

```
~/shinken/shinken/test$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elasticsearch
>>> print elasticsearch.__version__
(6, 3, 0)
```

Si vous avez ce résultat, c'est qu'il est mal installé :

```
~/shinken/shinken/test$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elasticsearch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named elasticsearch
```

**Comment by m2cci-KGY** [comment]
Bonjour,
Quand je lance la commande j'ai ce résultat :
 ~/shinken/shinken/test$ python
-bash: /home/shinken/shinken/shinken/test$: No such file or directory

**Comment by vaxvms** [comment]
La partie "~/shinken/shinken/test$" correspond au prompt

il faut seulement saisir "python"

**Comment by m2cci-KGY** [comment]
~]$ python
Python 2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elasticsearch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named elasticsearch

**Comment by m2cci-KGY** [comment]
[.......... ~]$ python
Python 2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elasticsearch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named elasticsearch

**Comment by m2cci-KGY** [comment]
SVP c'est le quel des modules ? :
elasticsearch-6.3.0.rpm
elasticsearch-curator-5.5.4-1.x86_64.rpm
 elasticsearch-py-6.3.0.tar.gz

**Comment by m2cci-KGY** [comment]
python
Python 2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elasticsearch
>>> print elasticsearch.__version__
(6, 3, 0)

**Comment by m2cci-KGY** [comment]
Merci je l'ai corrigé

**Comment by m2cci-KGY** [comment]
Mais j'ai un nouveau problème
 Could not import bare 'module.py' from /var/lib/shinken/modules/elastic-logs : No module named curator
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Shinken-2.4.3-py2.7.egg/shinken/modulesmanager.py", line 114, in try_very_bad_load
    return importlib.import_module('module')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/shinken/modules/elastic-logs/module.py", line 41, in <module>
    import curator
ImportError: No module named curator

**Comment by m2cci-KGY** [comment]
Pourtant il est installé "elasticsearch-curator"

**Comment by m2cci-KGY** [comment]
Je fais la même procédure Merci

**Comment by vaxvms** [comment]
Visiblement, il n'est pas installé correctement puisque l'import echoue

**Comment by m2cci-KGY** [comment]
J'ai installé la version elasticsearch-curator-5.5.4-1

**Comment by m2cci-KGY** [comment]
c'est package rpm car la version tar me demmandé de changer mon package setuptoools à une version supérieur

**Comment by m2cci-KGY** [comment]
J'ai vérifier dans les logs de shinken : 
J'ai ça comme erreur
[elastic-logs] exception while checking the existance of the index shinken-2018.08.07: ConnectionError(('Connection aborted.', error(111, 'Connection refused'))) caused by: ProtocolError(('Connection aborted.', error(111, 'Connection refused')))

**Comment by hvad** [comment]
Bonjour,

Pourquoi vous n'utilisez pas l'agent Beat d'elasticsearch pour transférer
les fichiers journaux de shinken ? Cela me semble plus simple comme méthode.

Bonne journée

**Comment by m2cci-KGY** [comment]
Bonjour moi je voudrais remonté les informations sur les environnements de bas niveau comme les infos sur les disques de stockages, cpu ....... est-il possiblme avec les agents beats?
Merci

**Comment by hvad** [comment]
Bonjour,
Certainement si l'agent récupère un fichier des données de performance. Je connais plus Splunk et le principe est le même. 
Bonne recherche
