### ISSUE TITLE
Retention in webui2

### ISSUE THREAD

**Issue by esebille** [naparuba/shinken#1978]
hello,
i think i do not understand how the retention works in shinken, i have modules for retention but it doesnt seems to work.

here's the result of the command :
`shinken inventory
ui-pnp
imap
ldap
rhev
http-proxy
retention-redis
dns
mod-mongodb
smtp
switch
graphite
ui-graphite2
mongodb
dhcp
ssh
mod-mongodb-notification-broker
pack-rhev
oracle
graphite2
linux-ssh
linux-snmp
pickle-retention-file-scheduler
logstore-mongodb
mod-mongodb-dt-ct-retention-scheduler
auth-active-directory
mod-influxdb
logstore-sqlite
mongo-logs
http
webui2
webui
hp
livestatus
mod-mongodb-retention-scheduler
ui-graphite
windows`
Thanks

**Comment by geektophe** [comment]
I'm not sure to understand what you're asking...

**Comment by esebille** [comment]
i want to be able to do a yearly report of hosts state.

**Comment by geektophe** [comment]
This seems to be a WebUI related question. You'd better open a ticket on https://github.com/shinken-monitoring/mod-webui
