### ISSUE TITLE
Business rules downtime/acknowledge

### ISSUE THREAD

**Issue by vkuharkov** [naparuba/shinken#1992]
Hello!

I have problem with a business rule in shinken.
Repeat:
1. I have a hostgroup, a group that the business rule is configured for
2. I off a host, he in status "CRITICAL"
3. business rule goes into state "CRITICAL"
4. I doing downtime or acknowledge this host

I expect the business rule to become OK.

business_rule_smart_notifications and business_rule_downtime_as_ack on.

I need alerts to come from a business rule when one of the hosts is in downtime or acknowledge, but crashed another host. But since the business rule in critical notification state does not come. Notification come only from host.

Please help!
Thanks!

**Comment by vkuharkov** [comment]
Is there anyone? :(

**Comment by fpeyre** [comment]
I think I had the same issue, and create a PR for that
https://github.com/naparuba/shinken/pull/1837

**Comment by vkuharkov** [comment]
Thanks
