### ISSUE TITLE
Ubuntu 20.04 -  except KeyError, exp:

### ISSUE THREAD

**Issue by gamersalpha** [naparuba/shinken#2006]
Hello so i try to install Shinekn and i got this error , can u tell me what is wrong please : 

```

root@pxe01:/home/stagiaire/shinken-2.4.3# python setup.py instal
  File "setup.py", line 124
    except KeyError, exp:
                   ^
SyntaxError: invalid syntax
```

```
root@pxe01:/home/stagiaire/shinken-2.4.3# python -V
Python 3.8.5
```

i m stuck please help

**Comment by andonovski** [comment]
I have same issue, Ubuntu 20.04, python 3.8.5$, downloaded version 2.4.3 and run python setup.py install.
Also, tried setup using PIP and got same error

**Comment by naparuba** [comment]
Currently only python 2 is managed, the python3 is in a dev branch, not released yet.
