### ISSUE TITLE
Spare configuration for a distant poller doesn't work

### ISSUE THREAD

**Issue by banderas07** [naparuba/shinken#403]
I have the following configuration: 
 define poller{
           poller_name      poller-1
           address          localhost
           port             7771
           # optional
           manage_sub_realms 0      ; optional and advanced: does it take jobs from schedulers of sub realms?
           min_workers       0      ; optional : starts with N worker processes. 0 means : "number of cpus"
           max_workers       0      ; optional : no more than N worker processes. 0 means : "number of cpus"
           processes_by_worker      256        ; optional : each worker manages 256 checks
           polling_interval         1       ; optional : get jobs from schedulers each 1 second
           timeout          3             ; 'ping' timeout
           data_timeout     120           ; 'data send' timeout
           check_interval           60    ; ping it every minute
           max_check_attempts       3     ;  if at least max_check_attempts ping failed, the node is DEAD
           #  advanced features
           # modules                NrpeBooster,CommandFile
           #  NRPE Boster will avoid to use the check_nrpe binary
           #       and so can enhance your performances if you have
           #       lot of nrpe calls
           #  CommandFile can allow a nagios.cmd named pipe to be read by the
           #       poller. This permits the use of distributed check_mk checks should you desire it.
           # poller_tags    None
           realm            All
            spare           1
            poller_tags     poller2, None
    }
    define poller{
            poller_name     poller-2
            address         Distant-poller-IP
            port            7771
            poller_tags     poller2
            spare           0
    }

Where poller-1 is the local poller and poller-2 is the distant poller. According to the documentation and shinken forum when the connection to the poller-2 will be broken poller-1 will take the checks instead - this works. The problem is that the untagged checks that were normally run by poller-1 are not run anymore even if poller-1 has "None" tag.
Additional information: on the machine running poller-1 are also started the other shinken daemons.

**Comment by nitin-tm** [comment]
Hi ,

i have following config on 10.133.12.163  with seperate files for arbiter-spare,arbiter-master,arbiter master-1

 arbiter_name    arbiter-spare
 host_name       nitin-Desktop       
 address         10.133.12.163   
 port            5015
 spare           1  

arbiter_name    arbiter-master
 host_name       kapil-Desktop       
 address         10.133.19.165   
 port            5015
 spare           0 

arbiter_name    arbiter-master-1
 host_name       kapil-Desktop       
 address         10.133.19.165   
 port            5012
 spare           0 

two seperate shinken installaton on 10.133.19.165 with different ports.i have same 3 files for all process.

I am making two master one spare set-up .spare set up have this kind of config for all processs.

Now when i stop the shinken process on 10.133.19.165  with port 5015 . spare set up comes alive and start monitoring services.
but when i try to stop the shinken process on 10.133.19.165 with port 5012 ,it does not automatically start on spare.

why this is case ,Can't we make two master on spare ?

will the simultaneous multiple master-spare set up will work ?
