### ISSUE TITLE
Result modulation and escalation documentation

### ISSUE THREAD

**Issue by xkilian** [naparuba/shinken#574]
Can these two features actually be used? If so, please document their use and how to define them in the wiki under :

Under object definitions, or maybe advanced scheduler configurations.

These two "defines" got clobbered in the shinken-specific.cfg update.

A result modulation is use to module a check result, like CRITICAL->WARNING here

```
define resultmodulation{
    resultmodulation_name     critical_is_warning           ; required
    exit_codes_match          2       ; optional, list of code to change
    output_match              //      ; optional, regexp for activation of exit_code if output match
    exit_code_modulation      1       ; code that will be put if the code match
    output_modulation         s///    ; optional regexp to change output
    longoutput_modulation     s///    ; optional regexp to change long_output
    modulation_period         24×7    ; period when to apply the modulation
}
```

Escalation is a generic version of service_escalation and host_escalation
It can be called by services/hosts so it will be far more easier to be
configured

```
define escalation{
    escalation_name		ToLevel2           ; required
    first_notification  	2
    last_notification   	5
    notification_interval	1
    escalation_period	24x7          ; optional, if none, always true
    escalation_options	d,u,r,w,c     ; optional, if none, all states (d,u,r,w,c)
    contacts			dbrosseau
    #contact_groups		admins
}
```

**Comment by Seb-Solon** [comment]
In 2.4 resultmodulation has to be linked to something (an host) to be checked. Same for escalation : this escalation does nothing if there is not hostgroup or host linked. 

Doc could be updated at least to clarify this
