### ISSUE TITLE
Feature request= ignore bp_rules at check

### ISSUE THREAD

**Issue by Denetariko** [naparuba/shinken#636]
Hi

When using some external config tool (Nconf, NagiosQL, Centreon,..) we can not define a "bp_rule" command because check fails (duplicate).  
So, we can no define any object at config tool containing bp_rules (must use external text files manually edited). And we can not edit at config tool any object related with these (dependencies, groups,...) because tool needs "bp_rule" checked object into his database for using it on other objects..

I've tryed (Nagiosql) to define objects with "register" mark disabled, so I can use them on others to define dependencies (example)...I can define ok the dependency but when writing the cfg files this line does not appear since object is not registered --> no writed to cfg file.

So I suggest as Shinken feature => when checking commands.cfg file (or "define command" directive) just ignore any line "define command bp_rule. With this line ignored, we can define at config tool a command like

define command {
   command_name                      bp_rule
   command_line                      bp_rule!($ARG1)
   register                          1
}   

And then we could define in our config tool a host or service using bp_rule command. At config tool will write into $ARG1$ needed text  to compose the rule ok.
( host_name      my_cluster
   check_command   bp_rule
                       $ARG1$                   2,1,2of: member1 | member2
)
since ARGs usually are free text fields we could define as needed..

Shinken, when compiling and creatins his own configuration (I don't know how it is stored) just should ignore the bp_rule command definition from cfg's  and follow his tasks...
Only requirement is that when cfg file for host is writed text must be "well" generated to shinken read it...

It should work, I think. And would permit full use of config tools avoiding text file usage
thanks if you consideer it as good feature.

**Comment by naparuba** [comment]
It's up to the external tools to manage. I prefer not to complexify the framework for such use case of external tools :)
