### ISSUE TITLE
add support for anag (android app with widget support)

### ISSUE THREAD

**Issue by kiranos** [naparuba/shinken#650]
I would like that anag supported Shinken, we use it heavily for its widget of active alarms.
http://damien.degois.info/android/aNag/summary

It supports cgi and json (icinga 1.6+) Would be great if shinken ui could generate these compatible json output. 

With anag support there is no need for shinkens own app.

**Comment by naparuba** [comment]
I close as it do not impact framework now :)

**Comment by babs** [comment]
Just an update for late readers. The best way is to use Thruk and connect aNag to it :)

**Comment by naparuba** [comment]
Really cool ^^
