### ISSUE TITLE
initial_state doesn't seem to work

### ISSUE THREAD

**Issue by DessaiImrane** [naparuba/shinken#828]
Following @naparuba  advice, I open this issue 

The original post is here : 
http://www.shinken-monitoring.org/forum/index.php/topic,886.0.html

**Comment by SLoeuillet** [comment]
Service notifications are only sent for services attached to a host that is UP.
See :
shinken/objects/service.py
def notification_is_blocked_by_item(self, type, t_wished=None):

        # Block if host is down
        if self.host.state != self.host.ok_up:
            return True

The comment is wrong : it would only notify is host is UP, not in PENDING/UNKNOWN.

In the case of passive checks via SNMP TRAPS => external_command, as those hosts aren't actively checked, their state is PENDING.

So I tried to force their initial_state to "UP" (o)
Then, grepping the code, I saw the config option was parsed but no used ...

Do you have a solution ?

**Comment by olivierHa** [comment]
initial_state is now handled by Shinken
