### ISSUE TITLE
No notification for service in down state when host changes state 

### ISSUE THREAD

**Issue by eliaz** [naparuba/shinken#857]
I have tested the following
1. I configure  a service with check_dummy|0|... and restart shinken
2. I force the service the host are attached to to down state I(Now I get a notification about host down after  some recheck's)
3. I force the service  to down state by reconfiguring it to  check_dummy|2... - and I restart shinken. I wait for some rechecks and  dont get notification( as expected)
4. I make the host  go to UP state. Now I get notification about recovery of the host, but I never get notification about the service being down!

(It seems the service   maybe never leaves state its in(soft). e.g  1/2(hard/state. After the  host has recovered the service  just gets stuck in the state, even if I do manual rechecks.)

**Comment by Seb-Solon** [comment]
Case is not enough clear. Reopen if you can provide configuration sample in the current Shinken version
